/*
 Fuse.js v3.2.0 - Lightweight fuzzy-search (http://fusejs.io)

 Copyright (c) 2012-2017 Kirollos Risk (http://kiro.me)
 All Rights Reserved. Apache Software License 2.0

 http://www.apache.org/licenses/LICENSE-2.0
 Hammer.JS - v2.0.7 - 2016-04-22
 http://hammerjs.github.io/

 Copyright (c) 2016 Jorik Tangelder;
 Licensed under the MIT license */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(g,A,z){g!=Array.prototype&&g!=Object.prototype&&(g[A]=z.value)};$jscomp.getGlobal=function(g){return"undefined"!=typeof window&&window===g?g:"undefined"!=typeof global&&null!=global?global:g};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(g){return $jscomp.SYMBOL_PREFIX+(g||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var g=$jscomp.global.Symbol.iterator;g||(g=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[g]&&$jscomp.defineProperty(Array.prototype,g,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(g){var A=0;return $jscomp.iteratorPrototype(function(){return A<g.length?{done:!1,value:g[A++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(g){$jscomp.initSymbolIterator();g={next:g};g[$jscomp.global.Symbol.iterator]=function(){return this};return g};$jscomp.makeIterator=function(g){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var A=g[Symbol.iterator];return A?A.call(g):$jscomp.arrayIterator(g)};$jscomp.arrayFromIterator=function(g){for(var A,z=[];!(A=g.next()).done;)z.push(A.value);return z};$jscomp.arrayFromIterable=function(g){return g instanceof Array?g:$jscomp.arrayFromIterator($jscomp.makeIterator(g))};
$jscomp.iteratorFromArray=function(g,A){$jscomp.initSymbolIterator();g instanceof String&&(g+="");var z=0,q={next:function(){if(z<g.length){var x=z++;return{value:A(x,g[x]),done:!1}}q.next=function(){return{done:!0,value:void 0}};return q.next()}};q[Symbol.iterator]=function(){return q};return q};
$jscomp.polyfill=function(g,A,z,q){if(A){z=$jscomp.global;g=g.split(".");for(q=0;q<g.length-1;q++){var x=g[q];x in z||(z[x]={});z=z[x]}g=g[g.length-1];q=z[g];A=A(q);A!=q&&null!=A&&$jscomp.defineProperty(z,g,{configurable:!0,writable:!0,value:A})}};$jscomp.polyfill("Array.prototype.keys",function(g){return g?g:function(){return $jscomp.iteratorFromArray(this,function(g){return g})}},"es6","es3");
$jscomp.polyfill("Array.from",function(g){return g?g:function(g,z,q){$jscomp.initSymbolIterator();z=null!=z?z:function(p){return p};var x=[],D=g[Symbol.iterator];if("function"==typeof D)for(g=D.call(g);!(D=g.next()).done;)x.push(z.call(q,D.value));else{D=g.length;for(var p=0;p<D;p++)x.push(z.call(q,g[p]))}return x}},"es6","es3");$jscomp.polyfill("Array.prototype.entries",function(g){return g?g:function(){return $jscomp.iteratorFromArray(this,function(g,z){return[g,z]})}},"es6","es3");
(function(){var g="undefined"===typeof global?self:global;if("function"!==typeof g.require){var A={},z={},q={},x={}.hasOwnProperty,D=/^\.\.?(\/|$)/,p=function(a,c){var h=[];c=(D.test(c)?a+"/"+c:c).split("/");for(var u=0,f=c.length;u<f;u++)a=c[u],".."===a?h.pop():"."!==a&&""!==a&&h.push(a);return h.join("/")},B=function(a){return function(c){c=p(a.split("/").slice(0,-1).join("/"),c);return g.require(c,a)}},n=function(a){return q[a]?n(q[a]):a},m=function(a,c){return n(p(a.split("/").slice(0,-1).join("/"),
c))},v=function(a,u){null==u&&(u="/");var h=n(a);if(x.call(z,h))return z[h].exports;if(x.call(A,h))return a=A[h],u=c&&c.createHot(h),u={id:h,exports:{},hot:u},z[h]=u,a(u.exports,B(h),u),u.exports;throw Error("Cannot find module '"+a+"' from '"+u+"'");};v.alias=function(a,c){q[c]=a};var r=/\.[^.\/]+$/,d=/\/index(\.[^\/]+)?$/;v.register=v.define=function(a,c){if(a&&"object"===typeof a)for(var h in a)x.call(a,h)&&v.register(h,a[h]);else A[a]=c,delete z[a],r.test(a)&&(c=a.replace(r,""),x.call(q,c)&&q[c].replace(r,
"")!==c+"/index"||(q[c]=a)),d.test(a)&&(c=a.replace(d,""),x.call(q,c)||(q[c]=a))};v.list=function(){var a=[],c;for(c in A)x.call(A,c)&&a.push(c);return a};var c=g._hmr&&new g._hmr(m,v,A,z);v._cache=z;v.hmr=c&&c.wrap;v.brunch=!0;g.require=v}})();
(function(){var g="undefined"===typeof window?this:window,A=function(g,q,x){var D={},p=function(B,n){var m;try{return m=g(n+"/node_modules/"+B)}catch(v){if(-1===v.toString().indexOf("Cannot find module"))throw v;if(-1!==n.indexOf("node_modules"))return n=n.split("/"),m=n.lastIndexOf("node_modules"),n=n.slice(0,m).join("/"),p(B,n)}return D};return function(B){B in q&&(B=q[B]);if(B){if("."!==B[0]&&x){var n=p(B,x);if(n!==D)return n}return g(B)}}};require.register("@fdaciuk/ajax/dist/ajax.min.js",function(g,
q,x){q=A(q,{},"@fdaciuk/ajax");(function(){!function(D,p){"function"==typeof define&&define.amd?define("ajax",p):"object"==typeof g?g=x.exports=p():D.ajax=p()}(this,function(){function g(c,a,d,h){var u=["then","catch","always"].reduce(function(a,c){return a[c]=function(f){return a[c]=f,a},a},{}),f=new XMLHttpRequest;a=p(a,d,c);return f.open(c,a,!0),f.withCredentials=h.hasOwnProperty("withCredentials"),B(f,h.headers),f.addEventListener("readystatechange",m(u,f),!1),f.send(r(d)),u.abort=function(){return f.abort()},
u}function p(c,a,d){if("get"!==d.toLowerCase()||!a)return c;a=r(a);d=-1<c.indexOf("?")?"\x26":"?";return c+d+a}function B(c,a){a=a||{};n(a)||(a["Content-Type"]="application/x-www-form-urlencoded");Object.keys(a).forEach(function(d){a[d]&&c.setRequestHeader(d,a[d])})}function n(c){return Object.keys(c).some(function(a){return"content-type"===a.toLowerCase()})}function m(c,a){return function h(){a.readyState===a.DONE&&(a.removeEventListener("readystatechange",h,!1),c.always.apply(c,v(a)),200<=a.status&&
300>a.status?c.then.apply(c,v(a)):c["catch"].apply(c,v(a)))}}function v(c){try{var a=JSON.parse(c.responseText)}catch(u){a=c.responseText}return[a,c]}function r(c){return"[object Object]"===Object.prototype.toString.call(c)?d(c):c}function d(c){return Object.keys(c).reduce(function(a,d){return(a?a+"\x26":"")+encodeURIComponent(d)+"\x3d"+encodeURIComponent(c[d])},"")}return function(c){var a=["get","post","put","delete"];return c=c||{},c.baseUrl=c.baseUrl||"",c.method&&c.url?g(c.method,c.baseUrl+c.url,
c.data||null,c):a.reduce(function(a,h){return a[h]=function(a,f){return g(h,c.baseUrl+a,f||null,c)},a},{})}})})()});require.register("fuse.js/dist/fuse.js",function(g,q,x){q=A(q,{},"fuse.js");(function(){(function(D,p){"object"===typeof g&&"object"===typeof x?x.exports=p():"function"===typeof define&&define.amd?define("Fuse",[],p):"object"===typeof g?g.Fuse=p():D.Fuse=p()})(this,function(){return function(g){function p(n){if(D[n])return D[n].exports;var m=D[n]={i:n,l:!1,exports:{}};g[n].call(m.exports,
m,m.exports,p);m.l=!0;return m.exports}var D={};p.m=g;p.c=D;p.i=function(n){return n};p.d=function(n,m,g){p.o(n,m)||Object.defineProperty(n,m,{configurable:!1,enumerable:!0,get:g})};p.n=function(n){var m=n&&n.__esModule?function(){return n["default"]}:function(){return n};p.d(m,"a",m);return m};p.o=function(n,m){return Object.prototype.hasOwnProperty.call(n,m)};p.p="";return p(p.s=8)}([function(g,p,B){g.exports=function(n){return"[object Array]"===Object.prototype.toString.call(n)}},function(g,p,
B){var n=function(){function d(c,a){for(var d=0;d<a.length;d++){var h=a[d];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(c,h.key,h)}}return function(c,a,u){a&&d(c.prototype,a);u&&d(c,u);return c}}(),m=B(5),v=B(7),r=B(4);p=function(){function d(c,a){var u=a.location;u=void 0===u?0:u;var h=a.distance;h=void 0===h?100:h;var m=a.threshold;m=void 0===m?.6:m;var f=a.maxPatternLength;f=void 0===f?32:f;var l=a.isCaseSensitive;l=void 0===l?!1:l;var w=a.tokenSeparator;
w=void 0===w?/ +/g:w;var e=a.findAllMatches;e=void 0===e?!1:e;a=a.minMatchCharLength;a=void 0===a?1:a;if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");this.options={location:u,distance:h,threshold:m,maxPatternLength:f,isCaseSensitive:l,tokenSeparator:w,findAllMatches:e,minMatchCharLength:a};this.pattern=this.options.isCaseSensitive?c:c.toLowerCase();this.pattern.length<=f&&(this.patternAlphabet=r(this.pattern))}n(d,[{key:"search",value:function(c){this.options.isCaseSensitive||
(c=c.toLowerCase());if(this.pattern===c)return{isMatch:!0,score:0,matchedIndices:[[0,c.length-1]]};var a=this.options,d=a.tokenSeparator;if(this.pattern.length>a.maxPatternLength)return m(c,this.pattern,d);a=this.options;return v(c,this.pattern,this.patternAlphabet,{location:a.location,distance:a.distance,threshold:a.threshold,findAllMatches:a.findAllMatches,minMatchCharLength:a.minMatchCharLength})}}]);return d}();g.exports=p},function(g,p,B){var n=B(0),m=function r(d,c,a){if(c){var u=c.indexOf("."),
h=c,m=null;-1!==u&&(h=c.slice(0,u),m=c.slice(u+1));d=d[h];if(null!==d&&void 0!==d)if(m||"string"!==typeof d&&"number"!==typeof d)if(n(d))for(c=0,u=d.length;c<u;c+=1)r(d[c],m,a);else m&&r(d,m,a);else a.push(d.toString())}else a.push(d);return a};g.exports=function(n,d){return m(n,d,[])}},function(g,p,B){g.exports=function(){for(var n=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],m=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,p=[],r=-1,d,c=0,a=n.length;c<a;c+=1)(d=n[c])&&-1===
r?r=c:d||-1===r||(d=c-1,d-r+1>=m&&p.push([r,d]),r=-1);n[c-1]&&c-r>=m&&p.push([r,c-1]);return p}},function(g,p,B){g.exports=function(n){for(var m={},p=n.length,r=0;r<p;r+=1)m[n.charAt(r)]=0;for(r=0;r<p;r+=1)m[n.charAt(r)]|=1<<p-r-1;return m}},function(g,p,B){var n=/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g;g.exports=function(m,p){var g=2<arguments.length&&void 0!==arguments[2]?arguments[2]:/ +/g;g=new RegExp(p.replace(n,"\\$\x26").replace(g,"|"));g=m.match(g);var d=!!g,c=[];if(d)for(var a=0,u=g.length;a<
u;a+=1){var h=g[a];c.push([m.indexOf(h),h.length-1])}return{score:d?.5:1,isMatch:d,matchedIndices:c}}},function(g,p,B){g.exports=function(n,m){var p=m.errors,g=m.currentLocation,d=m.expectedLocation;m=m.distance;m=void 0===m?100:m;n=(void 0===p?0:p)/n.length;g=Math.abs((void 0===d?0:d)-(void 0===g?0:g));return m?n+g/m:g?1:n}},function(g,p,B){var n=B(6),m=B(3);g.exports=function(g,p,d,c){var a=c.location,u=c.distance;u=void 0===u?100:u;var h=c.threshold,y=c.findAllMatches;y=void 0===y?!1:y;c=c.minMatchCharLength;
c=void 0===c?1:c;a=void 0===a?0:a;var f=g.length;h=void 0===h?.6:h;for(var l=g.indexOf(p,a),w=p.length,e=[],b=0;b<f;b+=1)e[b]=0;-1!==l&&(l=n(p,{errors:0,currentLocation:l,expectedLocation:a,distance:u}),h=Math.min(l,h),l=g.lastIndexOf(p,a+w),-1!==l&&(l=n(p,{errors:0,currentLocation:l,expectedLocation:a,distance:u}),h=Math.min(l,h)));l=-1;b=[];for(var k=1,H=w+f,C=1<<w-1,I=0;I<w;I+=1){for(var O=0,G=H;O<G;)n(p,{errors:I,currentLocation:a+G,expectedLocation:a,distance:u})<=h?O=G:H=G,G=Math.floor((H-O)/
2+O);H=G;O=Math.max(1,a-G+1);var K=y?f:Math.min(a+G,f)+w;G=Array(K+2);for(G[K+1]=(1<<I)-1;K>=O;--K){var L=K-1,F=d[g.charAt(L)];F&&(e[L]=1);G[K]=(G[K+1]<<1|1)&F;0!==I&&(G[K]=G[K]|(b[K+1]|b[K])<<1|1|b[K+1]);if(G[K]&C&&(k=n(p,{errors:I,currentLocation:L,expectedLocation:a,distance:u}),k<=h)){h=k;l=L;if(l<=a)break;O=Math.max(1,2*a-l)}}if(n(p,{errors:I+1,currentLocation:a,expectedLocation:a,distance:u})>h)break;b=G}return{isMatch:0<=l,score:0===k?.001:k,matchedIndices:m(e,c)}}},function(g,p,B){var n=function(){function d(c,
a){for(var d=0;d<a.length;d++){var h=a[d];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(c,h.key,h)}}return function(c,a,u){a&&d(c.prototype,a);u&&d(c,u);return c}}(),m=B(1),v=B(2),r=B(0);p=function(){function d(c,a){var u=a.location;u=void 0===u?0:u;var h=a.distance;h=void 0===h?100:h;var m=a.threshold;m=void 0===m?.6:m;var f=a.maxPatternLength;f=void 0===f?32:f;var l=a.caseSensitive;l=void 0===l?!1:l;var w=a.tokenSeparator;w=void 0===w?/ +/g:w;
var e=a.findAllMatches;e=void 0===e?!1:e;var b=a.minMatchCharLength;b=void 0===b?1:b;var k=a.id;k=void 0===k?null:k;var H=a.keys;H=void 0===H?[]:H;var C=a.shouldSort;C=void 0===C?!0:C;var I=a.getFn;I=void 0===I?v:I;var p=a.sortFn;p=void 0===p?function(b,a){return b.score-a.score}:p;var G=a.tokenize;G=void 0===G?!1:G;var n=a.matchAllTokens;n=void 0===n?!1:n;var g=a.includeMatches;g=void 0===g?!1:g;var F=a.includeScore;F=void 0===F?!1:F;a=a.verbose;a=void 0===a?!1:a;if(!(this instanceof d))throw new TypeError("Cannot call a class as a function");
this.options={location:u,distance:h,threshold:m,maxPatternLength:f,isCaseSensitive:l,tokenSeparator:w,findAllMatches:e,minMatchCharLength:b,id:k,keys:H,includeMatches:g,includeScore:F,shouldSort:C,getFn:I,sortFn:p,verbose:a,tokenize:G,matchAllTokens:n};this.setCollection(c)}n(d,[{key:"setCollection",value:function(c){return this.list=c}},{key:"search",value:function(c){this._log('---------\nSearch pattern: "'+c+'"');c=this._prepareSearchers(c);c=this._search(c.tokenSearchers,c.fullSearcher);var a=
c.results;this._computeScore(c.weights,a);this.options.shouldSort&&this._sort(a);return this._format(a)}},{key:"_prepareSearchers",value:function(){var c=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"",a=[];if(this.options.tokenize)for(var d=c.split(this.options.tokenSeparator),h=0,p=d.length;h<p;h+=1)a.push(new m(d[h],this.options));c=new m(c,this.options);return{tokenSearchers:a,fullSearcher:c}}},{key:"_search",value:function(){var c=0<arguments.length&&void 0!==arguments[0]?arguments[0]:
[],a=arguments[1],d=this.list,h={},m=[];if("string"===typeof d[0]){for(var f=0,l=d.length;f<l;f+=1)this._analyze({key:"",value:d[f],record:f,index:f},{resultMap:h,results:m,tokenSearchers:c,fullSearcher:a});return{weights:null,results:m}}f={};l=0;for(var w=d.length;l<w;l+=1)for(var e=d[l],b=0,k=this.options.keys.length;b<k;b+=1){var H=this.options.keys[b];if("string"!==typeof H){f[H.name]={weight:1-H.weight||1};if(0>=H.weight||1<H.weight)throw Error("Key weight has to be \x3e 0 and \x3c\x3d 1");H=
H.name}else f[H]={weight:1};this._analyze({key:H,value:this.options.getFn(e,H),record:e,index:l},{resultMap:h,results:m,tokenSearchers:c,fullSearcher:a})}return{weights:f,results:m}}},{key:"_analyze",value:function(c,a){var d=c.key,h=c.arrayIndex,m=void 0===h?-1:h;h=c.value;var f=c.record;c=c.index;var l=a.tokenSearchers;l=void 0===l?[]:l;var w=a.fullSearcher,e=void 0===w?[]:w;w=a.resultMap;w=void 0===w?{}:w;a=a.results;a=void 0===a?[]:a;if(void 0!==h&&null!==h){var b=!1,k=-1,H=0;if("string"===typeof h){this._log("\nKey: "+
(""===d?"-":d));e=e.search(h);this._log('Full text: "'+h+'", score: '+e.score);if(this.options.tokenize){k=h.split(this.options.tokenSeparator);for(var C=[],I=0;I<l.length;I+=1){var p=l[I];this._log('\nPattern: "'+p.pattern+'"');for(var G=!1,n=0;n<k.length;n+=1){var g=k[n],F=p.search(g),E={};F.isMatch?(E[g]=F.score,G=b=!0,C.push(F.score)):(E[g]=1,this.options.matchAllTokens||C.push(1));this._log('Token: "'+g+'", score: '+E[g])}G&&(H+=1)}k=C[0];I=C.length;for(p=1;p<I;p+=1)k+=C[p];k/=I;this._log("Token score average:",
k)}C=e.score;-1<k&&(C=(C+k)/2);this._log("Score average:",C);l=this.options.tokenize&&this.options.matchAllTokens?H>=l.length:!0;this._log("\nCheck Matches: "+l);(b||e.isMatch)&&l&&((l=w[c])?l.output.push({key:d,arrayIndex:m,value:h,score:C,matchedIndices:e.matchedIndices}):(w[c]={item:f,output:[{key:d,arrayIndex:m,value:h,score:C,matchedIndices:e.matchedIndices}]},a.push(w[c])))}else if(r(h))for(m=0,b=h.length;m<b;m+=1)this._analyze({key:d,arrayIndex:m,value:h[m],record:f,index:c},{resultMap:w,results:a,
tokenSearchers:l,fullSearcher:e})}}},{key:"_computeScore",value:function(c,a){this._log("\n\nComputing score:\n");for(var d=0,h=a.length;d<h;d+=1){for(var m=a[d].output,f=m.length,l=0,w=1,e=0;e<f;e+=1){var b=c?c[m[e].key].weight:1,k=(1===b?m[e].score:m[e].score||.001)*b;1!==b?w=Math.min(w,k):(m[e].nScore=k,l+=k)}a[d].score=1===w?l/f:w;this._log(a[d])}}},{key:"_sort",value:function(c){this._log("\n\nSorting....");c.sort(this.options.sortFn)}},{key:"_format",value:function(c){var a=[];this._log("\n\nOutput:\n\n",
JSON.stringify(c));var d=[];this.options.includeMatches&&d.push(function(b,a){b=b.output;a.matches=[];for(var c=0,k=b.length;c<k;c+=1){var f=b[c];if(0!==f.matchedIndices.length){var e={indices:f.matchedIndices,value:f.value};f.key&&(e.key=f.key);f.hasOwnProperty("arrayIndex")&&-1<f.arrayIndex&&(e.arrayIndex=f.arrayIndex);a.matches.push(e)}}});this.options.includeScore&&d.push(function(b,a){a.score=b.score});for(var h=0,m=c.length;h<m;h+=1){var f=c[h];this.options.id&&(f.item=this.options.getFn(f.item,
this.options.id)[0]);if(d.length){for(var l={item:f.item},w=0,e=d.length;w<e;w+=1)d[w](f,l);a.push(l)}else a.push(f.item)}return a}},{key:"_log",value:function(){if(this.options.verbose){var c;(c=console).log.apply(c,arguments)}}}]);return d}();g.exports=p}])})})()});require.register("hammerjs/hammer.js",function(g,q,x){q=A(q,{},"hammerjs");(function(){(function(g,p,B,n){function m(b,c,f){return setTimeout(a(b,f),c)}function v(b,a,c){return Array.isArray(b)?(r(b,c[a],c),!0):!1}function r(b,a,c){var t;
if(b)if(b.forEach)b.forEach(a,c);else if(b.length!==n)for(t=0;t<b.length;)a.call(c,b[t],t,b),t++;else for(t in b)b.hasOwnProperty(t)&&a.call(c,b[t],t,b)}function d(b,a,c){var t="DEPRECATED METHOD: "+a+"\n"+c+" AT \n";return function(){var a=Error("get-stack-trace");a=a&&a.stack?a.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@"):"Unknown Stack Trace";var c=g.console&&(g.console.warn||g.console.log);c&&c.call(g.console,t,a);return b.apply(this,
arguments)}}function c(b,a,c){a=a.prototype;var t=b.prototype=Object.create(a);t.constructor=b;t._super=a;c&&R(t,c)}function a(b,a){return function(){return b.apply(a,arguments)}}function u(b,a){return"function"==typeof b?b.apply(a?a[0]||n:n,a):b}function h(b,a,c){r(l(a),function(t){b.addEventListener(t,c,!1)})}function y(b,a,c){r(l(a),function(t){b.removeEventListener(t,c,!1)})}function f(b,a){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}function l(b){return b.trim().split(/\s+/g)}function w(b,
a,c){if(b.indexOf&&!c)return b.indexOf(a);for(var t=0;t<b.length;){if(c&&b[t][c]==a||!c&&b[t]===a)return t;t++}return-1}function e(b){return Array.prototype.slice.call(b,0)}function b(b,a,c){for(var t=[],f=[],k=0;k<b.length;){var e=a?b[k][a]:b[k];0>w(f,e)&&t.push(b[k]);f[k]=e;k++}c&&(t=a?t.sort(function(b,t){return b[a]>t[a]}):t.sort());return t}function k(b,a){for(var t,c=a[0].toUpperCase()+a.slice(1),f=0;f<ia.length;){t=(t=ia[f])?t+c:a;if(t in b)return t;f++}return n}function H(b){b=b.ownerDocument||
b;return b.defaultView||b.parentWindow||g}function C(b,a){var t=this;this.manager=b;this.callback=a;this.element=b.element;this.target=b.options.inputTarget;this.domHandler=function(a){u(b.options.enable,[b])&&t.handler(a)};this.init()}function I(b){var a=b.options.inputClass;return new (a?a:ta?N:ua?z:ja?Z:q)(b,O)}function O(b,a,c){var t=c.pointers.length,k=c.changedPointers.length;var e=a&1&&0===t-k;c.isFirst=!!e;c.isFinal=!!(a&12&&0===t-k);e&&(b.session={});c.eventType=a;a=b.session;t=c.pointers;
k=t.length;a.firstInput||(a.firstInput=G(c));1<k&&!a.firstMultiple?a.firstMultiple=G(c):1===k&&(a.firstMultiple=!1);e=a.firstInput;var l=(k=a.firstMultiple)?k.center:e.center;var C=c.center=K(t);c.timeStamp=aa();c.deltaTime=c.timeStamp-e.timeStamp;c.angle=E(l,C);c.distance=F(l,C);e=c.center;l=a.offsetDelta||{};C=a.prevDelta||{};var d=a.prevInput||{};if(1===c.eventType||4===d.eventType)C=a.prevDelta={x:d.deltaX||0,y:d.deltaY||0},l=a.offsetDelta={x:e.x,y:e.y};c.deltaX=C.x+(e.x-l.x);c.deltaY=C.y+(e.y-
l.y);c.offsetDirection=L(c.deltaX,c.deltaY);l=c.deltaTime;e=c.deltaX/l||0;l=c.deltaY/l||0;c.overallVelocityX=e;c.overallVelocityY=l;c.overallVelocity=S(e)>S(l)?e:l;k?(e=k.pointers,e=F(t[0],t[1],U)/F(e[0],e[1],U)):e=1;c.scale=e;k?(k=k.pointers,t=E(t[1],t[0],U)+E(k[1],k[0],U)):t=0;c.rotation=t;c.maxPointers=a.prevInput?c.pointers.length>a.prevInput.maxPointers?c.pointers.length:a.prevInput.maxPointers:c.pointers.length;l=a.lastInterval||c;t=c.timeStamp-l.timeStamp;8!=c.eventType&&(25<t||l.velocity===
n)?(e=c.deltaX-l.deltaX,l=c.deltaY-l.deltaY,C=e/t||0,d=l/t||0,t=C,k=d,C=S(C)>S(d)?C:d,e=L(e,l),a.lastInterval=c):(C=l.velocity,t=l.velocityX,k=l.velocityY,e=l.direction);c.velocity=C;c.velocityX=t;c.velocityY=k;c.direction=e;a=b.element;f(c.srcEvent.target,a)&&(a=c.srcEvent.target);c.target=a;b.emit("hammer.input",c);b.recognize(c);b.session.prevInput=c}function G(b){for(var a=[],c=0;c<b.pointers.length;)a[c]={clientX:T(b.pointers[c].clientX),clientY:T(b.pointers[c].clientY)},c++;return{timeStamp:aa(),
pointers:a,center:K(a),deltaX:b.deltaX,deltaY:b.deltaY}}function K(b){var a=b.length;if(1===a)return{x:T(b[0].clientX),y:T(b[0].clientY)};for(var c=0,t=0,k=0;k<a;)c+=b[k].clientX,t+=b[k].clientY,k++;return{x:T(c/a),y:T(t/a)}}function L(b,a){return b===a?1:S(b)>=S(a)?0>b?2:4:0>a?8:16}function F(b,a,c){c||(c=ka);var t=a[c[0]]-b[c[0]];b=a[c[1]]-b[c[1]];return Math.sqrt(t*t+b*b)}function E(b,a,c){c||(c=ka);return 180*Math.atan2(a[c[1]]-b[c[1]],a[c[0]]-b[c[0]])/Math.PI}function q(){this.evEl=va;this.evWin=
wa;this.pressed=!1;C.apply(this,arguments)}function N(){this.evEl=la;this.evWin=ma;C.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function D(){this.evTarget="touchstart";this.evWin="touchstart touchmove touchend touchcancel";this.started=!1;C.apply(this,arguments)}function z(){this.evTarget=xa;this.targetIds={};C.apply(this,arguments)}function A(a,c){var t=e(a.touches),k=this.targetIds;if(c&3&&1===t.length)return k[t[0].identifier]=!0,[t,t];a=e(a.changedTouches);var l=[],
C=this.target;var d=t.filter(function(b){return f(b.target,C)});if(1===c)for(t=0;t<d.length;)k[d[t].identifier]=!0,t++;for(t=0;t<a.length;)k[a[t].identifier]&&l.push(a[t]),c&12&&delete k[a[t].identifier],t++;if(l.length)return[b(d.concat(l),"identifier",!0),l]}function Z(){C.apply(this,arguments);var b=a(this.handler,this);this.touch=new z(this.manager,b);this.mouse=new q(this.manager,b);this.primaryTouch=null;this.lastTouches=[]}function J(b){b=b.changedPointers[0];if(b.identifier===this.primaryTouch){var a=
{x:b.clientX,y:b.clientY};this.lastTouches.push(a);var c=this.lastTouches;setTimeout(function(){var b=c.indexOf(a);-1<b&&c.splice(b,1)},2500)}}function ba(b,a){this.manager=b;this.set(a)}function ya(b){if(-1<b.indexOf("none"))return"none";var a=-1<b.indexOf("pan-x"),c=-1<b.indexOf("pan-y");return a&&c?"none":a||c?a?"pan-x":"pan-y":-1<b.indexOf("manipulation")?"manipulation":"auto"}function P(b){this.options=R({},this.defaults,b||{});this.id=za++;this.manager=null;b=this.options.enable;this.options.enable=
b===n?!0:b;this.state=1;this.simultaneous={};this.requireFail=[]}function na(b){return b&16?"cancel":b&8?"end":b&4?"move":b&2?"start":""}function oa(b){return 16==b?"down":8==b?"up":2==b?"left":4==b?"right":""}function V(b,a){return(a=a.manager)?a.get(b):b}function M(){P.apply(this,arguments)}function W(){M.apply(this,arguments);this.pY=this.pX=null}function ca(){M.apply(this,arguments)}function da(){P.apply(this,arguments);this._input=this._timer=null}function ea(){M.apply(this,arguments)}function fa(){M.apply(this,
arguments)}function X(){P.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function Q(b,a){a=a||{};var c=a.recognizers;a.recognizers=c===n?Q.defaults.preset:c;return new ha(b,a)}function ha(b,a){this.options=R({},Q.defaults,a||{});this.options.inputTarget=this.options.inputTarget||b;this.handlers={};this.session={};this.recognizers=[];this.oldCssProps={};this.element=b;this.input=I(this);this.touchAction=new ba(this,this.options.touchAction);pa(this,!0);r(this.options.recognizers,
function(b){var a=this.add(new b[0](b[1]));b[2]&&a.recognizeWith(b[2]);b[3]&&a.requireFailure(b[3])},this)}function pa(b,a){var c=b.element;if(c.style){var t;r(b.options.cssProps,function(f,e){t=k(c.style,e);a?(b.oldCssProps[t]=c.style[t],c.style[t]=f):c.style[t]=b.oldCssProps[t]||""});a||(b.oldCssProps={})}}function Aa(b,a){var c=p.createEvent("Event");c.initEvent(b,!0,!0);c.gesture=a;a.target.dispatchEvent(c)}var ia=" webkit Moz MS ms o".split(" "),Ba=p.createElement("div"),T=Math.round,S=Math.abs,
aa=Date.now;var R="function"!==typeof Object.assign?function(b){if(b===n||null===b)throw new TypeError("Cannot convert undefined or null to object");for(var a=Object(b),c=1;c<arguments.length;c++){var k=arguments[c];if(k!==n&&null!==k)for(var t in k)k.hasOwnProperty(t)&&(a[t]=k[t])}return a}:Object.assign;var qa=d(function(b,a,c){for(var k=Object.keys(a),t=0;t<k.length;){if(!c||c&&b[k[t]]===n)b[k[t]]=a[k[t]];t++}return b},"extend","Use `assign`."),Ca=d(function(b,a){return qa(b,a,!0)},"merge","Use `assign`."),
za=1,Da=/mobile|tablet|ip(ad|hone|od)|android/i,ja="ontouchstart"in g,ta=k(g,"PointerEvent")!==n,ua=ja&&Da.test(navigator.userAgent),ka=["x","y"],U=["clientX","clientY"];C.prototype={handler:function(){},init:function(){this.evEl&&h(this.element,this.evEl,this.domHandler);this.evTarget&&h(this.target,this.evTarget,this.domHandler);this.evWin&&h(H(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&y(this.element,this.evEl,this.domHandler);this.evTarget&&y(this.target,this.evTarget,
this.domHandler);this.evWin&&y(H(this.element),this.evWin,this.domHandler)}};var Ea={mousedown:1,mousemove:2,mouseup:4},va="mousedown",wa="mousemove mouseup";c(q,C,{handler:function(b){var a=Ea[b.type];a&1&&0===b.button&&(this.pressed=!0);a&2&&1!==b.which&&(a=4);this.pressed&&(a&4&&(this.pressed=!1),this.callback(this.manager,a,{pointers:[b],changedPointers:[b],pointerType:"mouse",srcEvent:b}))}});var Fa={pointerdown:1,pointermove:2,pointerup:4,pointercancel:8,pointerout:8},Ga={2:"touch",3:"pen",
4:"mouse",5:"kinect"},la="pointerdown",ma="pointermove pointerup pointercancel";g.MSPointerEvent&&!g.PointerEvent&&(la="MSPointerDown",ma="MSPointerMove MSPointerUp MSPointerCancel");c(N,C,{handler:function(b){var a=this.store,c=!1,k=b.type.toLowerCase().replace("ms","");k=Fa[k];var f=Ga[b.pointerType]||b.pointerType,e="touch"==f,t=w(a,b.pointerId,"pointerId");k&1&&(0===b.button||e)?0>t&&(a.push(b),t=a.length-1):k&12&&(c=!0);0>t||(a[t]=b,this.callback(this.manager,k,{pointers:a,changedPointers:[b],
pointerType:f,srcEvent:b}),c&&a.splice(t,1))}});var Ha={touchstart:1,touchmove:2,touchend:4,touchcancel:8};c(D,C,{handler:function(a){var c=Ha[a.type];1===c&&(this.started=!0);if(this.started){var k=e(a.touches);var f=e(a.changedTouches);c&12&&(k=b(k.concat(f),"identifier",!0));k=[k,f];c&12&&0===k[0].length-k[1].length&&(this.started=!1);this.callback(this.manager,c,{pointers:k[0],changedPointers:k[1],pointerType:"touch",srcEvent:a})}}});var Ia={touchstart:1,touchmove:2,touchend:4,touchcancel:8},
xa="touchstart touchmove touchend touchcancel";c(z,C,{handler:function(b){var a=Ia[b.type],c=A.call(this,b,a);c&&this.callback(this.manager,a,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:b})}});c(Z,C,{handler:function(b,a,c){var k="mouse"==c.pointerType;if(!(k&&c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents)){if("touch"==c.pointerType)a&1?(this.primaryTouch=c.changedPointers[0].identifier,J.call(this,c)):a&12&&J.call(this,c);else{if(k)a:{k=c.srcEvent.clientX;for(var f=
c.srcEvent.clientY,e=0;e<this.lastTouches.length;e++){var t=this.lastTouches[e],l=Math.abs(f-t.y);if(25>=Math.abs(k-t.x)&&25>=l){k=!0;break a}}k=!1}if(k)return}this.callback(b,a,c)}},destroy:function(){this.touch.destroy();this.mouse.destroy()}});var ra=k(Ba.style,"touchAction"),sa=ra!==n,Y=function(){if(!sa)return!1;var b={},a=g.CSS&&g.CSS.supports;"auto;manipulation;pan-y;pan-x;pan-x pan-y;none".split(";").forEach(function(c){b[c]=a?g.CSS.supports("touch-action",c):!0});return b}();ba.prototype=
{set:function(b){"compute"==b&&(b=this.compute());sa&&this.manager.element.style&&Y[b]&&(this.manager.element.style[ra]=b);this.actions=b.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},compute:function(){var b=[];r(this.manager.recognizers,function(a){u(a.options.enable,[a])&&(b=b.concat(a.getTouchAction()))});return ya(b.join(" "))},preventDefaults:function(b){var a=b.srcEvent,c=b.offsetDirection;if(this.manager.session.prevented)a.preventDefault();else{var k=
this.actions,f=-1<k.indexOf("none")&&!Y.none,e=-1<k.indexOf("pan-y")&&!Y["pan-y"];k=-1<k.indexOf("pan-x")&&!Y["pan-x"];if(f){var l=2>b.distance,t=250>b.deltaTime;if(1===b.pointers.length&&l&&t)return}if(!k||!e)if(f||e&&c&6||k&&c&24)return this.preventSrc(a)}},preventSrc:function(b){this.manager.session.prevented=!0;b.preventDefault()}};P.prototype={defaults:{},set:function(b){R(this.options,b);this.manager&&this.manager.touchAction.update();return this},recognizeWith:function(b){if(v(b,"recognizeWith",
this))return this;var a=this.simultaneous;b=V(b,this);a[b.id]||(a[b.id]=b,b.recognizeWith(this));return this},dropRecognizeWith:function(b){if(v(b,"dropRecognizeWith",this))return this;b=V(b,this);delete this.simultaneous[b.id];return this},requireFailure:function(b){if(v(b,"requireFailure",this))return this;var a=this.requireFail;b=V(b,this);-1===w(a,b)&&(a.push(b),b.requireFailure(this));return this},dropRequireFailure:function(b){if(v(b,"dropRequireFailure",this))return this;b=V(b,this);b=w(this.requireFail,
b);-1<b&&this.requireFail.splice(b,1);return this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(b){return!!this.simultaneous[b.id]},emit:function(b){function a(a){c.manager.emit(a,b)}var c=this,k=this.state;8>k&&a(c.options.event+na(k));a(c.options.event);b.additionalEvent&&a(b.additionalEvent);8<=k&&a(c.options.event+na(k))},tryEmit:function(b){if(this.canEmit())return this.emit(b);this.state=32},canEmit:function(){for(var b=0;b<this.requireFail.length;){if(!(this.requireFail[b].state&
33))return!1;b++}return!0},recognize:function(b){b=R({},b);u(this.options.enable,[this,b])?(this.state&56&&(this.state=1),this.state=this.process(b),this.state&30&&this.tryEmit(b)):(this.reset(),this.state=32)},process:function(b){},getTouchAction:function(){},reset:function(){}};c(M,P,{defaults:{pointers:1},attrTest:function(b){var a=this.options.pointers;return 0===a||b.pointers.length===a},process:function(b){var a=this.state,c=b.eventType,k=a&6;b=this.attrTest(b);return k&&(c&8||!b)?a|16:k||b?
c&4?a|8:a&2?a|4:2:32}});c(W,M,{defaults:{event:"pan",threshold:10,pointers:1,direction:30},getTouchAction:function(){var b=this.options.direction,a=[];b&6&&a.push("pan-y");b&24&&a.push("pan-x");return a},directionTest:function(b){var a=this.options,c=!0,k=b.distance,f=b.direction,e=b.deltaX,l=b.deltaY;f&a.direction||(a.direction&6?(f=0===e?1:0>e?2:4,c=e!=this.pX,k=Math.abs(b.deltaX)):(f=0===l?1:0>l?8:16,c=l!=this.pY,k=Math.abs(b.deltaY)));b.direction=f;return c&&k>a.threshold&&f&a.direction},attrTest:function(b){return M.prototype.attrTest.call(this,
b)&&(this.state&2||!(this.state&2)&&this.directionTest(b))},emit:function(b){this.pX=b.deltaX;this.pY=b.deltaY;var a=oa(b.direction);a&&(b.additionalEvent=this.options.event+a);this._super.emit.call(this,b)}});c(ca,M,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(b){return this._super.attrTest.call(this,b)&&(Math.abs(b.scale-1)>this.options.threshold||this.state&2)},emit:function(b){1!==b.scale&&(b.additionalEvent=this.options.event+(1>
b.scale?"in":"out"));this._super.emit.call(this,b)}});c(da,P,{defaults:{event:"press",pointers:1,time:251,threshold:9},getTouchAction:function(){return["auto"]},process:function(b){var a=this.options,c=b.pointers.length===a.pointers,k=b.distance<a.threshold,f=b.deltaTime>a.time;this._input=b;if(!k||!c||b.eventType&12&&!f)this.reset();else if(b.eventType&1)this.reset(),this._timer=m(function(){this.state=8;this.tryEmit()},a.time,this);else if(b.eventType&4)return 8;return 32},reset:function(){clearTimeout(this._timer)},
emit:function(b){8===this.state&&(b&&b.eventType&4?this.manager.emit(this.options.event+"up",b):(this._input.timeStamp=aa(),this.manager.emit(this.options.event,this._input)))}});c(ea,M,{defaults:{event:"rotate",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(b){return this._super.attrTest.call(this,b)&&(Math.abs(b.rotation)>this.options.threshold||this.state&2)}});c(fa,M,{defaults:{event:"swipe",threshold:10,velocity:.3,direction:30,pointers:1},getTouchAction:function(){return W.prototype.getTouchAction.call(this)},
attrTest:function(b){var a=this.options.direction;if(a&30)var c=b.overallVelocity;else a&6?c=b.overallVelocityX:a&24&&(c=b.overallVelocityY);return this._super.attrTest.call(this,b)&&a&b.offsetDirection&&b.distance>this.options.threshold&&b.maxPointers==this.options.pointers&&S(c)>this.options.velocity&&b.eventType&4},emit:function(b){var a=oa(b.offsetDirection);a&&this.manager.emit(this.options.event+a,b);this.manager.emit(this.options.event,b)}});c(X,P,{defaults:{event:"tap",pointers:1,taps:1,interval:300,
time:250,threshold:9,posThreshold:10},getTouchAction:function(){return["manipulation"]},process:function(b){var a=this.options,c=b.pointers.length===a.pointers,k=b.distance<a.threshold,f=b.deltaTime<a.time;this.reset();if(b.eventType&1&&0===this.count)return this.failTimeout();if(k&&f&&c){if(4!=b.eventType)return this.failTimeout();c=this.pTime?b.timeStamp-this.pTime<a.interval:!0;k=!this.pCenter||F(this.pCenter,b.center)<a.posThreshold;this.pTime=b.timeStamp;this.pCenter=b.center;this.count=k&&c?
this.count+1:1;this._input=b;if(0===this.count%a.taps)return this.hasRequireFailures()?(this._timer=m(function(){this.state=8;this.tryEmit()},a.interval,this),2):8}return 32},failTimeout:function(){this._timer=m(function(){this.state=32},this.options.interval,this);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){8==this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});Q.VERSION="2.0.7";Q.defaults={domEvents:!1,touchAction:"compute",
enable:!0,inputTarget:null,inputClass:null,preset:[[ea,{enable:!1}],[ca,{enable:!1},["rotate"]],[fa,{direction:6}],[W,{direction:6},["swipe"]],[X],[X,{event:"doubletap",taps:2},["tap"]],[da]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};ha.prototype={set:function(b){R(this.options,b);b.touchAction&&this.touchAction.update();b.inputTarget&&(this.input.destroy(),this.input.target=b.inputTarget,this.input.init());
return this},stop:function(b){this.session.stopped=b?2:1},recognize:function(b){var a=this.session;if(!a.stopped){this.touchAction.preventDefaults(b);var c=this.recognizers,k=a.curRecognizer;if(!k||k&&k.state&8)k=a.curRecognizer=null;for(var f=0;f<c.length;){var e=c[f];2===a.stopped||k&&e!=k&&!e.canRecognizeWith(k)?e.reset():e.recognize(b);!k&&e.state&14&&(k=a.curRecognizer=e);f++}}},get:function(b){if(b instanceof P)return b;for(var a=this.recognizers,c=0;c<a.length;c++)if(a[c].options.event==b)return a[c];
return null},add:function(b){if(v(b,"add",this))return this;var a=this.get(b.options.event);a&&this.remove(a);this.recognizers.push(b);b.manager=this;this.touchAction.update();return b},remove:function(b){if(v(b,"remove",this))return this;if(b=this.get(b)){var a=this.recognizers;b=w(a,b);-1!==b&&(a.splice(b,1),this.touchAction.update())}return this},on:function(b,a){if(b!==n&&a!==n){var c=this.handlers;r(l(b),function(b){c[b]=c[b]||[];c[b].push(a)});return this}},off:function(b,a){if(b!==n){var c=
this.handlers;r(l(b),function(b){a?c[b]&&c[b].splice(w(c[b],a),1):delete c[b]});return this}},emit:function(b,a){this.options.domEvents&&Aa(b,a);var c=this.handlers[b]&&this.handlers[b].slice();if(c&&c.length)for(a.type=b,a.preventDefault=function(){a.srcEvent.preventDefault()},b=0;b<c.length;)c[b](a),b++},destroy:function(){this.element&&pa(this,!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};R(Q,{INPUT_START:1,INPUT_MOVE:2,INPUT_END:4,INPUT_CANCEL:8,STATE_POSSIBLE:1,
STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,DIRECTION_NONE:1,DIRECTION_LEFT:2,DIRECTION_RIGHT:4,DIRECTION_UP:8,DIRECTION_DOWN:16,DIRECTION_HORIZONTAL:6,DIRECTION_VERTICAL:24,DIRECTION_ALL:30,Manager:ha,Input:C,TouchAction:ba,TouchInput:z,MouseInput:q,PointerEventInput:N,TouchMouseInput:Z,SingleTouchInput:D,Recognizer:P,AttrRecognizer:M,Tap:X,Pan:W,Swipe:fa,Pinch:ca,Rotate:ea,Press:da,on:h,off:y,each:r,merge:Ca,extend:qa,assign:R,inherit:c,bindFn:a,
prefixed:k});("undefined"!==typeof g?g:"undefined"!==typeof self?self:{}).Hammer=Q;"function"===typeof define&&define.amd?define(function(){return Q}):"undefined"!=typeof x&&x.exports?x.exports=Q:g[B]=Q})(window,document,"Hammer")})()});require.register("marked/lib/marked.js",function(z,q,x){q=A(q,{},"marked");(function(){(function(g){function p(b){this.tokens=[];this.tokens.links={};this.options=b||y.defaults;this.rules=f.normal;this.options.gfm&&(this.rules=this.options.tables?f.tables:f.gfm)}function q(b,
a){this.options=a||y.defaults;this.links=b;this.rules=l.normal;this.renderer=this.options.renderer||new n;this.renderer.options=this.options;if(!this.links)throw Error("Tokens array requires a `links` property.");this.options.gfm?this.rules=this.options.breaks?l.breaks:l.gfm:this.options.pedantic&&(this.rules=l.pedantic)}function n(b){this.options=b||{}}function m(){}function v(b){this.tokens=[];this.token=null;this.options=b||y.defaults;this.options.renderer=this.options.renderer||new n;this.renderer=
this.options.renderer;this.renderer.options=this.options}function r(b,a){return b.replace(a?/&/g:/&(?!#?\w+;)/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,"\x26quot;").replace(/'/g,"\x26#39;")}function d(b){return b.replace(/&(#(?:\d+)|(?:#x[0-9A-Fa-f]+)|(?:\w+));?/ig,function(b,a){a=a.toLowerCase();return"colon"===a?":":"#"===a.charAt(0)?"x"===a.charAt(1)?String.fromCharCode(parseInt(a.substring(2),16)):String.fromCharCode(+a.substring(1)):""})}function c(b,a){b=b.source;
a=a||"";return{replace:function(a,c){c=c.source||c;c=c.replace(/(^|[^\[])\^/g,"$1");b=b.replace(a,c);return this},getRegex:function(){return new RegExp(b,a)}}}function a(b,a){w[" "+b]||(/^[^:]+:\/*[^/]*$/.test(b)?w[" "+b]=b+"/":w[" "+b]=b.replace(/[^/]*$/,""));b=w[" "+b];return"//"===a.slice(0,2)?b.replace(/:[\s\S]*/,":")+a:"/"===a.charAt(0)?b.replace(/(:\/*[^/]*)[\s\S]*/,"$1")+a:b+a}function u(){}function h(b){for(var a=1,c,f;a<arguments.length;a++)for(f in c=arguments[a],c)Object.prototype.hasOwnProperty.call(c,
f)&&(b[f]=c[f]);return b}function y(b,a,c){if("undefined"===typeof b||null===b)throw Error("marked(): input parameter is undefined or null");if("string"!==typeof b)throw Error("marked(): input parameter is of type "+Object.prototype.toString.call(b)+", string expected");if(c||"function"===typeof a){c||(c=a,a=null);a=h({},y.defaults,a||{});var k=a.highlight,f=0;try{var e=p.lex(b,a)}catch(L){return c(L)}var l=e.length;var d=function(b){if(b)return a.highlight=k,c(b);try{var f=v.parse(e,a)}catch(E){b=
E}a.highlight=k;return b?c(b):c(null,f)};if(!k||3>k.length)return d();delete a.highlight;if(!l)return d();for(;f<e.length;f++)(function(b){return"code"!==b.type?--l||d():k(b.text,b.lang,function(a,c){if(a)return d(a);if(null==c||c===b.text)return--l||d();b.text=c;b.escaped=!0;--l||d()})})(e[f])}else try{return a&&(a=h({},y.defaults,a)),v.parse(p.lex(b,a),a)}catch(L){L.message+="\nPlease report this to https://github.com/markedjs/marked.";if((a||y.defaults).silent)return"\x3cp\x3eAn error occurred:\x3c/p\x3e\x3cpre\x3e"+
r(L.message+"",!0)+"\x3c/pre\x3e";throw L;}}var f={newline:/^\n+/,code:/^( {4}[^\n]+\n*)+/,fences:u,hr:/^ {0,3}((?:- *){3,}|(?:_ *){3,}|(?:\* *){3,})(?:\n+|$)/,heading:/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n+|$)/,nptable:u,blockquote:/^( {0,3}> ?(paragraph|[^\n]*)(?:\n|$))+/,list:/^( *)(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,html:/^ *(?:comment *(?:\n|\s*$)|closed *(?:\n{2,}|\s*$)|closing *(?:\n{2,}|\s*$))/,def:/^ {0,3}\[(label)\]: *\n? *<?([^\s>]+)>?(?:(?: +\n? *| *\n *)(title))? *(?:\n+|$)/,
table:u,lheading:/^([^\n]+)\n *(=|-){2,} *(?:\n+|$)/,paragraph:/^([^\n]+(?:\n?(?!hr|heading|lheading| {0,3}>|tag)[^\n]+)+)/,text:/^[^\n]+/,_label:/(?:\\[\[\]]|[^\[\]])+/,_title:/(?:"(?:\\"|[^"]|"[^"\n]*")*"|'\n?(?:[^'\n]+\n?)*'|\([^()]*\))/};f.def=c(f.def).replace("label",f._label).replace("title",f._title).getRegex();f.bullet=/(?:[*+-]|\d+\.)/;f.item=/^( *)(bull) [^\n]*(?:\n(?!\1bull )[^\n]*)*/;f.item=c(f.item,"gm").replace(/bull/g,f.bullet).getRegex();f.list=c(f.list).replace(/bull/g,f.bullet).replace("hr",
"\\n+(?\x3d\\1?(?:(?:- *){3,}|(?:_ *){3,}|(?:\\* *){3,})(?:\\n+|$))").replace("def","\\n+(?\x3d"+f.def.source+")").getRegex();f._tag="(?!(?:a|em|strong|small|s|cite|q|dfn|abbr|data|time|code|var|samp|kbd|sub|sup|i|b|u|mark|ruby|rt|rp|bdi|bdo|span|br|wbr|ins|del|img)\\b)\\w+(?!:|[^\\w\\s@]*@)\\b";f.html=c(f.html).replace("comment",/\x3c!--[\s\S]*?--\x3e/).replace("closed",/<(tag)[\s\S]+?<\/\1>/).replace("closing",/<tag(?:"[^"]*"|'[^']*'|\s[^'"\/>\s]*)*?\/?>/).replace(/tag/g,f._tag).getRegex();f.paragraph=
c(f.paragraph).replace("hr",f.hr).replace("heading",f.heading).replace("lheading",f.lheading).replace("tag","\x3c"+f._tag).getRegex();f.blockquote=c(f.blockquote).replace("paragraph",f.paragraph).getRegex();f.normal=h({},f);f.gfm=h({},f.normal,{fences:/^ *(`{3,}|~{3,})[ \.]*(\S+)? *\n([\s\S]*?)\n? *\1 *(?:\n+|$)/,paragraph:/^/,heading:/^ *(#{1,6}) +([^\n]+?) *#* *(?:\n+|$)/});f.gfm.paragraph=c(f.paragraph).replace("(?!","(?!"+f.gfm.fences.source.replace("\\1","\\2")+"|"+f.list.source.replace("\\1",
"\\3")+"|").getRegex();f.tables=h({},f.gfm,{nptable:/^ *(\S.*\|.*)\n *([-:]+ *\|[-| :]*)\n((?:.*\|.*(?:\n|$))*)\n*/,table:/^ *\|(.+)\n *\|( *[-:]+[-| :]*)\n((?: *\|.*(?:\n|$))*)\n*/});p.rules=f;p.lex=function(b,a){return(new p(a)).lex(b)};p.prototype.lex=function(b){b=b.replace(/\r\n|\r/g,"\n").replace(/\t/g,"    ").replace(/\u00a0/g," ").replace(/\u2424/g,"\n");return this.token(b,!0)};p.prototype.token=function(b,a){b=b.replace(/^ +$/gm,"");for(var c,k,e,l,d,h,w;b;){if(e=this.rules.newline.exec(b))b=
b.substring(e[0].length),1<e[0].length&&this.tokens.push({type:"space"});if(e=this.rules.code.exec(b))b=b.substring(e[0].length),e=e[0].replace(/^ {4}/gm,""),this.tokens.push({type:"code",text:this.options.pedantic?e:e.replace(/\n+$/,"")});else if(e=this.rules.fences.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"code",lang:e[2],text:e[3]||""});else if(e=this.rules.heading.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"heading",depth:e[1].length,text:e[2]});else if(a&&(e=this.rules.nptable.exec(b))){b=
b.substring(e[0].length);d={type:"table",header:e[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:e[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:e[3].replace(/\n$/,"").split("\n")};for(h=0;h<d.align.length;h++)/^ *-+: *$/.test(d.align[h])?d.align[h]="right":/^ *:-+: *$/.test(d.align[h])?d.align[h]="center":/^ *:-+ *$/.test(d.align[h])?d.align[h]="left":d.align[h]=null;for(h=0;h<d.cells.length;h++)d.cells[h]=d.cells[h].split(/ *\| */);this.tokens.push(d)}else if(e=this.rules.hr.exec(b))b=
b.substring(e[0].length),this.tokens.push({type:"hr"});else if(e=this.rules.blockquote.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"blockquote_start"}),e=e[0].replace(/^ *> ?/gm,""),this.token(e,a),this.tokens.push({type:"blockquote_end"});else if(e=this.rules.list.exec(b)){b=b.substring(e[0].length);l=e[2];c=1<l.length;this.tokens.push({type:"list_start",ordered:c,start:c?+l:""});e=e[0].match(this.rules.item);c=!1;w=e.length;for(h=0;h<w;h++)d=e[h],k=d.length,d=d.replace(/^ *([*+-]|\d+\.) +/,
""),~d.indexOf("\n ")&&(k-=d.length,d=this.options.pedantic?d.replace(/^ {1,4}/gm,""):d.replace(new RegExp("^ {1,"+k+"}","gm"),"")),this.options.smartLists&&h!==w-1&&(k=f.bullet.exec(e[h+1])[0],l===k||1<l.length&&1<k.length||(b=e.slice(h+1).join("\n")+b,h=w-1)),k=c||/\n\n(?!\s*$)/.test(d),h!==w-1&&(c="\n"===d.charAt(d.length-1),k||(k=c)),this.tokens.push({type:k?"loose_item_start":"list_item_start"}),this.token(d,!1),this.tokens.push({type:"list_item_end"});this.tokens.push({type:"list_end"})}else if(e=
this.rules.html.exec(b))b=b.substring(e[0].length),this.tokens.push({type:this.options.sanitize?"paragraph":"html",pre:!this.options.sanitizer&&("pre"===e[1]||"script"===e[1]||"style"===e[1]),text:e[0]});else if(a&&(e=this.rules.def.exec(b)))b=b.substring(e[0].length),e[3]&&(e[3]=e[3].substring(1,e[3].length-1)),l=e[1].toLowerCase(),this.tokens.links[l]||(this.tokens.links[l]={href:e[2],title:e[3]});else if(a&&(e=this.rules.table.exec(b))){b=b.substring(e[0].length);d={type:"table",header:e[1].replace(/^ *| *\| *$/g,
"").split(/ *\| */),align:e[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:e[3].replace(/(?: *\| *)?\n$/,"").split("\n")};for(h=0;h<d.align.length;h++)/^ *-+: *$/.test(d.align[h])?d.align[h]="right":/^ *:-+: *$/.test(d.align[h])?d.align[h]="center":/^ *:-+ *$/.test(d.align[h])?d.align[h]="left":d.align[h]=null;for(h=0;h<d.cells.length;h++)d.cells[h]=d.cells[h].replace(/^ *\| *| *\| *$/g,"").split(/ *\| */);this.tokens.push(d)}else if(e=this.rules.lheading.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"heading",
depth:"\x3d"===e[2]?1:2,text:e[1]});else if(a&&(e=this.rules.paragraph.exec(b)))b=b.substring(e[0].length),this.tokens.push({type:"paragraph",text:"\n"===e[1].charAt(e[1].length-1)?e[1].slice(0,-1):e[1]});else if(e=this.rules.text.exec(b))b=b.substring(e[0].length),this.tokens.push({type:"text",text:e[0]});else if(b)throw Error("Infinite loop on byte: "+b.charCodeAt(0));}return this.tokens};var l={escape:/^\\([\\`*{}\[\]()#+\-.!_>])/,autolink:/^<(scheme:[^\s\x00-\x1f<>]*|email)>/,url:u,tag:/^\x3c!--[\s\S]*?--\x3e|^<\/?[a-zA-Z0-9\-]+(?:"[^"]*"|'[^']*'|\s[^<'">\/\s]*)*?\/?>/,
link:/^!?\[(inside)\]\(href\)/,reflink:/^!?\[(inside)\]\s*\[([^\]]*)\]/,nolink:/^!?\[((?:\[[^\[\]]*\]|\\[\[\]]|[^\[\]])*)\]/,strong:/^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,em:/^_([^\s_](?:[^_]|__)+?[^\s_])_\b|^\*((?:\*\*|[^*])+?)\*(?!\*)/,code:/^(`+)\s*([\s\S]*?[^`]?)\s*\1(?!`)/,br:/^ {2,}\n(?!\s*$)/,del:u,text:/^[\s\S]+?(?=[\\<!\[`*]|\b_| {2,}\n|$)/,_scheme:/[a-zA-Z][a-zA-Z0-9+.-]{1,31}/,_email:/[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+(@)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+(?![-_])/};
l.autolink=c(l.autolink).replace("scheme",l._scheme).replace("email",l._email).getRegex();l._inside=/(?:\[[^\[\]]*\]|\\[\[\]]|[^\[\]]|\](?=[^\[]*\]))*/;l._href=/\s*<?([\s\S]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*/;l.link=c(l.link).replace("inside",l._inside).replace("href",l._href).getRegex();l.reflink=c(l.reflink).replace("inside",l._inside).getRegex();l.normal=h({},l);l.pedantic=h({},l.normal,{strong:/^__(?=\S)([\s\S]*?\S)__(?!_)|^\*\*(?=\S)([\s\S]*?\S)\*\*(?!\*)/,em:/^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)/});
l.gfm=h({},l.normal,{escape:c(l.escape).replace("])","~|])").getRegex(),url:c(/^((?:ftp|https?):\/\/|www\.)(?:[a-zA-Z0-9\-]+\.?)+[^\s<]*|^email/).replace("email",l._email).getRegex(),_backpedal:/(?:[^?!.,:;*_~()&]+|\([^)]*\)|&(?![a-zA-Z0-9]+;$)|[?!.,:;*_~)]+(?!$))+/,del:/^~~(?=\S)([\s\S]*?\S)~~/,text:c(l.text).replace("]|","~]|").replace("|","|https?://|ftp://|www\\.|[a-zA-Z0-9.!#$%\x26'*+/\x3d?^_`{\\|}~-]+@|").getRegex()});l.breaks=h({},l.gfm,{br:c(l.br).replace("{2,}","*").getRegex(),text:c(l.gfm.text).replace("{2,}",
"*").getRegex()});q.rules=l;q.output=function(b,a,c){return(new q(a,c)).output(b)};q.prototype.output=function(b){for(var a="",c,e;b;)if(e=this.rules.escape.exec(b))b=b.substring(e[0].length),a+=e[1];else if(e=this.rules.autolink.exec(b))b=b.substring(e[0].length),"@"===e[2]?(c=r(this.mangle(e[1])),e="mailto:"+c):e=c=r(e[1]),a+=this.renderer.link(e,null,c);else if(!this.inLink&&(e=this.rules.url.exec(b)))e[0]=this.rules._backpedal.exec(e[0])[0],b=b.substring(e[0].length),"@"===e[2]?(c=r(e[0]),e="mailto:"+
c):(c=r(e[0]),e="www."===e[1]?"http://"+c:c),a+=this.renderer.link(e,null,c);else if(e=this.rules.tag.exec(b))!this.inLink&&/^<a /i.test(e[0])?this.inLink=!0:this.inLink&&/^<\/a>/i.test(e[0])&&(this.inLink=!1),b=b.substring(e[0].length),a+=this.options.sanitize?this.options.sanitizer?this.options.sanitizer(e[0]):r(e[0]):e[0];else if(e=this.rules.link.exec(b))b=b.substring(e[0].length),this.inLink=!0,a+=this.outputLink(e,{href:e[2],title:e[3]}),this.inLink=!1;else if((e=this.rules.reflink.exec(b))||
(e=this.rules.nolink.exec(b)))b=b.substring(e[0].length),c=(e[2]||e[1]).replace(/\s+/g," "),(c=this.links[c.toLowerCase()])&&c.href?(this.inLink=!0,a+=this.outputLink(e,c),this.inLink=!1):(a+=e[0].charAt(0),b=e[0].substring(1)+b);else if(e=this.rules.strong.exec(b))b=b.substring(e[0].length),a+=this.renderer.strong(this.output(e[2]||e[1]));else if(e=this.rules.em.exec(b))b=b.substring(e[0].length),a+=this.renderer.em(this.output(e[2]||e[1]));else if(e=this.rules.code.exec(b))b=b.substring(e[0].length),
a+=this.renderer.codespan(r(e[2].trim(),!0));else if(e=this.rules.br.exec(b))b=b.substring(e[0].length),a+=this.renderer.br();else if(e=this.rules.del.exec(b))b=b.substring(e[0].length),a+=this.renderer.del(this.output(e[1]));else if(e=this.rules.text.exec(b))b=b.substring(e[0].length),a+=this.renderer.text(r(this.smartypants(e[0])));else if(b)throw Error("Infinite loop on byte: "+b.charCodeAt(0));return a};q.prototype.outputLink=function(b,a){var c=r(a.href);a=a.title?r(a.title):null;return"!"!==
b[0].charAt(0)?this.renderer.link(c,a,this.output(b[1])):this.renderer.image(c,a,r(b[1]))};q.prototype.smartypants=function(b){return this.options.smartypants?b.replace(/---/g,"\u2014").replace(/--/g,"\u2013").replace(/(^|[-\u2014/(\[{"\s])'/g,"$1\u2018").replace(/'/g,"\u2019").replace(/(^|[-\u2014/(\[{\u2018\s])"/g,"$1\u201c").replace(/"/g,"\u201d").replace(/\.{3}/g,"\u2026"):b};q.prototype.mangle=function(b){if(!this.options.mangle)return b;for(var a="",c=b.length,e=0,f;e<c;e++)f=b.charCodeAt(e),
.5<Math.random()&&(f="x"+f.toString(16)),a+="\x26#"+f+";";return a};n.prototype.code=function(b,a,c){if(this.options.highlight){var e=this.options.highlight(b,a);null!=e&&e!==b&&(c=!0,b=e)}return a?'\x3cpre\x3e\x3ccode class\x3d"'+this.options.langPrefix+r(a,!0)+'"\x3e'+(c?b:r(b,!0))+"\n\x3c/code\x3e\x3c/pre\x3e\n":"\x3cpre\x3e\x3ccode\x3e"+(c?b:r(b,!0))+"\n\x3c/code\x3e\x3c/pre\x3e"};n.prototype.blockquote=function(b){return"\x3cblockquote\x3e\n"+b+"\x3c/blockquote\x3e\n"};n.prototype.html=function(b){return b};
n.prototype.heading=function(b,a,c){return"\x3ch"+a+' id\x3d"'+this.options.headerPrefix+c.toLowerCase().replace(/[^\w]+/g,"-")+'"\x3e'+b+"\x3c/h"+a+"\x3e\n"};n.prototype.hr=function(){return this.options.xhtml?"\x3chr/\x3e\n":"\x3chr\x3e\n"};n.prototype.list=function(b,a,c){var e=a?"ol":"ul";return"\x3c"+e+(a&&1!==c?' start\x3d"'+c+'"':"")+"\x3e\n"+b+"\x3c/"+e+"\x3e\n"};n.prototype.listitem=function(b){return"\x3cli\x3e"+b+"\x3c/li\x3e\n"};n.prototype.paragraph=function(b){return"\x3cp\x3e"+b+"\x3c/p\x3e\n"};
n.prototype.table=function(b,a){return"\x3ctable\x3e\n\x3cthead\x3e\n"+b+"\x3c/thead\x3e\n\x3ctbody\x3e\n"+a+"\x3c/tbody\x3e\n\x3c/table\x3e\n"};n.prototype.tablerow=function(b){return"\x3ctr\x3e\n"+b+"\x3c/tr\x3e\n"};n.prototype.tablecell=function(b,a){var c=a.header?"th":"td";return(a.align?"\x3c"+c+' style\x3d"text-align:'+a.align+'"\x3e':"\x3c"+c+"\x3e")+b+"\x3c/"+c+"\x3e\n"};n.prototype.strong=function(b){return"\x3cstrong\x3e"+b+"\x3c/strong\x3e"};n.prototype.em=function(b){return"\x3cem\x3e"+
b+"\x3c/em\x3e"};n.prototype.codespan=function(b){return"\x3ccode\x3e"+b+"\x3c/code\x3e"};n.prototype.br=function(){return this.options.xhtml?"\x3cbr/\x3e":"\x3cbr\x3e"};n.prototype.del=function(b){return"\x3cdel\x3e"+b+"\x3c/del\x3e"};n.prototype.link=function(b,c,f){if(this.options.sanitize){try{var k=decodeURIComponent(d(b)).replace(/[^\w:]/g,"").toLowerCase()}catch(I){return f}if(0===k.indexOf("javascript:")||0===k.indexOf("vbscript:")||0===k.indexOf("data:"))return f}this.options.baseUrl&&!e.test(b)&&
(b=a(this.options.baseUrl,b));b='\x3ca href\x3d"'+b+'"';c&&(b+=' title\x3d"'+c+'"');return b+("\x3e"+f+"\x3c/a\x3e")};n.prototype.image=function(b,c,f){this.options.baseUrl&&!e.test(b)&&(b=a(this.options.baseUrl,b));b='\x3cimg src\x3d"'+b+'" alt\x3d"'+f+'"';c&&(b+=' title\x3d"'+c+'"');return b+=this.options.xhtml?"/\x3e":"\x3e"};n.prototype.text=function(b){return b};m.prototype.strong=m.prototype.em=m.prototype.codespan=m.prototype.del=m.prototype.text=function(b){return b};m.prototype.link=m.prototype.image=
function(b,a,c){return""+c};m.prototype.br=function(){return""};v.parse=function(b,a){return(new v(a)).parse(b)};v.prototype.parse=function(b){this.inline=new q(b.links,this.options);this.inlineText=new q(b.links,h({},this.options,{renderer:new m}));this.tokens=b.reverse();for(b="";this.next();)b+=this.tok();return b};v.prototype.next=function(){return this.token=this.tokens.pop()};v.prototype.peek=function(){return this.tokens[this.tokens.length-1]||0};v.prototype.parseText=function(){for(var b=
this.token.text;"text"===this.peek().type;)b+="\n"+this.next().text;return this.inline.output(b)};v.prototype.tok=function(){switch(this.token.type){case "space":return"";case "hr":return this.renderer.hr();case "heading":return this.renderer.heading(this.inline.output(this.token.text),this.token.depth,d(this.inlineText.output(this.token.text)));case "code":return this.renderer.code(this.token.text,this.token.lang,this.token.escaped);case "table":var b="";var a="";var c,e;var f="";for(c=0;c<this.token.header.length;c++)f+=
this.renderer.tablecell(this.inline.output(this.token.header[c]),{header:!0,align:this.token.align[c]});b+=this.renderer.tablerow(f);for(c=0;c<this.token.cells.length;c++){var l=this.token.cells[c];f="";for(e=0;e<l.length;e++)f+=this.renderer.tablecell(this.inline.output(l[e]),{header:!1,align:this.token.align[e]});a+=this.renderer.tablerow(f)}return this.renderer.table(b,a);case "blockquote_start":for(a="";"blockquote_end"!==this.next().type;)a+=this.tok();return this.renderer.blockquote(a);case "list_start":a=
"";b=this.token.ordered;for(c=this.token.start;"list_end"!==this.next().type;)a+=this.tok();return this.renderer.list(a,b,c);case "list_item_start":for(a="";"list_item_end"!==this.next().type;)a+="text"===this.token.type?this.parseText():this.tok();return this.renderer.listitem(a);case "loose_item_start":for(a="";"list_item_end"!==this.next().type;)a+=this.tok();return this.renderer.listitem(a);case "html":return a=this.token.pre||this.options.pedantic?this.token.text:this.inline.output(this.token.text),
this.renderer.html(a);case "paragraph":return this.renderer.paragraph(this.inline.output(this.token.text));case "text":return this.renderer.paragraph(this.parseText())}};var w={},e=/^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;u.exec=u;y.options=y.setOptions=function(b){h(y.defaults,b);return y};y.defaults={gfm:!0,tables:!0,breaks:!1,pedantic:!1,sanitize:!1,sanitizer:null,mangle:!0,smartLists:!1,silent:!1,highlight:null,langPrefix:"lang-",smartypants:!1,headerPrefix:"",renderer:new n,xhtml:!1,baseUrl:null};y.Parser=
v;y.parser=v.parse;y.Renderer=n;y.TextRenderer=m;y.Lexer=p;y.lexer=p.lex;y.InlineLexer=q;y.inlineLexer=q.output;y.parse=y;"undefined"!==typeof x&&"object"===typeof z?x.exports=y:"function"===typeof define&&define.amd?define(function(){return y}):g.marked=y})(this||("undefined"!==typeof window?window:g))})()});require.register("prismjs/prism.js",function(z,q,x){q=A(q,{},"prismjs");(function(){var q="undefined"!==typeof window?window:"undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?
self:{},p=function(){var g=/\blang(?:uage)?-([\w-]+)\b/i,p=0,m=q.Prism={manual:q.Prism&&q.Prism.manual,disableWorkerMessageHandler:q.Prism&&q.Prism.disableWorkerMessageHandler,util:{encode:function(d){return d instanceof v?new v(d.type,m.util.encode(d.content),d.alias):"Array"===m.util.type(d)?d.map(m.util.encode):d.replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/\u00a0/g," ")},type:function(d){return Object.prototype.toString.call(d).match(/\[object (\w+)\]/)[1]},objId:function(d){d.__id||
Object.defineProperty(d,"__id",{value:++p});return d.__id},clone:function(d,c){var a=m.util.type(d);c=c||{};switch(a){case "Object":if(c[m.util.objId(d)])return c[m.util.objId(d)];var g={};c[m.util.objId(d)]=g;for(var h in d)d.hasOwnProperty(h)&&(g[h]=m.util.clone(d[h],c));return g;case "Array":if(c[m.util.objId(d)])return c[m.util.objId(d)];g=[];c[m.util.objId(d)]=g;d.forEach(function(a,f){g[f]=m.util.clone(a,c)});return g}return d}},languages:{extend:function(d,c){d=m.util.clone(m.languages[d]);
for(var a in c)d[a]=c[a];return d},insertBefore:function(d,c,a,g){g=g||m.languages;var h=g[d];if(2==arguments.length){a=arguments[1];for(var p in a)a.hasOwnProperty(p)&&(h[p]=a[p]);return h}var f={},l;for(l in h)if(h.hasOwnProperty(l)){if(l==c)for(p in a)a.hasOwnProperty(p)&&(f[p]=a[p]);f[l]=h[l]}m.languages.DFS(m.languages,function(a,c){c===g[d]&&a!=d&&(this[a]=f)});return g[d]=f},DFS:function(d,c,a,g){g=g||{};for(var h in d)d.hasOwnProperty(h)&&((c.call(d,h,d[h],a||h),"Object"!==m.util.type(d[h])||
g[m.util.objId(d[h])])?"Array"!==m.util.type(d[h])||g[m.util.objId(d[h])]||(g[m.util.objId(d[h])]=!0,m.languages.DFS(d[h],c,h,g)):(g[m.util.objId(d[h])]=!0,m.languages.DFS(d[h],c,null,g)))}},plugins:{},highlightAll:function(d,c){m.highlightAllUnder(document,d,c)},highlightAllUnder:function(d,c,a){a={callback:a,selector:'code[class*\x3d"language-"], [class*\x3d"language-"] code, code[class*\x3d"lang-"], [class*\x3d"lang-"] code'};m.hooks.run("before-highlightall",a);d=a.elements||d.querySelectorAll(a.selector);
for(var g=0,h;h=d[g++];)m.highlightElement(h,!0===c,a.callback)},highlightElement:function(d,c,a){for(var p,h,n=d;n&&!g.test(n.className);)n=n.parentNode;n&&(p=(n.className.match(g)||[,""])[1].toLowerCase(),h=m.languages[p]);d.className=d.className.replace(g,"").replace(/\s+/g," ")+" language-"+p;d.parentNode&&(n=d.parentNode,/pre/i.test(n.nodeName)&&(n.className=n.className.replace(g,"").replace(/\s+/g," ")+" language-"+p));var f={element:d,language:p,grammar:h,code:d.textContent};m.hooks.run("before-sanity-check",
f);f.code&&f.grammar?(m.hooks.run("before-highlight",f),c&&q.Worker?(d=new Worker(m.filename),d.onmessage=function(c){f.highlightedCode=c.data;m.hooks.run("before-insert",f);f.element.innerHTML=f.highlightedCode;a&&a.call(f.element);m.hooks.run("after-highlight",f);m.hooks.run("complete",f)},d.postMessage(JSON.stringify({language:f.language,code:f.code,immediateClose:!0}))):(f.highlightedCode=m.highlight(f.code,f.grammar,f.language),m.hooks.run("before-insert",f),f.element.innerHTML=f.highlightedCode,
a&&a.call(d),m.hooks.run("after-highlight",f),m.hooks.run("complete",f))):(f.code&&(m.hooks.run("before-highlight",f),f.element.textContent=f.code,m.hooks.run("after-highlight",f)),m.hooks.run("complete",f))},highlight:function(d,c,a){d={code:d,grammar:c,language:a};m.hooks.run("before-tokenize",d);d.tokens=m.tokenize(d.code,d.grammar);m.hooks.run("after-tokenize",d);return v.stringify(m.util.encode(d.tokens),d.language)},matchGrammar:function(d,c,a,g,h,p,f){var l=m.Token,w;for(w in a)if(a.hasOwnProperty(w)&&
a[w]){if(w==f)break;var e=a[w];e="Array"===m.util.type(e)?e:[e];for(var b=0;b<e.length;++b){var k=e[b],n=k.inside,C=!!k.lookbehind,u=!!k.greedy,q=0,G=k.alias;if(u&&!k.pattern.global){var r=k.pattern.toString().match(/[imuy]*$/)[0];k.pattern=RegExp(k.pattern.source,r+"g")}k=k.pattern||k;r=g;for(var y=h;r<c.length;y+=c[r].length,++r){var F=c[r];if(c.length>d.length)return;if(!(F instanceof l)){if(u&&r!=c.length-1){k.lastIndex=y;var E=k.exec(d);if(!E)break;var v=E.index+(C?E[1].length:0);var N=E.index+
E[0].length;var z=r;F=y;for(var B=c.length;z<B&&(F<N||!c[z].type&&!c[z-1].greedy);++z)F+=c[z].length,v>=F&&(++r,y=F);if(c[r]instanceof l)continue;z-=r;F=d.slice(y,F);E.index-=y}else k.lastIndex=0,E=k.exec(F),z=1;E&&(C&&(q=E[1]?E[1].length:0),v=E.index+q,E=E[0].slice(q),N=v+E.length,v=F.slice(0,v),N=F.slice(N),F=[r,z],v&&(++r,y+=v.length,F.push(v)),E=new l(w,n?m.tokenize(E,n):E,G,E,u),F.push(E),N&&F.push(N),Array.prototype.splice.apply(c,F),1!=z&&m.matchGrammar(d,c,a,r,y,!0,w));if(p)break}}}}},tokenize:function(d,
c,a){a=[d];var g=c.rest;if(g){for(var h in g)c[h]=g[h];delete c.rest}m.matchGrammar(d,a,c,0,0,!1);return a},hooks:{all:{},add:function(d,c){var a=m.hooks.all;a[d]=a[d]||[];a[d].push(c)},run:function(d,c){if((d=m.hooks.all[d])&&d.length)for(var a=0,g;g=d[a++];)g(c)}}},v=m.Token=function(d,c,a,g,h){this.type=d;this.content=c;this.alias=a;this.length=(g||"").length|0;this.greedy=!!h};v.stringify=function(d,c,a){if("string"==typeof d)return d;if("Array"===m.util.type(d))return d.map(function(a){return v.stringify(a,
c,d)}).join("");var g={type:d.type,content:v.stringify(d.content,c,a),tag:"span",classes:["token",d.type],attributes:{},language:c,parent:a};d.alias&&(a="Array"===m.util.type(d.alias)?d.alias:[d.alias],Array.prototype.push.apply(g.classes,a));m.hooks.run("wrap",g);a=Object.keys(g.attributes).map(function(a){return a+'\x3d"'+(g.attributes[a]||"").replace(/"/g,"\x26quot;")+'"'}).join(" ");return"\x3c"+g.tag+' class\x3d"'+g.classes.join(" ")+'"'+(a?" "+a:"")+"\x3e"+g.content+"\x3c/"+g.tag+"\x3e"};if(!q.document){if(!q.addEventListener)return q.Prism;
m.disableWorkerMessageHandler||q.addEventListener("message",function(d){d=JSON.parse(d.data);var c=d.language,a=d.immediateClose;q.postMessage(m.highlight(d.code,m.languages[c],c));a&&q.close()},!1);return q.Prism}var r=document.currentScript||[].slice.call(document.getElementsByTagName("script")).pop();r&&(m.filename=r.src,m.manual||r.hasAttribute("data-manual")||("loading"!==document.readyState?window.requestAnimationFrame?window.requestAnimationFrame(m.highlightAll):window.setTimeout(m.highlightAll,
16):document.addEventListener("DOMContentLoaded",m.highlightAll)));return q.Prism}();"undefined"!==typeof x&&x.exports&&(x.exports=p);"undefined"!==typeof g&&(g.Prism=p);p.languages.markup={comment:/\x3c!--[\s\S]*?--\x3e/,prolog:/<\?[\s\S]+?\?>/,doctype:/<!DOCTYPE[\s\S]+?>/i,cdata:/<!\[CDATA\[[\s\S]*?]]\x3e/i,tag:{pattern:/<\/?(?!\d)[^\s>\/=$<%]+(?:\s+[^\s>\/=]+(?:=(?:("|')(?:\\[\s\S]|(?!\1)[^\\])*\1|[^\s'">=]+))?)*\s*\/?>/i,greedy:!0,inside:{tag:{pattern:/^<\/?[^\s>\/]+/i,inside:{punctuation:/^<\/?/,
namespace:/^[^\s>\/:]+:/}},"attr-value":{pattern:/=(?:("|')(?:\\[\s\S]|(?!\1)[^\\])*\1|[^\s'">=]+)/i,inside:{punctuation:[/^=/,{pattern:/(^|[^\\])["']/,lookbehind:!0}]}},punctuation:/\/?>/,"attr-name":{pattern:/[^\s>\/]+/,inside:{namespace:/^[^\s>\/:]+:/}}}},entity:/&#?[\da-z]{1,8};/i};p.languages.markup.tag.inside["attr-value"].inside.entity=p.languages.markup.entity;p.hooks.add("wrap",function(g){"entity"===g.type&&(g.attributes.title=g.content.replace(/&amp;/,"\x26"))});p.languages.xml=p.languages.markup;
p.languages.html=p.languages.markup;p.languages.mathml=p.languages.markup;p.languages.svg=p.languages.markup;p.languages.css={comment:/\/\*[\s\S]*?\*\//,atrule:{pattern:/@[\w-]+?.*?(?:;|(?=\s*\{))/i,inside:{rule:/@[\w-]+/}},url:/url\((?:(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1|.*?)\)/i,selector:/[^{}\s][^{};]*?(?=\s*\{)/,string:{pattern:/("|')(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},property:/[-_a-z\xA0-\uFFFF][-\w\xA0-\uFFFF]*(?=\s*:)/i,important:/\B!important\b/i,"function":/[-a-z0-9]+(?=\()/i,
punctuation:/[(){};:]/};p.languages.css.atrule.inside.rest=p.languages.css;p.languages.markup&&(p.languages.insertBefore("markup","tag",{style:{pattern:/(<style[\s\S]*?>)[\s\S]*?(?=<\/style>)/i,lookbehind:!0,inside:p.languages.css,alias:"language-css",greedy:!0}}),p.languages.insertBefore("inside","attr-value",{"style-attr":{pattern:/\s*style=("|')(?:\\[\s\S]|(?!\1)[^\\])*\1/i,inside:{"attr-name":{pattern:/^\s*style/i,inside:p.languages.markup.tag.inside},punctuation:/^\s*=\s*['"]|['"]\s*$/,"attr-value":{pattern:/.+/i,
inside:p.languages.css}},alias:"language-css"}},p.languages.markup.tag));p.languages.clike={comment:[{pattern:/(^|[^\\])\/\*[\s\S]*?(?:\*\/|$)/,lookbehind:!0},{pattern:/(^|[^\\:])\/\/.*/,lookbehind:!0,greedy:!0}],string:{pattern:/(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},"class-name":{pattern:/((?:\b(?:class|interface|extends|implements|trait|instanceof|new)\s+)|(?:catch\s+\())[\w.\\]+/i,lookbehind:!0,inside:{punctuation:/[.\\]/}},keyword:/\b(?:if|else|while|do|for|return|in|instanceof|function|new|try|throw|catch|finally|null|break|continue)\b/,
"boolean":/\b(?:true|false)\b/,"function":/[a-z0-9_]+(?=\()/i,number:/\b0x[\da-f]+\b|(?:\b\d+\.?\d*|\B\.\d+)(?:e[+-]?\d+)?/i,operator:/--?|\+\+?|!=?=?|<=?|>=?|==?=?|&&?|\|\|?|\?|\*|\/|~|\^|%/,punctuation:/[{}[\];(),.:]/};p.languages.javascript=p.languages.extend("clike",{keyword:/\b(?:as|async|await|break|case|catch|class|const|continue|debugger|default|delete|do|else|enum|export|extends|finally|for|from|function|get|if|implements|import|in|instanceof|interface|let|new|null|of|package|private|protected|public|return|set|static|super|switch|this|throw|try|typeof|var|void|while|with|yield)\b/,
number:/\b(?:0[xX][\dA-Fa-f]+|0[bB][01]+|0[oO][0-7]+|NaN|Infinity)\b|(?:\b\d+\.?\d*|\B\.\d+)(?:[Ee][+-]?\d+)?/,"function":/[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*(?=\s*\()/i,operator:/-[-=]?|\+[+=]?|!=?=?|<<?=?|>>?>?=?|=(?:==?|>)?|&[&=]?|\|[|=]?|\*\*?=?|\/=?|~|\^=?|%=?|\?|\.{3}/});p.languages.insertBefore("javascript","keyword",{regex:{pattern:/((?:^|[^$\w\xA0-\uFFFF."'\])\s])\s*)\/(\[[^\]\r\n]+]|\\.|[^/\\\[\r\n])+\/[gimyu]{0,5}(?=\s*($|[\r\n,.;})]))/,lookbehind:!0,greedy:!0},"function-variable":{pattern:/[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*(?=\s*=\s*(?:function\b|(?:\([^()]*\)|[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*)\s*=>))/i,
alias:"function"},constant:/\b[A-Z][A-Z\d_]*\b/});p.languages.insertBefore("javascript","string",{"template-string":{pattern:/`(?:\\[\s\S]|[^\\`])*`/,greedy:!0,inside:{interpolation:{pattern:/\$\{[^}]+\}/,inside:{"interpolation-punctuation":{pattern:/^\$\{|\}$/,alias:"punctuation"},rest:p.languages.javascript}},string:/[\s\S]+/}}});p.languages.markup&&p.languages.insertBefore("markup","tag",{script:{pattern:/(<script[\s\S]*?>)[\s\S]*?(?=<\/script>)/i,lookbehind:!0,inside:p.languages.javascript,alias:"language-javascript",
greedy:!0}});p.languages.js=p.languages.javascript;(function(){"undefined"!==typeof self&&self.Prism&&self.document&&document.querySelector&&(self.Prism.fileHighlight=function(){var g={js:"javascript",py:"python",rb:"ruby",ps1:"powershell",psm1:"powershell",sh:"bash",bat:"batch",h:"c",tex:"latex"};Array.prototype.slice.call(document.querySelectorAll("pre[data-src]")).forEach(function(n){for(var m=n.getAttribute("data-src"),q,r=n,d=/\blang(?:uage)?-(?!\*)([\w-]+)\b/i;r&&!d.test(r.className);)r=r.parentNode;
r&&(q=(n.className.match(d)||[,""])[1]);q||(q=(m.match(/\.(\w+)$/)||[,""])[1],q=g[q]||q);var c=document.createElement("code");c.className="language-"+q;n.textContent="";c.textContent="Loading\u2026";n.appendChild(c);var a=new XMLHttpRequest;a.open("GET",m,!0);a.onreadystatechange=function(){4==a.readyState&&(400>a.status&&a.responseText?(c.textContent=a.responseText,p.highlightElement(c)):c.textContent=400<=a.status?"\u2716 Error "+a.status+" while fetching file: "+a.statusText:"\u2716 Error: File does not exist or is empty")};
n.hasAttribute("data-download-link")&&p.plugins.toolbar&&p.plugins.toolbar.registerButton("download-file",function(){var a=document.createElement("a");a.textContent=n.getAttribute("data-download-link-label")||"Download";a.setAttribute("download","");a.href=m;return a});a.send(null)})},document.addEventListener("DOMContentLoaded",self.Prism.fileHighlight))})()})()});require.register("components/main.component.svelte",function(g,q,x){function z(f,l){var d,e,b,k,h,g,m,p,n,q,r=new a({root:f.root});r.on("mobilemenu",
function(b){f.handleMobileMenu(b)});r.on("fontsize",function(b){f.handleFontSize(b)});f.refs.topbar=r;var y=new c({root:f.root});y.on("mobilemenu",function(b){f.handleMobileMenu(b)});f.refs.menu=y;return{c:function(){d=document.createElement("div");r._fragment.c();e=document.createTextNode("\n  ");y._fragment.c();b=document.createTextNode("\n  ");k=document.createElement("div");h=document.createElement("div");h.innerHTML="Disclaimer:\x3cbr\x3eThis documentation is a work in progress. It isn't ready and shouldn't be shared with outsiders until the removal of this message. If you want to help build it, please \x3ca href\x3d\"https://github.com/peercoin/docs#peercoin-official-documentation-repository\"\x3eclick here\x3c/a\x3e.";
g=document.createTextNode("\n    ");m=document.createElement("div");p=document.createTextNode("\n    ");n=document.createElement("div");this.h()},h:function(){h.className="warn";m.className="menu-swipper";n.className=q="doc-container font-"+l.fontSize;k.className="body";d.className="MainComp"},m:function(a,c){a.insertBefore(d,c);r._mount(d,null);d.appendChild(e);y._mount(d,null);d.appendChild(b);d.appendChild(k);k.appendChild(h);k.appendChild(g);k.appendChild(m);k.appendChild(p);k.appendChild(n);
n.innerHTML=l.documentationHTML;f.refs.docContainer=n},p:function(b,a){b.documentationHTML&&(n.innerHTML=a.documentationHTML);b.fontSize&&q!==(q="doc-container font-"+a.fontSize)&&(n.className=q)},u:function(){n.innerHTML="";d.parentNode.removeChild(d)},d:function(){r.destroy(!1);f.refs.topbar===r&&(f.refs.topbar=null);y.destroy(!1);f.refs.menu===y&&(f.refs.menu=null);f.refs.docContainer===n&&(f.refs.docContainer=null)}}}function p(a){B(this,a);this.refs={};this._state=n({fontSize:2,documentation:"",
documentationHTML:""},a.data);var c=this;a.root||(this._oncreate=[],this._beforecreate=[],this._aftercreate=[]);this._fragment=z(this,this._state);this.root._oncreate.push(function(){c.registerDocumentation();c.fire("update",{changed:{fontSize:1,documentationHTML:1},current:c._state})});a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),this._lock=!0,m(this._beforecreate),m(this._oncreate),m(this._aftercreate),this._lock=!1)}function B(a,c){a._handlers=Object.create(null);a._bind=c._bind;
a.options=c;a.root=c.root||a;a.store=a.root.store||c.store}function n(a,c){for(var f in c)a[f]=c[f];return a}function m(a){for(;a&&a.length;)a.shift()()}function v(a){this.destroy=r;this.fire("destroy");this.set=this.get=r;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function r(){}var d=q("../herodotus-settings.js"),c=q("./menu.component"),a=q("./topbar.component"),u=q("marked"),h=q("@fdaciuk/ajax");q("hammerjs");var y=q("prismjs");d=d&&d.__esModule?d["default"]:d;
c=c&&c.__esModule?c["default"]:c;a=a&&a.__esModule?a["default"]:a;u=u&&u.__esModule?u["default"]:u;h=h&&h.__esModule?h["default"]:h;y=y&&y.__esModule?y["default"]:y;n(p.prototype,{destroy:v,get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var f=0;f<a.length;f+=1){var e=a[f];e.__calling||(e.__calling=!0,e.call(this,c),e.__calling=!1)}},observe:function(a,c,d){var e=c.bind(this);d&&!1===d.init||e(this.get()[a],void 0);return this.on(d&&
d.defer?"update":"state",function(b){b.changed[a]&&e(b.current[a],b.previous&&b.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var f=this._handlers[a]||(this._handlers[a]=[]);f.push(c);return{cancel:function(){var a=f.indexOf(c);~a&&f.splice(a,1)}}},set:function(a){this._set(n({},a));this.root._lock||(this.root._lock=!0,m(this.root._beforecreate),m(this.root._oncreate),m(this.root._aftercreate),this.root._lock=!1)},teardown:v,_set:function(a){var c=this._state,f={},
e=!1,b;for(b in a)this._differs(a[b],c[b])&&(f[b]=e=!0);e&&(this._state=n(n({},c),a),this._recompute(f,this._state),this._bind&&this._bind(f,this._state),this._fragment&&(this.fire("state",{changed:f,current:this._state,previous:c}),this._fragment.p(f,this._state),this.fire("update",{changed:f,current:this._state,previous:c})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:
a!==c||a&&"object"===typeof a||"function"===typeof a}});n(p.prototype,{getParentId:function(a){return"end"===a?null:a.id&&-1<["H1","H2"].indexOf(a.tagName)?{id:a.id,title:a.textContent}:this.getParentId(a.previousElementSibling||"end")},generateSearchList:function(){var a=this,c=[];[].concat($jscomp.arrayFromIterable(document.querySelector(".doc-container").children)).forEach(function(d){var e=a.getParentId(d);e&&c.push({id:e.id,title:e.title,content:d.textContent})});return c},handleFontSize:function(a){switch(a.action){case "INCREASE":this.increaseFont();
break;case "DECREASE":this.decreaseFont()}},handleMobileMenu:function(a){switch(a.action){case "TOGGLE":this.refs.topbar.set({isMenuOpen:this.refs.menu.toggle()});break;case "CLOSE":this.refs.menu.close();this.refs.topbar.set({isMenuOpen:!1});break;case "OPEN":this.refs.menu.open(),this.refs.topbar.set({isMenuOpen:!0})}},increaseFont:function(){var a=this.get("fontSize");4<=a||this.set({fontSize:a+1})},decreaseFont:function(){var a=this.get("fontSize");1>=a||this.set({fontSize:a-1})},registerDocumentation:function(){var a=
this;var c=d.allow_remote_documentation?d.remote_documentation_url:"documentation.md";h().get(c).then(function(c,e){a.set({documentation:c,documentationHTML:u(c)});a.refs.menu.startMenu(a.generateMenu());a.refs.topbar.refs.searchlist.set({searchList:a.generateSearchList()});a.responsiveTables();y.highlightAll()})},responsiveTables:function(){Array.from(document.querySelectorAll(".doc-container table")).forEach(function(a){var c=document.createElement("div");c.classList.add("responsive-table");a.parentElement.insertBefore(c,
a);c.appendChild(a)})},generateMenu:function(){var a=[],c=[],d;this.refs.docContainer.querySelectorAll("h1, h2").forEach(function(e){c.push({type:e.nodeName.toLowerCase(),label:e.textContent,id:e.id});"h1"===e.nodeName.toLowerCase()?(a.push({type:e.nodeName.toLowerCase(),label:e.textContent,id:e.id}),d=a[a.length-1],d.children=[]):"h2"===e.nodeName.toLowerCase()&&d.children.push({type:e.nodeName.toLowerCase(),label:e.textContent,id:e.id})});return{menuItems:a,menuItemsFlat:c}}});p.prototype._recompute=
r;x.exports=p});require.register("components/menu.component.svelte",function(g,q,x){function z(a,b){(new w(a)).on("swipeleft",b)}function p(){var a=this;window.onhashchange=function(){a.scrollToURLMenu()}}function B(c,b){function e(b){c.onAppScroll(this.scrollY)}function d(b){c.fire("mobilemenu",{action:"CLOSE"})}var f,h,l,g,m,p,w,q,r,y;window.addEventListener("scroll",e);for(var v=b.menuItems,x=[],B=0;B<v.length;B+=1)x[B]=n(c,a(a({},b),{each_value:v,item:v[B],item_index:B}));return{c:function(){f=
document.createElement("div");h=document.createElement("div");g=document.createTextNode("\n  ");m=document.createElement("div");p=document.createElement("img");w=document.createTextNode("\n    ");q=document.createElement("ul");for(var b=0;b<x.length;b+=1)x[b].c();this.h()},h:function(){h.addEventListener("click",d,!1);h.className=l="MenuComp--overlay "+(b.isOpen?"active":"");p.src="img/logo-green.svg";p.alt="Peercoin Docs";p.className="logo";q.className="menu";r=z.call(c,m,function(b){c.fire("mobilemenu",
{action:"CLOSE"})});m.className=y="MenuComp "+(b.isOpen?"open":"")},m:function(b,a){b.insertBefore(f,a);f.appendChild(h);c.refs.overlay=h;f.appendChild(g);f.appendChild(m);m.appendChild(p);m.appendChild(w);m.appendChild(q);for(b=0;b<x.length;b+=1)x[b].m(q,null);c.refs.menu=m},p:function(b,e){b.isOpen&&l!==(l="MenuComp--overlay "+(e.isOpen?"active":""))&&(h.className=l);var d=e.menuItems;if(b.menuItems){for(var k=0;k<d.length;k+=1){var f=a(a({},e),{each_value:d,item:d[k],item_index:k});x[k]?x[k].p(b,
f):(x[k]=n(c,f),x[k].c(),x[k].m(q,null))}for(;k<x.length;k+=1)x[k].u(),x[k].d();x.length=d.length}b.isOpen&&y!==(y="MenuComp "+(e.isOpen?"open":""))&&(m.className=y)},u:function(){f.parentNode.removeChild(f);for(var b=0;b<x.length;b+=1)x[b].u()},d:function(){window.removeEventListener("scroll",e);h.removeEventListener("click",d,!1);c.refs.overlay===h&&(c.refs.overlay=null);u(x);r[r.destroy?"destroy":"teardown"]();c.refs.menu===m&&(c.refs.menu=null)}}}function n(a,b){var c=b.item,e,d,f=c.label,h,l,
g,m,p,n=0<c.children.length&&v(a,b);return{c:function(){e=document.createElement("li");d=document.createElement("a");h=document.createTextNode(f);g=document.createTextNode("\n            ");n&&n.c();this.h()},h:function(){d.addEventListener("click",r,!1);d.href=l="#"+c.id;d._svelte={component:a,each_value:b.each_value,item_index:b.item_index};e.id=m="menu-"+c.id;e.className=p=c.type},m:function(b,a){b.insertBefore(e,a);e.appendChild(d);d.appendChild(h);e.appendChild(g);n&&n.m(e,null)},p:function(b,
k){c=k.item;b.menuItems&&f!==(f=c.label)&&(h.data=f);b.menuItems&&l!==(l="#"+c.id)&&(d.href=l);d._svelte.each_value=k.each_value;d._svelte.item_index=k.item_index;0<c.children.length?n?n.p(b,k):(n=v(a,k),n.c(),n.m(e,null)):n&&(n.u(),n.d(),n=null);b.menuItems&&m!==(m="menu-"+c.id)&&(e.id=m);b.menuItems&&p!==(p=c.type)&&(e.className=p)},u:function(){e.parentNode.removeChild(e);n&&n.u()},d:function(){d.removeEventListener("click",r,!1);n&&n.d()}}}function m(a,b){var c=b.subitem,e,f,h=c.label,l,g,m,n;
return{c:function(){e=document.createElement("li");f=document.createElement("a");l=document.createTextNode(h);this.h()},h:function(){f.addEventListener("click",d,!1);f.href=g="#"+c.id;f._svelte={component:a,each_value_1:b.each_value_1,subitem_index:b.subitem_index};e.id=m="menu-"+c.id;e.className=n=c.type},m:function(b,a){b.insertBefore(e,a);e.appendChild(f);f.appendChild(l)},p:function(b,a){c=a.subitem;b.menuItems&&h!==(h=c.label)&&(l.data=h);b.menuItems&&g!==(g="#"+c.id)&&(f.href=g);f._svelte.each_value_1=
a.each_value_1;f._svelte.subitem_index=a.subitem_index;b.menuItems&&m!==(m="menu-"+c.id)&&(e.id=m);b.menuItems&&n!==(n=c.type)&&(e.className=n)},u:function(){e.parentNode.removeChild(e)},d:function(){f.removeEventListener("click",d,!1)}}}function v(c,b){for(var e=b.item,d,f=e.children,h=[],l=0;l<f.length;l+=1)h[l]=m(c,a(a({},b),{each_value_1:f,subitem:f[l],subitem_index:l}));return{c:function(){d=document.createElement("ul");for(var b=0;b<h.length;b+=1)h[b].c();this.h()},h:function(){d.className=
"subsection"},m:function(b,a){b.insertBefore(d,a);for(b=0;b<h.length;b+=1)h[b].m(d,null)},p:function(b,f){e=f.item;var k=e.children;if(b.menuItems){for(var l=0;l<k.length;l+=1){var g=a(a({},f),{each_value_1:k,subitem:k[l],subitem_index:l});h[l]?h[l].p(b,g):(h[l]=m(c,g),h[l].c(),h[l].m(d,null))}for(;l<h.length;l+=1)h[l].u(),h[l].d();h.length=k.length}},u:function(){d.parentNode.removeChild(d);for(var b=0;b<h.length;b+=1)h[b].u()},d:function(){u(h)}}}function r(a){this._svelte.component.scrollToItem(this._svelte.each_value[this._svelte.item_index],
a)}function d(a){this._svelte.component.scrollToItem(this._svelte.each_value_1[this._svelte.subitem_index],a)}function c(c){h(this,c);this.refs={};this._state=a({menuItems:[],menuItemsFlat:[],isOpen:!1,prevY:0},c.data);var b=this;c.root||(this._oncreate=[]);this._fragment=B(this,this._state);this.root._oncreate.push(function(){p.call(b);b.fire("update",{changed:{isOpen:1,menuItems:1},current:b._state})});c.target&&(this._fragment.c(),this._mount(c.target,c.anchor),y(this._oncreate))}function a(a,
b){for(var c in b)a[c]=b[c];return a}function u(a){for(var b=0;b<a.length;b+=1)a[b]&&a[b].d()}function h(a,b){a._handlers=Object.create(null);a._bind=b._bind;a.options=b;a.root=b.root||a;a.store=a.root.store||b.store}function y(a){for(;a&&a.length;)a.shift()()}function f(a){this.destroy=l;this.fire("destroy");this.set=this.get=l;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function l(){}var w=q("hammerjs");w=w&&w.__esModule?w["default"]:w;a(c.prototype,{destroy:f,
get:function(a){return a?this._state[a]:this._state},fire:function(a,b){if(a=a in this._handlers&&this._handlers[a].slice())for(var c=0;c<a.length;c+=1){var e=a[c];e.__calling||(e.__calling=!0,e.call(this,b),e.__calling=!1)}},observe:function(a,b,c){var e=b.bind(this);c&&!1===c.init||e(this.get()[a],void 0);return this.on(c&&c.defer?"update":"state",function(b){b.changed[a]&&e(b.current[a],b.previous&&b.previous[a])})},on:function(a,b){if("teardown"===a)return this.on("destroy",b);var c=this._handlers[a]||
(this._handlers[a]=[]);c.push(b);return{cancel:function(){var a=c.indexOf(b);~a&&c.splice(a,1)}}},set:function(c){this._set(a({},c));this.root._lock||(this.root._lock=!0,y(this.root._beforecreate),y(this.root._oncreate),y(this.root._aftercreate),this.root._lock=!1)},teardown:f,_set:function(c){var b=this._state,e={},d=!1,f;for(f in c)this._differs(c[f],b[f])&&(e[f]=d=!0);d&&(this._state=a(a({},b),c),this._recompute(e,this._state),this._bind&&this._bind(e,this._state),this._fragment&&(this.fire("state",
{changed:e,current:this._state,previous:b}),this._fragment.p(e,this._state),this.fire("update",{changed:e,current:this._state,previous:b})))},_mount:function(a,b){this._fragment[this._fragment.i?"i":"m"](a,b||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,b){return a!=a?b==b:a!==b||a&&"object"===typeof a||"function"===typeof a}});a(c.prototype,{onAppScroll:function(a){a=this.get("menuItemsFlat");a=$jscomp.makeIterator(a.entries());for(var b=a.next();!b.done;b=a.next()){b=
$jscomp.makeIterator(b.value);b.next();b=b.next().value;var c=document.getElementById(b.id),e=c.getBoundingClientRect().top;c=c.getBoundingClientRect().bottom;if(0<=e&&c<=window.innerHeight){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu li.active"))).map(function(a){return a.classList.remove("active")});a=document.getElementById("menu-"+b.id);a.classList.add("active");b=a.parentNode;b.classList.contains("subsection")&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),
b.classList.add("show"));0<a.querySelectorAll(".subsection").length&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),a.querySelector(".subsection").classList.add("show"));break}}},startMenu:function(a){var b=this;this.set(a);setTimeout(function(){b.scrollToURLMenu()},10)},scrollTop:function(){window.scrollTo(0,0);this.close()},scrollToURLMenu:function(){var a=window.location.hash.substr(2),b=this.get("menuItemsFlat").filter(function(b){return b.id===
a});0<b.length?(b=document.getElementById(b[0].id),b=window.scrollY+b.getBoundingClientRect().top-70,window.scrollTo(0,b)):window.scrollTo(0,1)},toggle:function(){this.set({isOpen:!this.refs.menu.isOpen});return this.refs.menu.isOpen},close:function(){this.set({isOpen:!1})},open:function(){this.set({isOpen:!0})},scrollToItem:function(a,b){b&&b.preventDefault();window.location.hash="/"+a.id;this.get("menuItemsFlat");a=window.scrollY+document.getElementById(a.id).getBoundingClientRect().top-70;window.scrollTo(0,
a);this.fire("mobilemenu",{action:"CLOSE"})}});c.prototype._recompute=l;x.exports=c});require.register("components/searchlist.component.svelte",function(g,q,x){function z(){var a=this;this.observe("searchList",function(c){a.fuse=a.setFuse(c)})}function p(a,c){function e(b){a.toggleSearch()}function b(b){a.closeSearch()}function f(b){a.handleSearch(b)}function h(b){a.isClosable(b)}var l,g,p,w,q,r,y,u,v,x,z,B,A,D=1<c.filteredList.length&&n(a,c),J=1>c.filteredList.length&&m(a,c);return{c:function(){l=
document.createElement("div");g=document.createElement("div");p=d("svg");w=d("use");q=document.createTextNode("\n  \n  ");r=document.createElement("div");u=document.createTextNode("\n\n  ");v=document.createElement("div");x=document.createElement("input");z=document.createTextNode("\n    ");D&&D.c();B=document.createTextNode("\n\n    ");J&&J.c();this.h()},h:function(){w.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-search.svg#icon");w.setAttribute("preserveAspectRatio","xMidYMid");
p.addEventListener("click",e,!1);p.setAttribute("class","svg-icon");p.setAttribute("xmlns","http://www.w3.org/2000/svg");p.setAttribute("role","img");p.setAttribute("viewBox","0 0 15 15");g.className="btn btn-svg";r.addEventListener("click",b,!1);r.className=y="SearchListComp--overlay "+(c.isOpen?"active":"");x.addEventListener("input",f,!1);x.addEventListener("keydown",h,!1);x.setAttribute("type","text");x.className="filter-input";x.placeholder="Search here...";v.className=A="search-popup "+(c.isOpen?
"open":"");l.className="SearchListComp"},m:function(b,c){b.insertBefore(l,c);l.appendChild(g);g.appendChild(p);p.appendChild(w);l.appendChild(q);l.appendChild(r);l.appendChild(u);l.appendChild(v);v.appendChild(x);a.refs.input=x;v.appendChild(z);D&&D.m(v,null);v.appendChild(B);J&&J.m(v,null)},p:function(b,c){b.isOpen&&y!==(y="SearchListComp--overlay "+(c.isOpen?"active":""))&&(r.className=y);1<c.filteredList.length?D?D.p(b,c):(D=n(a,c),D.c(),D.m(v,B)):D&&(D.u(),D.d(),D=null);1>c.filteredList.length?
J||(J=m(a,c),J.c(),J.m(v,null)):J&&(J.u(),J.d(),J=null);b.isOpen&&A!==(A="search-popup "+(c.isOpen?"open":""))&&(v.className=A)},u:function(){l.parentNode.removeChild(l);D&&D.u();J&&J.u()},d:function(){p.removeEventListener("click",e,!1);r.removeEventListener("click",b,!1);x.removeEventListener("input",f,!1);x.removeEventListener("keydown",h,!1);a.refs.input===x&&(a.refs.input=null);D&&D.d();J&&J.d()}}}function B(a,c){var e=c.item,b,d,f,h=e.item.title,l,g,m,p=e.item.content.substr(0,100),n,w,q;return{c:function(){b=
document.createElement("li");d=document.createElement("a");f=document.createElement("div");l=document.createTextNode(h);g=document.createTextNode("\n          ");m=document.createElement("div");n=document.createTextNode(p);w=document.createTextNode("...");this.h()},h:function(){f.className="section-title";m.className="section-text";d.addEventListener("click",v,!1);d.href=q="#/"+e.item.id;d._svelte={component:a};b.className="item"},m:function(a,c){a.insertBefore(b,c);b.appendChild(d);d.appendChild(f);
f.appendChild(l);d.appendChild(g);d.appendChild(m);m.appendChild(n);m.appendChild(w)},p:function(a,b){e=b.item;a.filteredList&&h!==(h=e.item.title)&&(l.data=h);a.filteredList&&p!==(p=e.item.content.substr(0,100))&&(n.data=p);a.filteredList&&q!==(q="#/"+e.item.id)&&(d.href=q)},u:function(){b.parentNode.removeChild(b)},d:function(){d.removeEventListener("click",v,!1)}}}function n(a,d){for(var e,b=d.filteredList,f=[],h=0;h<b.length;h+=1)f[h]=B(a,c(c({},d),{each_value:b,item:b[h],item_index:h}));return{c:function(){e=
document.createElement("ul");for(var a=0;a<f.length;a+=1)f[a].c();this.h()},h:function(){e.className="filtered-list"},m:function(a,b){a.insertBefore(e,b);for(a=0;a<f.length;a+=1)f[a].m(e,null)},p:function(b,d){var h=d.filteredList;if(b.filteredList){for(var l=0;l<h.length;l+=1){var g=c(c({},d),{each_value:h,item:h[l],item_index:l});f[l]?f[l].p(b,g):(f[l]=B(a,g),f[l].c(),f[l].m(e,null))}for(;l<f.length;l+=1)f[l].u(),f[l].d();f.length=h.length}},u:function(){e.parentNode.removeChild(e);for(var a=0;a<
f.length;a+=1)f[a].u()},d:function(){for(var a=0;a<f.length;a+=1)f[a]&&f[a].d()}}}function m(c,d){var e;return{c:function(){e=document.createElement("h2");e.textContent="No matches found.";this.h()},h:function(){e.className="empty-message"},m:function(a,c){a.insertBefore(e,c)},u:function(){e.parentNode.removeChild(e)},d:a}}function v(a){this._svelte.component.closeSearch()}function r(a){u(this,a);this.refs={};this._state=c({searchList:[],filteredList:[],fuse:null,isOpen:!1},a.data);var d=this;a.root||
(this._oncreate=[]);this._fragment=p(this,this._state);this.root._oncreate.push(function(){z.call(d);d.fire("update",{changed:{isOpen:1,filteredList:1},current:d._state})});a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),h(this._oncreate))}function d(a){return document.createElementNS("http://www.w3.org/2000/svg",a)}function c(a,c){for(var e in c)a[e]=c[e];return a}function a(){}function u(a,c){a._handlers=Object.create(null);a._bind=c._bind;a.options=c;a.root=c.root||a;a.store=a.root.store||
c.store}function h(a){for(;a&&a.length;)a.shift()()}function y(c){this.destroy=a;this.fire("destroy");this.set=this.get=a;!1!==c&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}var f=q("fuse.js");f=f&&f.__esModule?f["default"]:f;c(r.prototype,{destroy:y,get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var e=0;e<a.length;e+=1){var b=a[e];b.__calling||(b.__calling=!0,b.call(this,c),b.__calling=!1)}},
observe:function(a,c,e){var b=c.bind(this);e&&!1===e.init||b(this.get()[a],void 0);return this.on(e&&e.defer?"update":"state",function(c){c.changed[a]&&b(c.current[a],c.previous&&c.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var e=this._handlers[a]||(this._handlers[a]=[]);e.push(c);return{cancel:function(){var a=e.indexOf(c);~a&&e.splice(a,1)}}},set:function(a){this._set(c({},a));this.root._lock||(this.root._lock=!0,h(this.root._beforecreate),h(this.root._oncreate),
h(this.root._aftercreate),this.root._lock=!1)},teardown:y,_set:function(a){var d=this._state,e={},b=!1,f;for(f in a)this._differs(a[f],d[f])&&(e[f]=b=!0);b&&(this._state=c(c({},d),a),this._recompute(e,this._state),this._bind&&this._bind(e,this._state),this._fragment&&(this.fire("state",{changed:e,current:this._state,previous:d}),this._fragment.p(e,this._state),this.fire("update",{changed:e,current:this._state,previous:d})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},
_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});c(r.prototype,{openSearch:function(){this.set({isOpen:!0});this.refs.input.focus()},closeSearch:function(){this.set({isOpen:!1})},toggleSearch:function(){this.get("isOpen")?this.closeSearch():this.openSearch()},isClosable:function(a){27===a.keyCode&&this.closeSearch()},setFuse:function(a){1>a.length||this.set({fuse:new f(a,{shouldSort:!0,findAllMatches:!0,
includeMatches:!0,threshold:.3,location:0,distance:1E4,maxPatternLength:32,minMatchCharLength:3,keys:["content"]})})},handleSearch:function(a){3<a.target.value.length?this.set({filteredList:this.get("fuse").search(a.target.value)}):this.set({filteredList:[]});console.log(this.get("filteredList"))}});r.prototype._recompute=a;x.exports=r});require.register("components/topbar.component.svelte",function(g,q,x){function z(c,d){function f(a){c.fire("mobilemenu",{action:"TOGGLE"})}function h(a){c.scrollTop()}
var g,e,b,k,n,q,r,y,u,v,x,z,E=d.settings.allow_font_size_control&&p(c,d),D=new a({root:c.root});c.refs.searchlist=D;var A=d.settings.allow_topbar_link&&B(c,d);return{c:function(){g=document.createElement("div");e=document.createElement("div");b=m("svg");k=m("use");q=document.createTextNode("\n\n    ");r=document.createElement("div");r.innerHTML='\x3cimg src\x3d"img/logo.svg" alt\x3d"Peercoin Docs"\x3e';y=document.createTextNode("\n\n    ");E&&E.c();u=document.createTextNode("\n\n    ");v=document.createElement("hr");
x=document.createTextNode("\n\n    ");D._fragment.c();z=document.createTextNode("\n\n    ");A&&A.c();this.h()},h:function(){k.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-menu-open.svg#icon");k.setAttribute("preserveAspectRatio","xMidYMid");var a=n="svg-icon "+(d.isMenuOpen?"off":"");b.setAttribute("class",a);b.setAttribute("xmlns","http://www.w3.org/2000/svg");b.setAttribute("role","img");b.setAttribute("viewBox","0 0 40 28");e.addEventListener("click",f,!1);e.className="menu-button";
r.addEventListener("click",h,!1);r.className="logo";g.className="TopbarComp"},m:function(a,c){a.insertBefore(g,c);g.appendChild(e);e.appendChild(b);b.appendChild(k);g.appendChild(q);g.appendChild(r);g.appendChild(y);E&&E.m(g,null);g.appendChild(u);g.appendChild(v);g.appendChild(x);D._mount(g,null);g.appendChild(z);A&&A.m(g,null)},p:function(a,e){a.isMenuOpen&&n!==(n="svg-icon "+(e.isMenuOpen?"off":""))&&b.setAttribute("class",n);e.settings.allow_font_size_control?E||(E=p(c,e),E.c(),E.m(g,u)):E&&(E.u(),
E.d(),E=null);e.settings.allow_topbar_link?A?A.p(a,e):(A=B(c,e),A.c(),A.m(g,null)):A&&(A.u(),A.d(),A=null)},u:function(){g.parentNode.removeChild(g);E&&E.u();A&&A.u()},d:function(){e.removeEventListener("click",f,!1);r.removeEventListener("click",h,!1);E&&E.d();D.destroy(!1);c.refs.searchlist===D&&(c.refs.searchlist=null);A&&A.d()}}}function p(a,c){function d(b){a.fire("fontsize",{action:"DECREASE"})}function h(b){a.fire("fontsize",{action:"INCREASE"})}var g,e,b,k;return{c:function(){g=document.createElement("div");
e=document.createElement("div");e.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-minus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';b=document.createTextNode("\n      ");k=document.createElement("div");k.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-plus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';
this.h()},h:function(){e.addEventListener("click",d,!1);e.className="btn btn-svg v-center";k.addEventListener("click",h,!1);k.className="btn btn-svg v-center";g.className="btn-group"},m:function(a,c){a.insertBefore(g,c);g.appendChild(e);g.appendChild(b);g.appendChild(k)},u:function(){g.parentNode.removeChild(g)},d:function(){e.removeEventListener("click",d,!1);k.removeEventListener("click",h,!1)}}}function B(a,c){var d,h,g,e=c.settings.topbar_link_label,b,k;return{c:function(){d=document.createElement("a");
h=document.createElement("span");h.textContent="Contribute to";g=document.createElement("b");b=document.createTextNode(e);this.h()},h:function(){d.href=k=c.settings.topbar_link_url;d.className="btn btn-last-link"},m:function(a,c){a.insertBefore(d,c);d.appendChild(h);d.appendChild(g);g.appendChild(b)},p:function(a,c){a.settings&&e!==(e=c.settings.topbar_link_label)&&(b.data=e);a.settings&&k!==(k=c.settings.topbar_link_url)&&(d.href=k)},u:function(){d.parentNode.removeChild(d)},d:v}}function n(a){this._handlers=
Object.create(null);this._bind=a._bind;this.options=a;this.root=a.root||this;this.store=this.root.store||a.store;this.refs={};this._state=r({settings:u},a.data);a.root||(this._oncreate=[],this._beforecreate=[],this._aftercreate=[]);this._fragment=z(this,this._state);a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),this._lock=!0,d(this._beforecreate),d(this._oncreate),d(this._aftercreate),this._lock=!1)}function m(a){return document.createElementNS("http://www.w3.org/2000/svg",a)}function v(){}
function r(a,c){for(var d in c)a[d]=c[d];return a}function d(a){for(;a&&a.length;)a.shift()()}function c(a){this.destroy=v;this.fire("destroy");this.set=this.get=v;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}var a=q("./searchlist.component"),u=q("../herodotus-settings.js");a=a&&a.__esModule?a["default"]:a;u=u&&u.__esModule?u["default"]:u;r(n.prototype,{destroy:c,get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var d=
0;d<a.length;d+=1){var h=a[d];h.__calling||(h.__calling=!0,h.call(this,c),h.__calling=!1)}},observe:function(a,c,d){var f=c.bind(this);d&&!1===d.init||f(this.get()[a],void 0);return this.on(d&&d.defer?"update":"state",function(c){c.changed[a]&&f(c.current[a],c.previous&&c.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var d=this._handlers[a]||(this._handlers[a]=[]);d.push(c);return{cancel:function(){var a=d.indexOf(c);~a&&d.splice(a,1)}}},set:function(a){this._set(r({},
a));this.root._lock||(this.root._lock=!0,d(this.root._beforecreate),d(this.root._oncreate),d(this.root._aftercreate),this.root._lock=!1)},teardown:c,_set:function(a){var c=this._state,d={},h=!1,g;for(g in a)this._differs(a[g],c[g])&&(d[g]=h=!0);h&&(this._state=r(r({},c),a),this._recompute(d,this._state),this._bind&&this._bind(d,this._state),this._fragment&&(this.fire("state",{changed:d,current:this._state,previous:c}),this._fragment.p(d,this._state),this.fire("update",{changed:d,current:this._state,
previous:c})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});n.prototype._recompute=v;x.exports=n});require.register("herodotus-settings.js",function(g,q,x){Object.defineProperty(g,"__esModule",{value:!0});g.default={documentation_name:"My awesome documentation",allow_topbar_link:!0,topbar_link_label:"Peercoin Docs Repo",
topbar_link_url:"https://github.com/peercoin/docs#peercoin-official-documentation-repository",allow_font_size_control:!0,allow_remote_documentation:!1,remote_documentation_url:""}});require.register("initialize.js",function(g,q,x){var z=(g=q("./components/main.component"))&&g.__esModule?g:{default:g};document.addEventListener("DOMContentLoaded",function(){window.mainComponent=new z.default({target:document.querySelector("main")})})});require.alias("@fdaciuk/ajax/dist/ajax.min.js","@fdaciuk/ajax");
require.alias("fuse.js/dist/fuse.js","fuse.js");require.alias("hammerjs/hammer.js","hammerjs");require.alias("marked/lib/marked.js","marked");require.alias("prismjs/prism.js","prismjs");require.register("___globals___",function(g,q,x){})})();require("___globals___");require("initialize");