/*
 Fuse.js v3.3.0 - Lightweight fuzzy-search (http://fusejs.io)

 Copyright (c) 2012-2017 Kirollos Risk (http://kiro.me)
 All Rights Reserved. Apache Software License 2.0

 http://www.apache.org/licenses/LICENSE-2.0
 Hammer.JS - v2.0.7 - 2016-04-22
 http://hammerjs.github.io/

 Copyright (c) 2016 Jorik Tangelder;
 Licensed under the MIT license */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(h,A,z){h!=Array.prototype&&h!=Object.prototype&&(h[A]=z.value)};$jscomp.getGlobal=function(h){return"undefined"!=typeof window&&window===h?h:"undefined"!=typeof global&&null!=global?global:h};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(h){return $jscomp.SYMBOL_PREFIX+(h||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var h=$jscomp.global.Symbol.iterator;h||(h=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[h]&&$jscomp.defineProperty(Array.prototype,h,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(h){var A=0;return $jscomp.iteratorPrototype(function(){return A<h.length?{done:!1,value:h[A++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(h){$jscomp.initSymbolIterator();h={next:h};h[$jscomp.global.Symbol.iterator]=function(){return this};return h};$jscomp.makeIterator=function(h){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var A=h[Symbol.iterator];return A?A.call(h):$jscomp.arrayIterator(h)};$jscomp.arrayFromIterator=function(h){for(var A,z=[];!(A=h.next()).done;)z.push(A.value);return z};$jscomp.arrayFromIterable=function(h){return h instanceof Array?h:$jscomp.arrayFromIterator($jscomp.makeIterator(h))};
$jscomp.iteratorFromArray=function(h,A){$jscomp.initSymbolIterator();h instanceof String&&(h+="");var z=0,q={next:function(){if(z<h.length){var x=z++;return{value:A(x,h[x]),done:!1}}q.next=function(){return{done:!0,value:void 0}};return q.next()}};q[Symbol.iterator]=function(){return q};return q};
$jscomp.polyfill=function(h,A,z,q){if(A){z=$jscomp.global;h=h.split(".");for(q=0;q<h.length-1;q++){var x=h[q];x in z||(z[x]={});z=z[x]}h=h[h.length-1];q=z[h];A=A(q);A!=q&&null!=A&&$jscomp.defineProperty(z,h,{configurable:!0,writable:!0,value:A})}};$jscomp.polyfill("Array.prototype.keys",function(h){return h?h:function(){return $jscomp.iteratorFromArray(this,function(h){return h})}},"es6","es3");
$jscomp.polyfill("Array.from",function(h){return h?h:function(h,z,q){$jscomp.initSymbolIterator();z=null!=z?z:function(p){return p};var x=[],C=h[Symbol.iterator];if("function"==typeof C)for(h=C.call(h);!(C=h.next()).done;)x.push(z.call(q,C.value));else{C=h.length;for(var p=0;p<C;p++)x.push(z.call(q,h[p]))}return x}},"es6","es3");$jscomp.polyfill("Array.prototype.entries",function(h){return h?h:function(){return $jscomp.iteratorFromArray(this,function(h,z){return[h,z]})}},"es6","es3");
(function(){var h="undefined"===typeof global?self:global;if("function"!==typeof h.require){var A={},z={},q={},x={}.hasOwnProperty,C=/^\.\.?(\/|$)/,p=function(a,c){var e=[];c=(C.test(c)?a+"/"+c:c).split("/");for(var u=0,g=c.length;u<g;u++)a=c[u],".."===a?e.pop():"."!==a&&""!==a&&e.push(a);return e.join("/")},B=function(a){return function(c){c=p(a.split("/").slice(0,-1).join("/"),c);return h.require(c,a)}},n=function(a){return q[a]?n(q[a]):a},k=function(a,c){return n(p(a.split("/").slice(0,-1).join("/"),
c))},v=function(a,u){null==u&&(u="/");var e=n(a);if(x.call(z,e))return z[e].exports;if(x.call(A,e))return a=A[e],u=c&&c.createHot(e),u={id:e,exports:{},hot:u},z[e]=u,a(u.exports,B(e),u),u.exports;throw Error("Cannot find module '"+a+"' from '"+u+"'");};v.alias=function(a,c){q[c]=a};var r=/\.[^.\/]+$/,f=/\/index(\.[^\/]+)?$/;v.register=v.define=function(a,c){if(a&&"object"===typeof a)for(var e in a)x.call(a,e)&&v.register(e,a[e]);else A[a]=c,delete z[a],r.test(a)&&(c=a.replace(r,""),x.call(q,c)&&q[c].replace(r,
"")!==c+"/index"||(q[c]=a)),f.test(a)&&(c=a.replace(f,""),x.call(q,c)||(q[c]=a))};v.list=function(){var a=[],c;for(c in A)x.call(A,c)&&a.push(c);return a};var c=h._hmr&&new h._hmr(k,v,A,z);v._cache=z;v.hmr=c&&c.wrap;v.brunch=!0;h.require=v}})();
(function(){var h="undefined"===typeof window?this:window,A=function(h,q,x){var C={},p=function(B,n){var k;try{return k=h(n+"/node_modules/"+B)}catch(v){if(-1===v.toString().indexOf("Cannot find module"))throw v;if(-1!==n.indexOf("node_modules"))return n=n.split("/"),k=n.lastIndexOf("node_modules"),n=n.slice(0,k).join("/"),p(B,n)}return C};return function(B){B in q&&(B=q[B]);if(B){if("."!==B[0]&&x){var n=p(B,x);if(n!==C)return n}return h(B)}}};require.register("@fdaciuk/ajax/dist/ajax.min.js",function(h,
q,x){q=A(q,{},"@fdaciuk/ajax");(function(){!function(C,p){"function"==typeof define&&define.amd?define("ajax",p):"object"==typeof h?h=x.exports=p():C.ajax=p()}(this,function(){function h(c,a,f,e){var u=["then","catch","always"].reduce(function(a,c){return a[c]=function(g){return a[c]=g,a},a},{}),g=new XMLHttpRequest;a=p(a,f,c);return g.open(c,a,!0),g.withCredentials=e.hasOwnProperty("withCredentials"),B(g,e.headers,f),g.addEventListener("readystatechange",k(u,g),!1),g.send(r(f)?JSON.stringify(f):
f),u.abort=function(){return g.abort()},u}function p(c,a,u){if("get"!==u.toLowerCase()||!a)return c;a=r(a)?f(a):a;u=-1<c.indexOf("?")?"\x26":"?";return c+u+a}function B(c,a,f){a=a||{};n(a)||(a["Content-Type"]=r(f)?"application/json":"application/x-www-form-urlencoded");Object.keys(a).forEach(function(e){a[e]&&c.setRequestHeader(e,a[e])})}function n(c){return Object.keys(c).some(function(a){return"content-type"===a.toLowerCase()})}function k(c,a){return function e(){a.readyState===a.DONE&&(a.removeEventListener("readystatechange",
e,!1),c.always.apply(c,v(a)),200<=a.status&&300>a.status?c.then.apply(c,v(a)):c["catch"].apply(c,v(a)))}}function v(c){try{var a=JSON.parse(c.responseText)}catch(u){a=c.responseText}return[a,c]}function r(c){return"[object Object]"===Object.prototype.toString.call(c)}function f(c,a){return Object.keys(c).map(function(u){if(c.hasOwnProperty(u)&&void 0!==c[u]){var e=c[u];return u=a?a+"["+u+"]":u,null!==e&&"object"==typeof e?f(e,u):encodeURIComponent(u)+"\x3d"+encodeURIComponent(e)}}).filter(Boolean).join("\x26")}
return function(c){var a=["get","post","put","delete"];return c=c||{},c.baseUrl=c.baseUrl||"",c.method&&c.url?h(c.method,c.baseUrl+c.url,c.data||null,c):a.reduce(function(a,e){return a[e]=function(a,g){return h(e,c.baseUrl+a,g||null,c)},a},{})}})})()});require.register("fuse.js/dist/fuse.js",function(h,q,x){q=A(q,{},"fuse.js");(function(){(function(C,p){"object"===typeof h&&"object"===typeof x?x.exports=p():"function"===typeof define&&define.amd?define("Fuse",[],p):"object"===typeof h?h.Fuse=p():
C.Fuse=p()})(this,function(){return function(h){function p(n){if(C[n])return C[n].exports;var k=C[n]={i:n,l:!1,exports:{}};h[n].call(k.exports,k,k.exports,p);k.l=!0;return k.exports}var C={};p.m=h;p.c=C;p.i=function(n){return n};p.d=function(n,k,v){p.o(n,k)||Object.defineProperty(n,k,{configurable:!1,enumerable:!0,get:v})};p.n=function(n){var k=n&&n.__esModule?function(){return n["default"]}:function(){return n};p.d(k,"a",k);return k};p.o=function(n,k){return Object.prototype.hasOwnProperty.call(n,
k)};p.p="";return p(p.s=8)}([function(h,p,B){h.exports=function(n){return Array.isArray?Array.isArray(n):"[object Array]"===Object.prototype.toString.call(n)}},function(h,p,B){var n=function(){function f(c,a){for(var f=0;f<a.length;f++){var e=a[f];e.enumerable=e.enumerable||!1;e.configurable=!0;"value"in e&&(e.writable=!0);Object.defineProperty(c,e.key,e)}}return function(c,a,u){a&&f(c.prototype,a);u&&f(c,u);return c}}(),k=B(5),v=B(7),r=B(4);p=function(){function f(c,a){var u=a.location;u=void 0===
u?0:u;var e=a.distance;e=void 0===e?100:e;var k=a.threshold;k=void 0===k?.6:k;var g=a.maxPatternLength;g=void 0===g?32:g;var l=a.isCaseSensitive;l=void 0===l?!1:l;var w=a.tokenSeparator;w=void 0===w?/ +/g:w;var d=a.findAllMatches;d=void 0===d?!1:d;a=a.minMatchCharLength;a=void 0===a?1:a;if(!(this instanceof f))throw new TypeError("Cannot call a class as a function");this.options={location:u,distance:e,threshold:k,maxPatternLength:g,isCaseSensitive:l,tokenSeparator:w,findAllMatches:d,minMatchCharLength:a};
this.pattern=this.options.isCaseSensitive?c:c.toLowerCase();this.pattern.length<=g&&(this.patternAlphabet=r(this.pattern))}n(f,[{key:"search",value:function(c){this.options.isCaseSensitive||(c=c.toLowerCase());if(this.pattern===c)return{isMatch:!0,score:0,matchedIndices:[[0,c.length-1]]};var a=this.options,f=a.tokenSeparator;if(this.pattern.length>a.maxPatternLength)return k(c,this.pattern,f);a=this.options;return v(c,this.pattern,this.patternAlphabet,{location:a.location,distance:a.distance,threshold:a.threshold,
findAllMatches:a.findAllMatches,minMatchCharLength:a.minMatchCharLength})}}]);return f}();h.exports=p},function(h,p,B){var n=B(0),k=function r(f,c,a){if(c){var u=c.indexOf("."),e=c,k=null;-1!==u&&(e=c.slice(0,u),k=c.slice(u+1));f=f[e];if(null!==f&&void 0!==f)if(k||"string"!==typeof f&&"number"!==typeof f)if(n(f))for(c=0,u=f.length;c<u;c+=1)r(f[c],k,a);else k&&r(f,k,a);else a.push(f.toString())}else a.push(f);return a};h.exports=function(n,f){return k(n,f,[])}},function(h,p,B){h.exports=function(){for(var n=
0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],k=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,p=[],r=-1,f,c=0,a=n.length;c<a;c+=1)(f=n[c])&&-1===r?r=c:f||-1===r||(f=c-1,f-r+1>=k&&p.push([r,f]),r=-1);n[c-1]&&c-r>=k&&p.push([r,c-1]);return p}},function(h,p,B){h.exports=function(n){for(var k={},p=n.length,r=0;r<p;r+=1)k[n.charAt(r)]=0;for(r=0;r<p;r+=1)k[n.charAt(r)]|=1<<p-r-1;return k}},function(h,p,B){var n=/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g;h.exports=function(k,p){var r=2<
arguments.length&&void 0!==arguments[2]?arguments[2]:/ +/g;r=new RegExp(p.replace(n,"\\$\x26").replace(r,"|"));r=k.match(r);var f=!!r,c=[];if(f)for(var a=0,u=r.length;a<u;a+=1){var e=r[a];c.push([k.indexOf(e),e.length-1])}return{score:f?.5:1,isMatch:f,matchedIndices:c}}},function(h,p,B){h.exports=function(n,k){var p=k.errors,r=k.currentLocation,f=k.expectedLocation;k=k.distance;k=void 0===k?100:k;n=(void 0===p?0:p)/n.length;r=Math.abs((void 0===f?0:f)-(void 0===r?0:r));return k?n+r/k:r?1:n}},function(h,
p,B){var n=B(6),k=B(3);h.exports=function(p,h,f,c){var a=c.location,u=c.distance;u=void 0===u?100:u;var e=c.threshold,y=c.findAllMatches;y=void 0===y?!1:y;c=c.minMatchCharLength;c=void 0===c?1:c;a=void 0===a?0:a;var g=p.length;e=void 0===e?.6:e;for(var l=p.indexOf(h,a),w=h.length,d=[],b=0;b<g;b+=1)d[b]=0;-1!==l&&(l=n(h,{errors:0,currentLocation:l,expectedLocation:a,distance:u}),e=Math.min(l,e),l=p.lastIndexOf(h,a+w),-1!==l&&(l=n(h,{errors:0,currentLocation:l,expectedLocation:a,distance:u}),e=Math.min(l,
e)));l=-1;b=[];for(var m=1,H=w+g,E=1<<w-1,I=0;I<w;I+=1){for(var r=0,F=H;r<F;)n(h,{errors:I,currentLocation:a+F,expectedLocation:a,distance:u})<=e?r=F:H=F,F=Math.floor((H-r)/2+r);H=F;r=Math.max(1,a-F+1);var J=y?g:Math.min(a+F,g)+w;F=Array(J+2);for(F[J+1]=(1<<I)-1;J>=r;--J){var L=J-1,G=f[p.charAt(L)];G&&(d[L]=1);F[J]=(F[J+1]<<1|1)&G;0!==I&&(F[J]=F[J]|(b[J+1]|b[J])<<1|1|b[J+1]);if(F[J]&E&&(m=n(h,{errors:I,currentLocation:L,expectedLocation:a,distance:u}),m<=e)){e=m;l=L;if(l<=a)break;r=Math.max(1,2*a-
l)}}if(n(h,{errors:I+1,currentLocation:a,expectedLocation:a,distance:u})>e)break;b=F}return{isMatch:0<=l,score:0===m?.001:m,matchedIndices:k(d,c)}}},function(h,p,B){var n=function(){function f(c,a){for(var f=0;f<a.length;f++){var e=a[f];e.enumerable=e.enumerable||!1;e.configurable=!0;"value"in e&&(e.writable=!0);Object.defineProperty(c,e.key,e)}}return function(c,a,u){a&&f(c.prototype,a);u&&f(c,u);return c}}(),k=B(1),v=B(2),r=B(0);p=function(){function f(c,a){var u=a.location;u=void 0===u?0:u;var e=
a.distance;e=void 0===e?100:e;var k=a.threshold;k=void 0===k?.6:k;var g=a.maxPatternLength;g=void 0===g?32:g;var l=a.caseSensitive;l=void 0===l?!1:l;var w=a.tokenSeparator;w=void 0===w?/ +/g:w;var d=a.findAllMatches;d=void 0===d?!1:d;var b=a.minMatchCharLength;b=void 0===b?1:b;var m=a.id;m=void 0===m?null:m;var H=a.keys;H=void 0===H?[]:H;var E=a.shouldSort;E=void 0===E?!0:E;var I=a.getFn;I=void 0===I?v:I;var n=a.sortFn;n=void 0===n?function(b,a){return b.score-a.score}:n;var F=a.tokenize;F=void 0===
F?!1:F;var J=a.matchAllTokens;J=void 0===J?!1:J;var p=a.includeMatches;p=void 0===p?!1:p;var h=a.includeScore;h=void 0===h?!1:h;a=a.verbose;a=void 0===a?!1:a;if(!(this instanceof f))throw new TypeError("Cannot call a class as a function");this.options={location:u,distance:e,threshold:k,maxPatternLength:g,isCaseSensitive:l,tokenSeparator:w,findAllMatches:d,minMatchCharLength:b,id:m,keys:H,includeMatches:p,includeScore:h,shouldSort:E,getFn:I,sortFn:n,verbose:a,tokenize:F,matchAllTokens:J};this.setCollection(c)}
n(f,[{key:"setCollection",value:function(c){return this.list=c}},{key:"search",value:function(c){this._log('---------\nSearch pattern: "'+c+'"');c=this._prepareSearchers(c);c=this._search(c.tokenSearchers,c.fullSearcher);var a=c.results;this._computeScore(c.weights,a);this.options.shouldSort&&this._sort(a);return this._format(a)}},{key:"_prepareSearchers",value:function(){var c=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"",a=[];if(this.options.tokenize)for(var f=c.split(this.options.tokenSeparator),
e=0,n=f.length;e<n;e+=1)a.push(new k(f[e],this.options));c=new k(c,this.options);return{tokenSearchers:a,fullSearcher:c}}},{key:"_search",value:function(){var c=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],a=arguments[1],f=this.list,e={},k=[];if("string"===typeof f[0]){for(var g=0,l=f.length;g<l;g+=1)this._analyze({key:"",value:f[g],record:g,index:g},{resultMap:e,results:k,tokenSearchers:c,fullSearcher:a});return{weights:null,results:k}}g={};l=0;for(var w=f.length;l<w;l+=1)for(var d=
f[l],b=0,m=this.options.keys.length;b<m;b+=1){var H=this.options.keys[b];if("string"!==typeof H){g[H.name]={weight:1-H.weight||1};if(0>=H.weight||1<H.weight)throw Error("Key weight has to be \x3e 0 and \x3c\x3d 1");H=H.name}else g[H]={weight:1};this._analyze({key:H,value:this.options.getFn(d,H),record:d,index:l},{resultMap:e,results:k,tokenSearchers:c,fullSearcher:a})}return{weights:g,results:k}}},{key:"_analyze",value:function(c,a){var f=c.key,e=c.arrayIndex,k=void 0===e?-1:e;e=c.value;var g=c.record;
c=c.index;var l=a.tokenSearchers;l=void 0===l?[]:l;var w=a.fullSearcher,d=void 0===w?[]:w;w=a.resultMap;w=void 0===w?{}:w;a=a.results;a=void 0===a?[]:a;if(void 0!==e&&null!==e){var b=!1,m=-1,H=0;if("string"===typeof e){this._log("\nKey: "+(""===f?"-":f));d=d.search(e);this._log('Full text: "'+e+'", score: '+d.score);if(this.options.tokenize){m=e.split(this.options.tokenSeparator);for(var E=[],I=0;I<l.length;I+=1){var n=l[I];this._log('\nPattern: "'+n.pattern+'"');for(var F=!1,p=0;p<m.length;p+=1){var h=
m[p],G=n.search(h),D={};G.isMatch?(D[h]=G.score,F=b=!0,E.push(G.score)):(D[h]=1,this.options.matchAllTokens||E.push(1));this._log('Token: "'+h+'", score: '+D[h])}F&&(H+=1)}m=E[0];I=E.length;for(n=1;n<I;n+=1)m+=E[n];m/=I;this._log("Token score average:",m)}E=d.score;-1<m&&(E=(E+m)/2);this._log("Score average:",E);l=this.options.tokenize&&this.options.matchAllTokens?H>=l.length:!0;this._log("\nCheck Matches: "+l);(b||d.isMatch)&&l&&((l=w[c])?l.output.push({key:f,arrayIndex:k,value:e,score:E,matchedIndices:d.matchedIndices}):
(w[c]={item:g,output:[{key:f,arrayIndex:k,value:e,score:E,matchedIndices:d.matchedIndices}]},a.push(w[c])))}else if(r(e))for(k=0,b=e.length;k<b;k+=1)this._analyze({key:f,arrayIndex:k,value:e[k],record:g,index:c},{resultMap:w,results:a,tokenSearchers:l,fullSearcher:d})}}},{key:"_computeScore",value:function(c,a){this._log("\n\nComputing score:\n");for(var f=0,e=a.length;f<e;f+=1){for(var k=a[f].output,g=k.length,l=1,w=1,d=0;d<g;d+=1){var b=c?c[k[d].key].weight:1,m=(1===b?k[d].score:k[d].score||.001)*
b;1!==b?w=Math.min(w,m):(k[d].nScore=m,l*=m)}a[f].score=1===w?l:w;this._log(a[f])}}},{key:"_sort",value:function(c){this._log("\n\nSorting....");c.sort(this.options.sortFn)}},{key:"_format",value:function(c){var a=[];this.options.verbose&&this._log("\n\nOutput:\n\n",JSON.stringify(c));var f=[];this.options.includeMatches&&f.push(function(b,a){b=b.output;a.matches=[];for(var c=0,m=b.length;c<m;c+=1){var g=b[c];if(0!==g.matchedIndices.length){var d={indices:g.matchedIndices,value:g.value};g.key&&(d.key=
g.key);g.hasOwnProperty("arrayIndex")&&-1<g.arrayIndex&&(d.arrayIndex=g.arrayIndex);a.matches.push(d)}}});this.options.includeScore&&f.push(function(b,a){a.score=b.score});for(var e=0,k=c.length;e<k;e+=1){var g=c[e];this.options.id&&(g.item=this.options.getFn(g.item,this.options.id)[0]);if(f.length){for(var l={item:g.item},w=0,d=f.length;w<d;w+=1)f[w](g,l);a.push(l)}else a.push(g.item)}return a}},{key:"_log",value:function(){if(this.options.verbose){var c;(c=console).log.apply(c,arguments)}}}]);return f}();
h.exports=p}])})})()});require.register("hammerjs/hammer.js",function(h,q,x){q=A(q,{},"hammerjs");(function(){(function(h,p,B,n){function k(b,c,g){return setTimeout(a(b,g),c)}function v(b,a,c){return Array.isArray(b)?(r(b,c[a],c),!0):!1}function r(b,a,c){var t;if(b)if(b.forEach)b.forEach(a,c);else if(b.length!==n)for(t=0;t<b.length;)a.call(c,b[t],t,b),t++;else for(t in b)b.hasOwnProperty(t)&&a.call(c,b[t],t,b)}function f(b,a,c){var t="DEPRECATED METHOD: "+a+"\n"+c+" AT \n";return function(){var a=
Error("get-stack-trace");a=a&&a.stack?a.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@"):"Unknown Stack Trace";var c=h.console&&(h.console.warn||h.console.log);c&&c.call(h.console,t,a);return b.apply(this,arguments)}}function c(b,a,c){a=a.prototype;var t=b.prototype=Object.create(a);t.constructor=b;t._super=a;c&&Q(t,c)}function a(b,a){return function(){return b.apply(a,arguments)}}function u(b,a){return"function"==typeof b?b.apply(a?
a[0]||n:n,a):b}function e(b,a,c){r(l(a),function(t){b.addEventListener(t,c,!1)})}function y(b,a,c){r(l(a),function(t){b.removeEventListener(t,c,!1)})}function g(b,a){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}function l(b){return b.trim().split(/\s+/g)}function w(b,a,c){if(b.indexOf&&!c)return b.indexOf(a);for(var t=0;t<b.length;){if(c&&b[t][c]==a||!c&&b[t]===a)return t;t++}return-1}function d(b){return Array.prototype.slice.call(b,0)}function b(b,a,c){for(var t=[],g=[],m=0;m<b.length;){var d=
a?b[m][a]:b[m];0>w(g,d)&&t.push(b[m]);g[m]=d;m++}c&&(t=a?t.sort(function(b,t){return b[a]>t[a]}):t.sort());return t}function m(b,a){for(var t,c=a[0].toUpperCase()+a.slice(1),g=0;g<ha.length;){t=(t=ha[g])?t+c:a;if(t in b)return t;g++}return n}function H(b){b=b.ownerDocument||b;return b.defaultView||b.parentWindow||h}function E(b,a){var t=this;this.manager=b;this.callback=a;this.element=b.element;this.target=b.options.inputTarget;this.domHandler=function(a){u(b.options.enable,[b])&&t.handler(a)};this.init()}
function I(b){var a=b.options.inputClass;return new (a?a:ta?N:ua?z:ia?Y:q)(b,sa)}function sa(b,a,c){var t=c.pointers.length,m=c.changedPointers.length;var d=a&1&&0===t-m;c.isFirst=!!d;c.isFinal=!!(a&12&&0===t-m);d&&(b.session={});c.eventType=a;a=b.session;t=c.pointers;m=t.length;a.firstInput||(a.firstInput=F(c));1<m&&!a.firstMultiple?a.firstMultiple=F(c):1===m&&(a.firstMultiple=!1);d=a.firstInput;var l=(m=a.firstMultiple)?m.center:d.center;var e=c.center=J(t);c.timeStamp=Z();c.deltaTime=c.timeStamp-
d.timeStamp;c.angle=D(l,e);c.distance=G(l,e);d=c.center;l=a.offsetDelta||{};e=a.prevDelta||{};var E=a.prevInput||{};if(1===c.eventType||4===E.eventType)e=a.prevDelta={x:E.deltaX||0,y:E.deltaY||0},l=a.offsetDelta={x:d.x,y:d.y};c.deltaX=e.x+(d.x-l.x);c.deltaY=e.y+(d.y-l.y);c.offsetDirection=L(c.deltaX,c.deltaY);l=c.deltaTime;d=c.deltaX/l||0;l=c.deltaY/l||0;c.overallVelocityX=d;c.overallVelocityY=l;c.overallVelocity=R(d)>R(l)?d:l;m?(d=m.pointers,d=G(t[0],t[1],T)/G(d[0],d[1],T)):d=1;c.scale=d;m?(m=m.pointers,
t=D(t[1],t[0],T)+D(m[1],m[0],T)):t=0;c.rotation=t;c.maxPointers=a.prevInput?c.pointers.length>a.prevInput.maxPointers?c.pointers.length:a.prevInput.maxPointers:c.pointers.length;l=a.lastInterval||c;t=c.timeStamp-l.timeStamp;8!=c.eventType&&(25<t||l.velocity===n)?(d=c.deltaX-l.deltaX,l=c.deltaY-l.deltaY,e=d/t||0,E=l/t||0,t=e,m=E,e=R(e)>R(E)?e:E,d=L(d,l),a.lastInterval=c):(e=l.velocity,t=l.velocityX,m=l.velocityY,d=l.direction);c.velocity=e;c.velocityX=t;c.velocityY=m;c.direction=d;a=b.element;g(c.srcEvent.target,
a)&&(a=c.srcEvent.target);c.target=a;b.emit("hammer.input",c);b.recognize(c);b.session.prevInput=c}function F(b){for(var a=[],c=0;c<b.pointers.length;)a[c]={clientX:S(b.pointers[c].clientX),clientY:S(b.pointers[c].clientY)},c++;return{timeStamp:Z(),pointers:a,center:J(a),deltaX:b.deltaX,deltaY:b.deltaY}}function J(b){var a=b.length;if(1===a)return{x:S(b[0].clientX),y:S(b[0].clientY)};for(var c=0,t=0,m=0;m<a;)c+=b[m].clientX,t+=b[m].clientY,m++;return{x:S(c/a),y:S(t/a)}}function L(b,a){return b===
a?1:R(b)>=R(a)?0>b?2:4:0>a?8:16}function G(b,a,c){c||(c=ja);var t=a[c[0]]-b[c[0]];b=a[c[1]]-b[c[1]];return Math.sqrt(t*t+b*b)}function D(b,a,c){c||(c=ja);return 180*Math.atan2(a[c[1]]-b[c[1]],a[c[0]]-b[c[0]])/Math.PI}function q(){this.evEl=va;this.evWin=wa;this.pressed=!1;E.apply(this,arguments)}function N(){this.evEl=ka;this.evWin=la;E.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function C(){this.evTarget="touchstart";this.evWin="touchstart touchmove touchend touchcancel";
this.started=!1;E.apply(this,arguments)}function z(){this.evTarget=xa;this.targetIds={};E.apply(this,arguments)}function A(a,c){var t=d(a.touches),m=this.targetIds;if(c&3&&1===t.length)return m[t[0].identifier]=!0,[t,t];a=d(a.changedTouches);var l=[],e=this.target;var E=t.filter(function(b){return g(b.target,e)});if(1===c)for(t=0;t<E.length;)m[E[t].identifier]=!0,t++;for(t=0;t<a.length;)m[a[t].identifier]&&l.push(a[t]),c&12&&delete m[a[t].identifier],t++;if(l.length)return[b(E.concat(l),"identifier",
!0),l]}function Y(){E.apply(this,arguments);var b=a(this.handler,this);this.touch=new z(this.manager,b);this.mouse=new q(this.manager,b);this.primaryTouch=null;this.lastTouches=[]}function K(b){b=b.changedPointers[0];if(b.identifier===this.primaryTouch){var a={x:b.clientX,y:b.clientY};this.lastTouches.push(a);var c=this.lastTouches;setTimeout(function(){var b=c.indexOf(a);-1<b&&c.splice(b,1)},2500)}}function aa(b,a){this.manager=b;this.set(a)}function ya(b){if(-1<b.indexOf("none"))return"none";var a=
-1<b.indexOf("pan-x"),c=-1<b.indexOf("pan-y");return a&&c?"none":a||c?a?"pan-x":"pan-y":-1<b.indexOf("manipulation")?"manipulation":"auto"}function O(b){this.options=Q({},this.defaults,b||{});this.id=za++;this.manager=null;b=this.options.enable;this.options.enable=b===n?!0:b;this.state=1;this.simultaneous={};this.requireFail=[]}function ma(b){return b&16?"cancel":b&8?"end":b&4?"move":b&2?"start":""}function na(b){return 16==b?"down":8==b?"up":2==b?"left":4==b?"right":""}function U(b,a){return(a=a.manager)?
a.get(b):b}function M(){O.apply(this,arguments)}function V(){M.apply(this,arguments);this.pY=this.pX=null}function ba(){M.apply(this,arguments)}function ca(){O.apply(this,arguments);this._input=this._timer=null}function da(){M.apply(this,arguments)}function ea(){M.apply(this,arguments)}function W(){O.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function P(b,a){a=a||{};var c=a.recognizers;a.recognizers=c===n?P.defaults.preset:c;return new fa(b,a)}function fa(b,
a){this.options=Q({},P.defaults,a||{});this.options.inputTarget=this.options.inputTarget||b;this.handlers={};this.session={};this.recognizers=[];this.oldCssProps={};this.element=b;this.input=I(this);this.touchAction=new aa(this,this.options.touchAction);oa(this,!0);r(this.options.recognizers,function(b){var a=this.add(new b[0](b[1]));b[2]&&a.recognizeWith(b[2]);b[3]&&a.requireFailure(b[3])},this)}function oa(b,a){var c=b.element;if(c.style){var t;r(b.options.cssProps,function(g,d){t=m(c.style,d);
a?(b.oldCssProps[t]=c.style[t],c.style[t]=g):c.style[t]=b.oldCssProps[t]||""});a||(b.oldCssProps={})}}function Aa(b,a){var c=p.createEvent("Event");c.initEvent(b,!0,!0);c.gesture=a;a.target.dispatchEvent(c)}var ha=" webkit Moz MS ms o".split(" "),Ba=p.createElement("div"),S=Math.round,R=Math.abs,Z=Date.now;var Q="function"!==typeof Object.assign?function(b){if(b===n||null===b)throw new TypeError("Cannot convert undefined or null to object");for(var a=Object(b),c=1;c<arguments.length;c++){var m=arguments[c];
if(m!==n&&null!==m)for(var t in m)m.hasOwnProperty(t)&&(a[t]=m[t])}return a}:Object.assign;var pa=f(function(b,a,c){for(var m=Object.keys(a),t=0;t<m.length;){if(!c||c&&b[m[t]]===n)b[m[t]]=a[m[t]];t++}return b},"extend","Use `assign`."),Ca=f(function(b,a){return pa(b,a,!0)},"merge","Use `assign`."),za=1,Da=/mobile|tablet|ip(ad|hone|od)|android/i,ia="ontouchstart"in h,ta=m(h,"PointerEvent")!==n,ua=ia&&Da.test(navigator.userAgent),ja=["x","y"],T=["clientX","clientY"];E.prototype={handler:function(){},
init:function(){this.evEl&&e(this.element,this.evEl,this.domHandler);this.evTarget&&e(this.target,this.evTarget,this.domHandler);this.evWin&&e(H(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&y(this.element,this.evEl,this.domHandler);this.evTarget&&y(this.target,this.evTarget,this.domHandler);this.evWin&&y(H(this.element),this.evWin,this.domHandler)}};var Ea={mousedown:1,mousemove:2,mouseup:4},va="mousedown",wa="mousemove mouseup";c(q,E,{handler:function(b){var a=Ea[b.type];
a&1&&0===b.button&&(this.pressed=!0);a&2&&1!==b.which&&(a=4);this.pressed&&(a&4&&(this.pressed=!1),this.callback(this.manager,a,{pointers:[b],changedPointers:[b],pointerType:"mouse",srcEvent:b}))}});var Fa={pointerdown:1,pointermove:2,pointerup:4,pointercancel:8,pointerout:8},Ga={2:"touch",3:"pen",4:"mouse",5:"kinect"},ka="pointerdown",la="pointermove pointerup pointercancel";h.MSPointerEvent&&!h.PointerEvent&&(ka="MSPointerDown",la="MSPointerMove MSPointerUp MSPointerCancel");c(N,E,{handler:function(b){var a=
this.store,c=!1,m=b.type.toLowerCase().replace("ms","");m=Fa[m];var g=Ga[b.pointerType]||b.pointerType,d="touch"==g,t=w(a,b.pointerId,"pointerId");m&1&&(0===b.button||d)?0>t&&(a.push(b),t=a.length-1):m&12&&(c=!0);0>t||(a[t]=b,this.callback(this.manager,m,{pointers:a,changedPointers:[b],pointerType:g,srcEvent:b}),c&&a.splice(t,1))}});var Ha={touchstart:1,touchmove:2,touchend:4,touchcancel:8};c(C,E,{handler:function(a){var c=Ha[a.type];1===c&&(this.started=!0);if(this.started){var m=d(a.touches);var g=
d(a.changedTouches);c&12&&(m=b(m.concat(g),"identifier",!0));m=[m,g];c&12&&0===m[0].length-m[1].length&&(this.started=!1);this.callback(this.manager,c,{pointers:m[0],changedPointers:m[1],pointerType:"touch",srcEvent:a})}}});var Ia={touchstart:1,touchmove:2,touchend:4,touchcancel:8},xa="touchstart touchmove touchend touchcancel";c(z,E,{handler:function(b){var a=Ia[b.type],c=A.call(this,b,a);c&&this.callback(this.manager,a,{pointers:c[0],changedPointers:c[1],pointerType:"touch",srcEvent:b})}});c(Y,
E,{handler:function(b,a,c){var m="mouse"==c.pointerType;if(!(m&&c.sourceCapabilities&&c.sourceCapabilities.firesTouchEvents)){if("touch"==c.pointerType)a&1?(this.primaryTouch=c.changedPointers[0].identifier,K.call(this,c)):a&12&&K.call(this,c);else{if(m)a:{m=c.srcEvent.clientX;for(var g=c.srcEvent.clientY,d=0;d<this.lastTouches.length;d++){var t=this.lastTouches[d],l=Math.abs(g-t.y);if(25>=Math.abs(m-t.x)&&25>=l){m=!0;break a}}m=!1}if(m)return}this.callback(b,a,c)}},destroy:function(){this.touch.destroy();
this.mouse.destroy()}});var qa=m(Ba.style,"touchAction"),ra=qa!==n,X=function(){if(!ra)return!1;var b={},a=h.CSS&&h.CSS.supports;"auto;manipulation;pan-y;pan-x;pan-x pan-y;none".split(";").forEach(function(c){b[c]=a?h.CSS.supports("touch-action",c):!0});return b}();aa.prototype={set:function(b){"compute"==b&&(b=this.compute());ra&&this.manager.element.style&&X[b]&&(this.manager.element.style[qa]=b);this.actions=b.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},
compute:function(){var b=[];r(this.manager.recognizers,function(a){u(a.options.enable,[a])&&(b=b.concat(a.getTouchAction()))});return ya(b.join(" "))},preventDefaults:function(b){var a=b.srcEvent,c=b.offsetDirection;if(this.manager.session.prevented)a.preventDefault();else{var m=this.actions,g=-1<m.indexOf("none")&&!X.none,d=-1<m.indexOf("pan-y")&&!X["pan-y"];m=-1<m.indexOf("pan-x")&&!X["pan-x"];if(g){var l=2>b.distance,t=250>b.deltaTime;if(1===b.pointers.length&&l&&t)return}if(!m||!d)if(g||d&&c&
6||m&&c&24)return this.preventSrc(a)}},preventSrc:function(b){this.manager.session.prevented=!0;b.preventDefault()}};O.prototype={defaults:{},set:function(b){Q(this.options,b);this.manager&&this.manager.touchAction.update();return this},recognizeWith:function(b){if(v(b,"recognizeWith",this))return this;var a=this.simultaneous;b=U(b,this);a[b.id]||(a[b.id]=b,b.recognizeWith(this));return this},dropRecognizeWith:function(b){if(v(b,"dropRecognizeWith",this))return this;b=U(b,this);delete this.simultaneous[b.id];
return this},requireFailure:function(b){if(v(b,"requireFailure",this))return this;var a=this.requireFail;b=U(b,this);-1===w(a,b)&&(a.push(b),b.requireFailure(this));return this},dropRequireFailure:function(b){if(v(b,"dropRequireFailure",this))return this;b=U(b,this);b=w(this.requireFail,b);-1<b&&this.requireFail.splice(b,1);return this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(b){return!!this.simultaneous[b.id]},emit:function(b){function a(a){c.manager.emit(a,
b)}var c=this,m=this.state;8>m&&a(c.options.event+ma(m));a(c.options.event);b.additionalEvent&&a(b.additionalEvent);8<=m&&a(c.options.event+ma(m))},tryEmit:function(b){if(this.canEmit())return this.emit(b);this.state=32},canEmit:function(){for(var b=0;b<this.requireFail.length;){if(!(this.requireFail[b].state&33))return!1;b++}return!0},recognize:function(b){b=Q({},b);u(this.options.enable,[this,b])?(this.state&56&&(this.state=1),this.state=this.process(b),this.state&30&&this.tryEmit(b)):(this.reset(),
this.state=32)},process:function(b){},getTouchAction:function(){},reset:function(){}};c(M,O,{defaults:{pointers:1},attrTest:function(b){var a=this.options.pointers;return 0===a||b.pointers.length===a},process:function(b){var a=this.state,c=b.eventType,m=a&6;b=this.attrTest(b);return m&&(c&8||!b)?a|16:m||b?c&4?a|8:a&2?a|4:2:32}});c(V,M,{defaults:{event:"pan",threshold:10,pointers:1,direction:30},getTouchAction:function(){var b=this.options.direction,a=[];b&6&&a.push("pan-y");b&24&&a.push("pan-x");
return a},directionTest:function(b){var a=this.options,c=!0,m=b.distance,g=b.direction,d=b.deltaX,l=b.deltaY;g&a.direction||(a.direction&6?(g=0===d?1:0>d?2:4,c=d!=this.pX,m=Math.abs(b.deltaX)):(g=0===l?1:0>l?8:16,c=l!=this.pY,m=Math.abs(b.deltaY)));b.direction=g;return c&&m>a.threshold&&g&a.direction},attrTest:function(b){return M.prototype.attrTest.call(this,b)&&(this.state&2||!(this.state&2)&&this.directionTest(b))},emit:function(b){this.pX=b.deltaX;this.pY=b.deltaY;var a=na(b.direction);a&&(b.additionalEvent=
this.options.event+a);this._super.emit.call(this,b)}});c(ba,M,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(b){return this._super.attrTest.call(this,b)&&(Math.abs(b.scale-1)>this.options.threshold||this.state&2)},emit:function(b){1!==b.scale&&(b.additionalEvent=this.options.event+(1>b.scale?"in":"out"));this._super.emit.call(this,b)}});c(ca,O,{defaults:{event:"press",pointers:1,time:251,threshold:9},getTouchAction:function(){return["auto"]},
process:function(b){var a=this.options,c=b.pointers.length===a.pointers,m=b.distance<a.threshold,g=b.deltaTime>a.time;this._input=b;if(!m||!c||b.eventType&12&&!g)this.reset();else if(b.eventType&1)this.reset(),this._timer=k(function(){this.state=8;this.tryEmit()},a.time,this);else if(b.eventType&4)return 8;return 32},reset:function(){clearTimeout(this._timer)},emit:function(b){8===this.state&&(b&&b.eventType&4?this.manager.emit(this.options.event+"up",b):(this._input.timeStamp=Z(),this.manager.emit(this.options.event,
this._input)))}});c(da,M,{defaults:{event:"rotate",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(b){return this._super.attrTest.call(this,b)&&(Math.abs(b.rotation)>this.options.threshold||this.state&2)}});c(ea,M,{defaults:{event:"swipe",threshold:10,velocity:.3,direction:30,pointers:1},getTouchAction:function(){return V.prototype.getTouchAction.call(this)},attrTest:function(b){var a=this.options.direction;if(a&30)var c=b.overallVelocity;else a&6?c=b.overallVelocityX:
a&24&&(c=b.overallVelocityY);return this._super.attrTest.call(this,b)&&a&b.offsetDirection&&b.distance>this.options.threshold&&b.maxPointers==this.options.pointers&&R(c)>this.options.velocity&&b.eventType&4},emit:function(b){var a=na(b.offsetDirection);a&&this.manager.emit(this.options.event+a,b);this.manager.emit(this.options.event,b)}});c(W,O,{defaults:{event:"tap",pointers:1,taps:1,interval:300,time:250,threshold:9,posThreshold:10},getTouchAction:function(){return["manipulation"]},process:function(b){var a=
this.options,c=b.pointers.length===a.pointers,m=b.distance<a.threshold,g=b.deltaTime<a.time;this.reset();if(b.eventType&1&&0===this.count)return this.failTimeout();if(m&&g&&c){if(4!=b.eventType)return this.failTimeout();c=this.pTime?b.timeStamp-this.pTime<a.interval:!0;m=!this.pCenter||G(this.pCenter,b.center)<a.posThreshold;this.pTime=b.timeStamp;this.pCenter=b.center;this.count=m&&c?this.count+1:1;this._input=b;if(0===this.count%a.taps)return this.hasRequireFailures()?(this._timer=k(function(){this.state=
8;this.tryEmit()},a.interval,this),2):8}return 32},failTimeout:function(){this._timer=k(function(){this.state=32},this.options.interval,this);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){8==this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});P.VERSION="2.0.7";P.defaults={domEvents:!1,touchAction:"compute",enable:!0,inputTarget:null,inputClass:null,preset:[[da,{enable:!1}],[ba,{enable:!1},["rotate"]],[ea,{direction:6}],[V,{direction:6},
["swipe"]],[W],[W,{event:"doubletap",taps:2},["tap"]],[ca]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};fa.prototype={set:function(b){Q(this.options,b);b.touchAction&&this.touchAction.update();b.inputTarget&&(this.input.destroy(),this.input.target=b.inputTarget,this.input.init());return this},stop:function(b){this.session.stopped=b?2:1},recognize:function(b){var a=this.session;if(!a.stopped){this.touchAction.preventDefaults(b);
var c=this.recognizers,m=a.curRecognizer;if(!m||m&&m.state&8)m=a.curRecognizer=null;for(var g=0;g<c.length;){var d=c[g];2===a.stopped||m&&d!=m&&!d.canRecognizeWith(m)?d.reset():d.recognize(b);!m&&d.state&14&&(m=a.curRecognizer=d);g++}}},get:function(b){if(b instanceof O)return b;for(var a=this.recognizers,c=0;c<a.length;c++)if(a[c].options.event==b)return a[c];return null},add:function(b){if(v(b,"add",this))return this;var a=this.get(b.options.event);a&&this.remove(a);this.recognizers.push(b);b.manager=
this;this.touchAction.update();return b},remove:function(b){if(v(b,"remove",this))return this;if(b=this.get(b)){var a=this.recognizers;b=w(a,b);-1!==b&&(a.splice(b,1),this.touchAction.update())}return this},on:function(b,a){if(b!==n&&a!==n){var c=this.handlers;r(l(b),function(b){c[b]=c[b]||[];c[b].push(a)});return this}},off:function(b,a){if(b!==n){var c=this.handlers;r(l(b),function(b){a?c[b]&&c[b].splice(w(c[b],a),1):delete c[b]});return this}},emit:function(b,a){this.options.domEvents&&Aa(b,a);
var c=this.handlers[b]&&this.handlers[b].slice();if(c&&c.length)for(a.type=b,a.preventDefault=function(){a.srcEvent.preventDefault()},b=0;b<c.length;)c[b](a),b++},destroy:function(){this.element&&oa(this,!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};Q(P,{INPUT_START:1,INPUT_MOVE:2,INPUT_END:4,INPUT_CANCEL:8,STATE_POSSIBLE:1,STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,DIRECTION_NONE:1,DIRECTION_LEFT:2,DIRECTION_RIGHT:4,
DIRECTION_UP:8,DIRECTION_DOWN:16,DIRECTION_HORIZONTAL:6,DIRECTION_VERTICAL:24,DIRECTION_ALL:30,Manager:fa,Input:E,TouchAction:aa,TouchInput:z,MouseInput:q,PointerEventInput:N,TouchMouseInput:Y,SingleTouchInput:C,Recognizer:O,AttrRecognizer:M,Tap:W,Pan:V,Swipe:ea,Pinch:ba,Rotate:da,Press:ca,on:e,off:y,each:r,merge:Ca,extend:pa,assign:Q,inherit:c,bindFn:a,prefixed:m});("undefined"!==typeof h?h:"undefined"!==typeof self?self:{}).Hammer=P;"function"===typeof define&&define.amd?define(function(){return P}):
"undefined"!=typeof x&&x.exports?x.exports=P:h[B]=P})(window,document,"Hammer")})()});require.register("marked/lib/marked.js",function(z,q,x){q=A(q,{},"marked");(function(){(function(h){function p(b){this.tokens=[];this.tokens.links={};this.options=b||y.defaults;this.rules=g.normal;this.options.gfm&&(this.rules=this.options.tables?g.tables:g.gfm)}function q(b,a){this.options=a||y.defaults;this.links=b;this.rules=l.normal;this.renderer=this.options.renderer||new n;this.renderer.options=this.options;
if(!this.links)throw Error("Tokens array requires a `links` property.");this.options.gfm?this.rules=this.options.breaks?l.breaks:l.gfm:this.options.pedantic&&(this.rules=l.pedantic)}function n(b){this.options=b||{}}function k(){}function v(b){this.tokens=[];this.token=null;this.options=b||y.defaults;this.options.renderer=this.options.renderer||new n;this.renderer=this.options.renderer;this.renderer.options=this.options}function r(b,a){return b.replace(a?/&/g:/&(?!#?\w+;)/g,"\x26amp;").replace(/</g,
"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,"\x26quot;").replace(/'/g,"\x26#39;")}function f(b){return b.replace(/&(#(?:\d+)|(?:#x[0-9A-Fa-f]+)|(?:\w+));?/ig,function(b,a){a=a.toLowerCase();return"colon"===a?":":"#"===a.charAt(0)?"x"===a.charAt(1)?String.fromCharCode(parseInt(a.substring(2),16)):String.fromCharCode(+a.substring(1)):""})}function c(b,a){b=b.source;a=a||"";return{replace:function(a,c){c=c.source||c;c=c.replace(/(^|[^\[])\^/g,"$1");b=b.replace(a,c);return this},getRegex:function(){return new RegExp(b,
a)}}}function a(b,a){w[" "+b]||(/^[^:]+:\/*[^/]*$/.test(b)?w[" "+b]=b+"/":w[" "+b]=b.replace(/[^/]*$/,""));b=w[" "+b];return"//"===a.slice(0,2)?b.replace(/:[\s\S]*/,":")+a:"/"===a.charAt(0)?b.replace(/(:\/*[^/]*)[\s\S]*/,"$1")+a:b+a}function u(){}function e(b){for(var a=1,c,g;a<arguments.length;a++)for(g in c=arguments[a],c)Object.prototype.hasOwnProperty.call(c,g)&&(b[g]=c[g]);return b}function y(b,a,c){if("undefined"===typeof b||null===b)throw Error("marked(): input parameter is undefined or null");
if("string"!==typeof b)throw Error("marked(): input parameter is of type "+Object.prototype.toString.call(b)+", string expected");if(c||"function"===typeof a){c||(c=a,a=null);a=e({},y.defaults,a||{});var m=a.highlight,g=0;try{var d=p.lex(b,a)}catch(L){return c(L)}var l=d.length;var f=function(b){if(b)return a.highlight=m,c(b);try{var g=v.parse(d,a)}catch(D){b=D}a.highlight=m;return b?c(b):c(null,g)};if(!m||3>m.length)return f();delete a.highlight;if(!l)return f();for(;g<d.length;g++)(function(b){return"code"!==
b.type?--l||f():m(b.text,b.lang,function(a,c){if(a)return f(a);if(null==c||c===b.text)return--l||f();b.text=c;b.escaped=!0;--l||f()})})(d[g])}else try{return a&&(a=e({},y.defaults,a)),v.parse(p.lex(b,a),a)}catch(L){L.message+="\nPlease report this to https://github.com/markedjs/marked.";if((a||y.defaults).silent)return"\x3cp\x3eAn error occurred:\x3c/p\x3e\x3cpre\x3e"+r(L.message+"",!0)+"\x3c/pre\x3e";throw L;}}var g={newline:/^\n+/,code:/^( {4}[^\n]+\n*)+/,fences:u,hr:/^ {0,3}((?:- *){3,}|(?:_ *){3,}|(?:\* *){3,})(?:\n+|$)/,
heading:/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n+|$)/,nptable:u,blockquote:/^( {0,3}> ?(paragraph|[^\n]*)(?:\n|$))+/,list:/^( *)(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,html:/^ *(?:comment *(?:\n|\s*$)|closed *(?:\n{2,}|\s*$)|closing *(?:\n{2,}|\s*$))/,def:/^ {0,3}\[(label)\]: *\n? *<?([^\s>]+)>?(?:(?: +\n? *| *\n *)(title))? *(?:\n+|$)/,table:u,lheading:/^([^\n]+)\n *(=|-){2,} *(?:\n+|$)/,paragraph:/^([^\n]+(?:\n?(?!hr|heading|lheading| {0,3}>|tag)[^\n]+)+)/,text:/^[^\n]+/,_label:/(?:\\[\[\]]|[^\[\]])+/,
_title:/(?:"(?:\\"|[^"]|"[^"\n]*")*"|'\n?(?:[^'\n]+\n?)*'|\([^()]*\))/};g.def=c(g.def).replace("label",g._label).replace("title",g._title).getRegex();g.bullet=/(?:[*+-]|\d+\.)/;g.item=/^( *)(bull) [^\n]*(?:\n(?!\1bull )[^\n]*)*/;g.item=c(g.item,"gm").replace(/bull/g,g.bullet).getRegex();g.list=c(g.list).replace(/bull/g,g.bullet).replace("hr","\\n+(?\x3d\\1?(?:(?:- *){3,}|(?:_ *){3,}|(?:\\* *){3,})(?:\\n+|$))").replace("def","\\n+(?\x3d"+g.def.source+")").getRegex();g._tag="(?!(?:a|em|strong|small|s|cite|q|dfn|abbr|data|time|code|var|samp|kbd|sub|sup|i|b|u|mark|ruby|rt|rp|bdi|bdo|span|br|wbr|ins|del|img)\\b)\\w+(?!:|[^\\w\\s@]*@)\\b";
g.html=c(g.html).replace("comment",/\x3c!--[\s\S]*?--\x3e/).replace("closed",/<(tag)[\s\S]+?<\/\1>/).replace("closing",/<tag(?:"[^"]*"|'[^']*'|\s[^'"\/>\s]*)*?\/?>/).replace(/tag/g,g._tag).getRegex();g.paragraph=c(g.paragraph).replace("hr",g.hr).replace("heading",g.heading).replace("lheading",g.lheading).replace("tag","\x3c"+g._tag).getRegex();g.blockquote=c(g.blockquote).replace("paragraph",g.paragraph).getRegex();g.normal=e({},g);g.gfm=e({},g.normal,{fences:/^ *(`{3,}|~{3,})[ \.]*(\S+)? *\n([\s\S]*?)\n? *\1 *(?:\n+|$)/,
paragraph:/^/,heading:/^ *(#{1,6}) +([^\n]+?) *#* *(?:\n+|$)/});g.gfm.paragraph=c(g.paragraph).replace("(?!","(?!"+g.gfm.fences.source.replace("\\1","\\2")+"|"+g.list.source.replace("\\1","\\3")+"|").getRegex();g.tables=e({},g.gfm,{nptable:/^ *(\S.*\|.*)\n *([-:]+ *\|[-| :]*)\n((?:.*\|.*(?:\n|$))*)\n*/,table:/^ *\|(.+)\n *\|( *[-:]+[-| :]*)\n((?: *\|.*(?:\n|$))*)\n*/});p.rules=g;p.lex=function(b,a){return(new p(a)).lex(b)};p.prototype.lex=function(b){b=b.replace(/\r\n|\r/g,"\n").replace(/\t/g,"    ").replace(/\u00a0/g,
" ").replace(/\u2424/g,"\n");return this.token(b,!0)};p.prototype.token=function(b,a){b=b.replace(/^ +$/gm,"");for(var c,m,d,l,e,f,w;b;){if(d=this.rules.newline.exec(b))b=b.substring(d[0].length),1<d[0].length&&this.tokens.push({type:"space"});if(d=this.rules.code.exec(b))b=b.substring(d[0].length),d=d[0].replace(/^ {4}/gm,""),this.tokens.push({type:"code",text:this.options.pedantic?d:d.replace(/\n+$/,"")});else if(d=this.rules.fences.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"code",
lang:d[2],text:d[3]||""});else if(d=this.rules.heading.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"heading",depth:d[1].length,text:d[2]});else if(a&&(d=this.rules.nptable.exec(b))){b=b.substring(d[0].length);e={type:"table",header:d[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:d[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:d[3].replace(/\n$/,"").split("\n")};for(f=0;f<e.align.length;f++)/^ *-+: *$/.test(e.align[f])?e.align[f]="right":/^ *:-+: *$/.test(e.align[f])?e.align[f]=
"center":/^ *:-+ *$/.test(e.align[f])?e.align[f]="left":e.align[f]=null;for(f=0;f<e.cells.length;f++)e.cells[f]=e.cells[f].split(/ *\| */);this.tokens.push(e)}else if(d=this.rules.hr.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"hr"});else if(d=this.rules.blockquote.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"blockquote_start"}),d=d[0].replace(/^ *> ?/gm,""),this.token(d,a),this.tokens.push({type:"blockquote_end"});else if(d=this.rules.list.exec(b)){b=b.substring(d[0].length);
l=d[2];c=1<l.length;this.tokens.push({type:"list_start",ordered:c,start:c?+l:""});d=d[0].match(this.rules.item);c=!1;w=d.length;for(f=0;f<w;f++)e=d[f],m=e.length,e=e.replace(/^ *([*+-]|\d+\.) +/,""),~e.indexOf("\n ")&&(m-=e.length,e=this.options.pedantic?e.replace(/^ {1,4}/gm,""):e.replace(new RegExp("^ {1,"+m+"}","gm"),"")),this.options.smartLists&&f!==w-1&&(m=g.bullet.exec(d[f+1])[0],l===m||1<l.length&&1<m.length||(b=d.slice(f+1).join("\n")+b,f=w-1)),m=c||/\n\n(?!\s*$)/.test(e),f!==w-1&&(c="\n"===
e.charAt(e.length-1),m||(m=c)),this.tokens.push({type:m?"loose_item_start":"list_item_start"}),this.token(e,!1),this.tokens.push({type:"list_item_end"});this.tokens.push({type:"list_end"})}else if(d=this.rules.html.exec(b))b=b.substring(d[0].length),this.tokens.push({type:this.options.sanitize?"paragraph":"html",pre:!this.options.sanitizer&&("pre"===d[1]||"script"===d[1]||"style"===d[1]),text:d[0]});else if(a&&(d=this.rules.def.exec(b)))b=b.substring(d[0].length),d[3]&&(d[3]=d[3].substring(1,d[3].length-
1)),l=d[1].toLowerCase(),this.tokens.links[l]||(this.tokens.links[l]={href:d[2],title:d[3]});else if(a&&(d=this.rules.table.exec(b))){b=b.substring(d[0].length);e={type:"table",header:d[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:d[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:d[3].replace(/(?: *\| *)?\n$/,"").split("\n")};for(f=0;f<e.align.length;f++)/^ *-+: *$/.test(e.align[f])?e.align[f]="right":/^ *:-+: *$/.test(e.align[f])?e.align[f]="center":/^ *:-+ *$/.test(e.align[f])?e.align[f]=
"left":e.align[f]=null;for(f=0;f<e.cells.length;f++)e.cells[f]=e.cells[f].replace(/^ *\| *| *\| *$/g,"").split(/ *\| */);this.tokens.push(e)}else if(d=this.rules.lheading.exec(b))b=b.substring(d[0].length),this.tokens.push({type:"heading",depth:"\x3d"===d[2]?1:2,text:d[1]});else if(a&&(d=this.rules.paragraph.exec(b)))b=b.substring(d[0].length),this.tokens.push({type:"paragraph",text:"\n"===d[1].charAt(d[1].length-1)?d[1].slice(0,-1):d[1]});else if(d=this.rules.text.exec(b))b=b.substring(d[0].length),
this.tokens.push({type:"text",text:d[0]});else if(b)throw Error("Infinite loop on byte: "+b.charCodeAt(0));}return this.tokens};var l={escape:/^\\([\\`*{}\[\]()#+\-.!_>])/,autolink:/^<(scheme:[^\s\x00-\x1f<>]*|email)>/,url:u,tag:/^\x3c!--[\s\S]*?--\x3e|^<\/?[a-zA-Z0-9\-]+(?:"[^"]*"|'[^']*'|\s[^<'">\/\s]*)*?\/?>/,link:/^!?\[(inside)\]\(href\)/,reflink:/^!?\[(inside)\]\s*\[([^\]]*)\]/,nolink:/^!?\[((?:\[[^\[\]]*\]|\\[\[\]]|[^\[\]])*)\]/,strong:/^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,em:/^_([^\s_](?:[^_]|__)+?[^\s_])_\b|^\*((?:\*\*|[^*])+?)\*(?!\*)/,
code:/^(`+)\s*([\s\S]*?[^`]?)\s*\1(?!`)/,br:/^ {2,}\n(?!\s*$)/,del:u,text:/^[\s\S]+?(?=[\\<!\[`*]|\b_| {2,}\n|$)/,_scheme:/[a-zA-Z][a-zA-Z0-9+.-]{1,31}/,_email:/[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+(@)[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+(?![-_])/};l.autolink=c(l.autolink).replace("scheme",l._scheme).replace("email",l._email).getRegex();l._inside=/(?:\[[^\[\]]*\]|\\[\[\]]|[^\[\]]|\](?=[^\[]*\]))*/;l._href=/\s*<?([\s\S]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*/;
l.link=c(l.link).replace("inside",l._inside).replace("href",l._href).getRegex();l.reflink=c(l.reflink).replace("inside",l._inside).getRegex();l.normal=e({},l);l.pedantic=e({},l.normal,{strong:/^__(?=\S)([\s\S]*?\S)__(?!_)|^\*\*(?=\S)([\s\S]*?\S)\*\*(?!\*)/,em:/^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)/});l.gfm=e({},l.normal,{escape:c(l.escape).replace("])","~|])").getRegex(),url:c(/^((?:ftp|https?):\/\/|www\.)(?:[a-zA-Z0-9\-]+\.?)+[^\s<]*|^email/).replace("email",l._email).getRegex(),
_backpedal:/(?:[^?!.,:;*_~()&]+|\([^)]*\)|&(?![a-zA-Z0-9]+;$)|[?!.,:;*_~)]+(?!$))+/,del:/^~~(?=\S)([\s\S]*?\S)~~/,text:c(l.text).replace("]|","~]|").replace("|","|https?://|ftp://|www\\.|[a-zA-Z0-9.!#$%\x26'*+/\x3d?^_`{\\|}~-]+@|").getRegex()});l.breaks=e({},l.gfm,{br:c(l.br).replace("{2,}","*").getRegex(),text:c(l.gfm.text).replace("{2,}","*").getRegex()});q.rules=l;q.output=function(b,a,c){return(new q(a,c)).output(b)};q.prototype.output=function(b){for(var a="",c,d;b;)if(d=this.rules.escape.exec(b))b=
b.substring(d[0].length),a+=d[1];else if(d=this.rules.autolink.exec(b))b=b.substring(d[0].length),"@"===d[2]?(c=r(this.mangle(d[1])),d="mailto:"+c):d=c=r(d[1]),a+=this.renderer.link(d,null,c);else if(!this.inLink&&(d=this.rules.url.exec(b)))d[0]=this.rules._backpedal.exec(d[0])[0],b=b.substring(d[0].length),"@"===d[2]?(c=r(d[0]),d="mailto:"+c):(c=r(d[0]),d="www."===d[1]?"http://"+c:c),a+=this.renderer.link(d,null,c);else if(d=this.rules.tag.exec(b))!this.inLink&&/^<a /i.test(d[0])?this.inLink=!0:
this.inLink&&/^<\/a>/i.test(d[0])&&(this.inLink=!1),b=b.substring(d[0].length),a+=this.options.sanitize?this.options.sanitizer?this.options.sanitizer(d[0]):r(d[0]):d[0];else if(d=this.rules.link.exec(b))b=b.substring(d[0].length),this.inLink=!0,a+=this.outputLink(d,{href:d[2],title:d[3]}),this.inLink=!1;else if((d=this.rules.reflink.exec(b))||(d=this.rules.nolink.exec(b)))b=b.substring(d[0].length),c=(d[2]||d[1]).replace(/\s+/g," "),(c=this.links[c.toLowerCase()])&&c.href?(this.inLink=!0,a+=this.outputLink(d,
c),this.inLink=!1):(a+=d[0].charAt(0),b=d[0].substring(1)+b);else if(d=this.rules.strong.exec(b))b=b.substring(d[0].length),a+=this.renderer.strong(this.output(d[2]||d[1]));else if(d=this.rules.em.exec(b))b=b.substring(d[0].length),a+=this.renderer.em(this.output(d[2]||d[1]));else if(d=this.rules.code.exec(b))b=b.substring(d[0].length),a+=this.renderer.codespan(r(d[2].trim(),!0));else if(d=this.rules.br.exec(b))b=b.substring(d[0].length),a+=this.renderer.br();else if(d=this.rules.del.exec(b))b=b.substring(d[0].length),
a+=this.renderer.del(this.output(d[1]));else if(d=this.rules.text.exec(b))b=b.substring(d[0].length),a+=this.renderer.text(r(this.smartypants(d[0])));else if(b)throw Error("Infinite loop on byte: "+b.charCodeAt(0));return a};q.prototype.outputLink=function(b,a){var c=r(a.href);a=a.title?r(a.title):null;return"!"!==b[0].charAt(0)?this.renderer.link(c,a,this.output(b[1])):this.renderer.image(c,a,r(b[1]))};q.prototype.smartypants=function(b){return this.options.smartypants?b.replace(/---/g,"\u2014").replace(/--/g,
"\u2013").replace(/(^|[-\u2014/(\[{"\s])'/g,"$1\u2018").replace(/'/g,"\u2019").replace(/(^|[-\u2014/(\[{\u2018\s])"/g,"$1\u201c").replace(/"/g,"\u201d").replace(/\.{3}/g,"\u2026"):b};q.prototype.mangle=function(b){if(!this.options.mangle)return b;for(var a="",c=b.length,d=0,g;d<c;d++)g=b.charCodeAt(d),.5<Math.random()&&(g="x"+g.toString(16)),a+="\x26#"+g+";";return a};n.prototype.code=function(b,a,c){if(this.options.highlight){var d=this.options.highlight(b,a);null!=d&&d!==b&&(c=!0,b=d)}return a?
'\x3cpre\x3e\x3ccode class\x3d"'+this.options.langPrefix+r(a,!0)+'"\x3e'+(c?b:r(b,!0))+"\n\x3c/code\x3e\x3c/pre\x3e\n":"\x3cpre\x3e\x3ccode\x3e"+(c?b:r(b,!0))+"\n\x3c/code\x3e\x3c/pre\x3e"};n.prototype.blockquote=function(b){return"\x3cblockquote\x3e\n"+b+"\x3c/blockquote\x3e\n"};n.prototype.html=function(b){return b};n.prototype.heading=function(b,a,c){return"\x3ch"+a+' id\x3d"'+this.options.headerPrefix+c.toLowerCase().replace(/[^\w]+/g,"-")+'"\x3e'+b+"\x3c/h"+a+"\x3e\n"};n.prototype.hr=function(){return this.options.xhtml?
"\x3chr/\x3e\n":"\x3chr\x3e\n"};n.prototype.list=function(b,a,c){var d=a?"ol":"ul";return"\x3c"+d+(a&&1!==c?' start\x3d"'+c+'"':"")+"\x3e\n"+b+"\x3c/"+d+"\x3e\n"};n.prototype.listitem=function(b){return"\x3cli\x3e"+b+"\x3c/li\x3e\n"};n.prototype.paragraph=function(b){return"\x3cp\x3e"+b+"\x3c/p\x3e\n"};n.prototype.table=function(b,a){return"\x3ctable\x3e\n\x3cthead\x3e\n"+b+"\x3c/thead\x3e\n\x3ctbody\x3e\n"+a+"\x3c/tbody\x3e\n\x3c/table\x3e\n"};n.prototype.tablerow=function(b){return"\x3ctr\x3e\n"+
b+"\x3c/tr\x3e\n"};n.prototype.tablecell=function(b,a){var c=a.header?"th":"td";return(a.align?"\x3c"+c+' style\x3d"text-align:'+a.align+'"\x3e':"\x3c"+c+"\x3e")+b+"\x3c/"+c+"\x3e\n"};n.prototype.strong=function(b){return"\x3cstrong\x3e"+b+"\x3c/strong\x3e"};n.prototype.em=function(b){return"\x3cem\x3e"+b+"\x3c/em\x3e"};n.prototype.codespan=function(b){return"\x3ccode\x3e"+b+"\x3c/code\x3e"};n.prototype.br=function(){return this.options.xhtml?"\x3cbr/\x3e":"\x3cbr\x3e"};n.prototype.del=function(b){return"\x3cdel\x3e"+
b+"\x3c/del\x3e"};n.prototype.link=function(b,c,g){if(this.options.sanitize){try{var m=decodeURIComponent(f(b)).replace(/[^\w:]/g,"").toLowerCase()}catch(I){return g}if(0===m.indexOf("javascript:")||0===m.indexOf("vbscript:")||0===m.indexOf("data:"))return g}this.options.baseUrl&&!d.test(b)&&(b=a(this.options.baseUrl,b));b='\x3ca href\x3d"'+b+'"';c&&(b+=' title\x3d"'+c+'"');return b+("\x3e"+g+"\x3c/a\x3e")};n.prototype.image=function(b,c,g){this.options.baseUrl&&!d.test(b)&&(b=a(this.options.baseUrl,
b));b='\x3cimg src\x3d"'+b+'" alt\x3d"'+g+'"';c&&(b+=' title\x3d"'+c+'"');return b+=this.options.xhtml?"/\x3e":"\x3e"};n.prototype.text=function(b){return b};k.prototype.strong=k.prototype.em=k.prototype.codespan=k.prototype.del=k.prototype.text=function(b){return b};k.prototype.link=k.prototype.image=function(b,a,c){return""+c};k.prototype.br=function(){return""};v.parse=function(b,a){return(new v(a)).parse(b)};v.prototype.parse=function(b){this.inline=new q(b.links,this.options);this.inlineText=
new q(b.links,e({},this.options,{renderer:new k}));this.tokens=b.reverse();for(b="";this.next();)b+=this.tok();return b};v.prototype.next=function(){return this.token=this.tokens.pop()};v.prototype.peek=function(){return this.tokens[this.tokens.length-1]||0};v.prototype.parseText=function(){for(var b=this.token.text;"text"===this.peek().type;)b+="\n"+this.next().text;return this.inline.output(b)};v.prototype.tok=function(){switch(this.token.type){case "space":return"";case "hr":return this.renderer.hr();
case "heading":return this.renderer.heading(this.inline.output(this.token.text),this.token.depth,f(this.inlineText.output(this.token.text)));case "code":return this.renderer.code(this.token.text,this.token.lang,this.token.escaped);case "table":var b="";var a="";var c,d;var g="";for(c=0;c<this.token.header.length;c++)g+=this.renderer.tablecell(this.inline.output(this.token.header[c]),{header:!0,align:this.token.align[c]});b+=this.renderer.tablerow(g);for(c=0;c<this.token.cells.length;c++){var l=this.token.cells[c];
g="";for(d=0;d<l.length;d++)g+=this.renderer.tablecell(this.inline.output(l[d]),{header:!1,align:this.token.align[d]});a+=this.renderer.tablerow(g)}return this.renderer.table(b,a);case "blockquote_start":for(a="";"blockquote_end"!==this.next().type;)a+=this.tok();return this.renderer.blockquote(a);case "list_start":a="";b=this.token.ordered;for(c=this.token.start;"list_end"!==this.next().type;)a+=this.tok();return this.renderer.list(a,b,c);case "list_item_start":for(a="";"list_item_end"!==this.next().type;)a+=
"text"===this.token.type?this.parseText():this.tok();return this.renderer.listitem(a);case "loose_item_start":for(a="";"list_item_end"!==this.next().type;)a+=this.tok();return this.renderer.listitem(a);case "html":return a=this.token.pre||this.options.pedantic?this.token.text:this.inline.output(this.token.text),this.renderer.html(a);case "paragraph":return this.renderer.paragraph(this.inline.output(this.token.text));case "text":return this.renderer.paragraph(this.parseText())}};var w={},d=/^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;
u.exec=u;y.options=y.setOptions=function(b){e(y.defaults,b);return y};y.defaults={gfm:!0,tables:!0,breaks:!1,pedantic:!1,sanitize:!1,sanitizer:null,mangle:!0,smartLists:!1,silent:!1,highlight:null,langPrefix:"lang-",smartypants:!1,headerPrefix:"",renderer:new n,xhtml:!1,baseUrl:null};y.Parser=v;y.parser=v.parse;y.Renderer=n;y.TextRenderer=k;y.Lexer=p;y.lexer=p.lex;y.InlineLexer=q;y.inlineLexer=q.output;y.parse=y;"undefined"!==typeof x&&"object"===typeof z?x.exports=y:"function"===typeof define&&define.amd?
define(function(){return y}):h.marked=y})(this||("undefined"!==typeof window?window:h))})()});require.register("prismjs/prism.js",function(z,q,x){q=A(q,{},"prismjs");(function(){var q="undefined"!==typeof window?window:"undefined"!==typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?self:{},p=function(){var h=/\blang(?:uage)?-([\w-]+)\b/i,n=0,k=q.Prism={manual:q.Prism&&q.Prism.manual,disableWorkerMessageHandler:q.Prism&&q.Prism.disableWorkerMessageHandler,util:{encode:function(f){return f instanceof
p?new p(f.type,k.util.encode(f.content),f.alias):"Array"===k.util.type(f)?f.map(k.util.encode):f.replace(/&/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/\u00a0/g," ")},type:function(f){return Object.prototype.toString.call(f).match(/\[object (\w+)\]/)[1]},objId:function(f){f.__id||Object.defineProperty(f,"__id",{value:++n});return f.__id},clone:function(f,c){var a=k.util.type(f);c=c||{};switch(a){case "Object":if(c[k.util.objId(f)])return c[k.util.objId(f)];var h={};c[k.util.objId(f)]=h;for(var e in f)f.hasOwnProperty(e)&&
(h[e]=k.util.clone(f[e],c));return h;case "Array":if(c[k.util.objId(f)])return c[k.util.objId(f)];h=[];c[k.util.objId(f)]=h;f.forEach(function(a,g){h[g]=k.util.clone(a,c)});return h}return f}},languages:{extend:function(f,c){f=k.util.clone(k.languages[f]);for(var a in c)f[a]=c[a];return f},insertBefore:function(f,c,a,h){h=h||k.languages;var e=h[f];if(2==arguments.length){a=arguments[1];for(var n in a)a.hasOwnProperty(n)&&(e[n]=a[n]);return e}var g={},l;for(l in e)if(e.hasOwnProperty(l)){if(l==c)for(n in a)a.hasOwnProperty(n)&&
(g[n]=a[n]);g[l]=e[l]}k.languages.DFS(k.languages,function(a,c){c===h[f]&&a!=f&&(this[a]=g)});return h[f]=g},DFS:function(f,c,a,h){h=h||{};for(var e in f)f.hasOwnProperty(e)&&((c.call(f,e,f[e],a||e),"Object"!==k.util.type(f[e])||h[k.util.objId(f[e])])?"Array"!==k.util.type(f[e])||h[k.util.objId(f[e])]||(h[k.util.objId(f[e])]=!0,k.languages.DFS(f[e],c,e,h)):(h[k.util.objId(f[e])]=!0,k.languages.DFS(f[e],c,null,h)))}},plugins:{},highlightAll:function(f,c){k.highlightAllUnder(document,f,c)},highlightAllUnder:function(f,
c,a){a={callback:a,selector:'code[class*\x3d"language-"], [class*\x3d"language-"] code, code[class*\x3d"lang-"], [class*\x3d"lang-"] code'};k.hooks.run("before-highlightall",a);f=a.elements||f.querySelectorAll(a.selector);for(var h=0,e;e=f[h++];)k.highlightElement(e,!0===c,a.callback)},highlightElement:function(f,c,a){for(var n,e,p=f;p&&!h.test(p.className);)p=p.parentNode;p&&(n=(p.className.match(h)||[,""])[1].toLowerCase(),e=k.languages[n]);f.className=f.className.replace(h,"").replace(/\s+/g," ")+
" language-"+n;f.parentNode&&(p=f.parentNode,/pre/i.test(p.nodeName)&&(p.className=p.className.replace(h,"").replace(/\s+/g," ")+" language-"+n));var g={element:f,language:n,grammar:e,code:f.textContent};k.hooks.run("before-sanity-check",g);g.code&&g.grammar?(k.hooks.run("before-highlight",g),c&&q.Worker?(f=new Worker(k.filename),f.onmessage=function(c){g.highlightedCode=c.data;k.hooks.run("before-insert",g);g.element.innerHTML=g.highlightedCode;a&&a.call(g.element);k.hooks.run("after-highlight",
g);k.hooks.run("complete",g)},f.postMessage(JSON.stringify({language:g.language,code:g.code,immediateClose:!0}))):(g.highlightedCode=k.highlight(g.code,g.grammar,g.language),k.hooks.run("before-insert",g),g.element.innerHTML=g.highlightedCode,a&&a.call(f),k.hooks.run("after-highlight",g),k.hooks.run("complete",g))):(g.code&&(k.hooks.run("before-highlight",g),g.element.textContent=g.code,k.hooks.run("after-highlight",g)),k.hooks.run("complete",g))},highlight:function(f,c,a){f={code:f,grammar:c,language:a};
k.hooks.run("before-tokenize",f);f.tokens=k.tokenize(f.code,f.grammar);k.hooks.run("after-tokenize",f);return p.stringify(k.util.encode(f.tokens),f.language)},matchGrammar:function(f,c,a,h,e,n,g){var l=k.Token,w;for(w in a)if(a.hasOwnProperty(w)&&a[w]){if(w==g)break;var d=a[w];d="Array"===k.util.type(d)?d:[d];for(var b=0;b<d.length;++b){var m=d[b],p=m.inside,E=!!m.lookbehind,u=!!m.greedy,r=0,F=m.alias;if(u&&!m.pattern.global){var q=m.pattern.toString().match(/[imuy]*$/)[0];m.pattern=RegExp(m.pattern.source,
q+"g")}m=m.pattern||m;q=h;for(var y=e;q<c.length;y+=c[q].length,++q){var G=c[q];if(c.length>f.length)return;if(!(G instanceof l)){if(u&&q!=c.length-1){m.lastIndex=y;var D=m.exec(f);if(!D)break;var v=D.index+(E?D[1].length:0);var N=D.index+D[0].length;var z=q;G=y;for(var B=c.length;z<B&&(G<N||!c[z].type&&!c[z-1].greedy);++z)G+=c[z].length,v>=G&&(++q,y=G);if(c[q]instanceof l)continue;z-=q;G=f.slice(y,G);D.index-=y}else m.lastIndex=0,D=m.exec(G),z=1;D&&(E&&(r=D[1]?D[1].length:0),v=D.index+r,D=D[0].slice(r),
N=v+D.length,v=G.slice(0,v),N=G.slice(N),G=[q,z],v&&(++q,y+=v.length,G.push(v)),D=new l(w,p?k.tokenize(D,p):D,F,D,u),G.push(D),N&&G.push(N),Array.prototype.splice.apply(c,G),1!=z&&k.matchGrammar(f,c,a,q,y,!0,w));if(n)break}}}}},tokenize:function(f,c,a){a=[f];var h=c.rest;if(h){for(var e in h)c[e]=h[e];delete c.rest}k.matchGrammar(f,a,c,0,0,!1);return a},hooks:{all:{},add:function(f,c){var a=k.hooks.all;a[f]=a[f]||[];a[f].push(c)},run:function(f,c){if((f=k.hooks.all[f])&&f.length)for(var a=0,h;h=f[a++];)h(c)}}},
p=k.Token=function(f,c,a,k,e){this.type=f;this.content=c;this.alias=a;this.length=(k||"").length|0;this.greedy=!!e};p.stringify=function(f,c,a){if("string"==typeof f)return f;if("Array"===k.util.type(f))return f.map(function(a){return p.stringify(a,c,f)}).join("");var h={type:f.type,content:p.stringify(f.content,c,a),tag:"span",classes:["token",f.type],attributes:{},language:c,parent:a};f.alias&&(a="Array"===k.util.type(f.alias)?f.alias:[f.alias],Array.prototype.push.apply(h.classes,a));k.hooks.run("wrap",
h);a=Object.keys(h.attributes).map(function(a){return a+'\x3d"'+(h.attributes[a]||"").replace(/"/g,"\x26quot;")+'"'}).join(" ");return"\x3c"+h.tag+' class\x3d"'+h.classes.join(" ")+'"'+(a?" "+a:"")+"\x3e"+h.content+"\x3c/"+h.tag+"\x3e"};if(!q.document){if(!q.addEventListener)return q.Prism;k.disableWorkerMessageHandler||q.addEventListener("message",function(f){f=JSON.parse(f.data);var c=f.language,a=f.immediateClose;q.postMessage(k.highlight(f.code,k.languages[c],c));a&&q.close()},!1);return q.Prism}var r=
document.currentScript||[].slice.call(document.getElementsByTagName("script")).pop();r&&(k.filename=r.src,k.manual||r.hasAttribute("data-manual")||("loading"!==document.readyState?window.requestAnimationFrame?window.requestAnimationFrame(k.highlightAll):window.setTimeout(k.highlightAll,16):document.addEventListener("DOMContentLoaded",k.highlightAll)));return q.Prism}();"undefined"!==typeof x&&x.exports&&(x.exports=p);"undefined"!==typeof h&&(h.Prism=p);p.languages.markup={comment:/\x3c!--[\s\S]*?--\x3e/,
prolog:/<\?[\s\S]+?\?>/,doctype:/<!DOCTYPE[\s\S]+?>/i,cdata:/<!\[CDATA\[[\s\S]*?]]\x3e/i,tag:{pattern:/<\/?(?!\d)[^\s>\/=$<%]+(?:\s+[^\s>\/=]+(?:=(?:("|')(?:\\[\s\S]|(?!\1)[^\\])*\1|[^\s'">=]+))?)*\s*\/?>/i,greedy:!0,inside:{tag:{pattern:/^<\/?[^\s>\/]+/i,inside:{punctuation:/^<\/?/,namespace:/^[^\s>\/:]+:/}},"attr-value":{pattern:/=(?:("|')(?:\\[\s\S]|(?!\1)[^\\])*\1|[^\s'">=]+)/i,inside:{punctuation:[/^=/,{pattern:/(^|[^\\])["']/,lookbehind:!0}]}},punctuation:/\/?>/,"attr-name":{pattern:/[^\s>\/]+/,
inside:{namespace:/^[^\s>\/:]+:/}}}},entity:/&#?[\da-z]{1,8};/i};p.languages.markup.tag.inside["attr-value"].inside.entity=p.languages.markup.entity;p.hooks.add("wrap",function(h){"entity"===h.type&&(h.attributes.title=h.content.replace(/&amp;/,"\x26"))});p.languages.xml=p.languages.markup;p.languages.html=p.languages.markup;p.languages.mathml=p.languages.markup;p.languages.svg=p.languages.markup;p.languages.css={comment:/\/\*[\s\S]*?\*\//,atrule:{pattern:/@[\w-]+?.*?(?:;|(?=\s*\{))/i,inside:{rule:/@[\w-]+/}},
url:/url\((?:(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1|.*?)\)/i,selector:/[^{}\s][^{};]*?(?=\s*\{)/,string:{pattern:/("|')(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},property:/[-_a-z\xA0-\uFFFF][-\w\xA0-\uFFFF]*(?=\s*:)/i,important:/\B!important\b/i,"function":/[-a-z0-9]+(?=\()/i,punctuation:/[(){};:]/};p.languages.css.atrule.inside.rest=p.languages.css;p.languages.markup&&(p.languages.insertBefore("markup","tag",{style:{pattern:/(<style[\s\S]*?>)[\s\S]*?(?=<\/style>)/i,lookbehind:!0,
inside:p.languages.css,alias:"language-css",greedy:!0}}),p.languages.insertBefore("inside","attr-value",{"style-attr":{pattern:/\s*style=("|')(?:\\[\s\S]|(?!\1)[^\\])*\1/i,inside:{"attr-name":{pattern:/^\s*style/i,inside:p.languages.markup.tag.inside},punctuation:/^\s*=\s*['"]|['"]\s*$/,"attr-value":{pattern:/.+/i,inside:p.languages.css}},alias:"language-css"}},p.languages.markup.tag));p.languages.clike={comment:[{pattern:/(^|[^\\])\/\*[\s\S]*?(?:\*\/|$)/,lookbehind:!0},{pattern:/(^|[^\\:])\/\/.*/,
lookbehind:!0,greedy:!0}],string:{pattern:/(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},"class-name":{pattern:/((?:\b(?:class|interface|extends|implements|trait|instanceof|new)\s+)|(?:catch\s+\())[\w.\\]+/i,lookbehind:!0,inside:{punctuation:/[.\\]/}},keyword:/\b(?:if|else|while|do|for|return|in|instanceof|function|new|try|throw|catch|finally|null|break|continue)\b/,"boolean":/\b(?:true|false)\b/,"function":/[a-z0-9_]+(?=\()/i,number:/\b0x[\da-f]+\b|(?:\b\d+\.?\d*|\B\.\d+)(?:e[+-]?\d+)?/i,
operator:/--?|\+\+?|!=?=?|<=?|>=?|==?=?|&&?|\|\|?|\?|\*|\/|~|\^|%/,punctuation:/[{}[\];(),.:]/};p.languages.javascript=p.languages.extend("clike",{keyword:/\b(?:as|async|await|break|case|catch|class|const|continue|debugger|default|delete|do|else|enum|export|extends|finally|for|from|function|get|if|implements|import|in|instanceof|interface|let|new|null|of|package|private|protected|public|return|set|static|super|switch|this|throw|try|typeof|var|void|while|with|yield)\b/,number:/\b(?:0[xX][\dA-Fa-f]+|0[bB][01]+|0[oO][0-7]+|NaN|Infinity)\b|(?:\b\d+\.?\d*|\B\.\d+)(?:[Ee][+-]?\d+)?/,
"function":/[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*(?=\s*\()/i,operator:/-[-=]?|\+[+=]?|!=?=?|<<?=?|>>?>?=?|=(?:==?|>)?|&[&=]?|\|[|=]?|\*\*?=?|\/=?|~|\^=?|%=?|\?|\.{3}/});p.languages.insertBefore("javascript","keyword",{regex:{pattern:/((?:^|[^$\w\xA0-\uFFFF."'\])\s])\s*)\/(\[[^\]\r\n]+]|\\.|[^/\\\[\r\n])+\/[gimyu]{0,5}(?=\s*($|[\r\n,.;})\]]))/,lookbehind:!0,greedy:!0},"function-variable":{pattern:/[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*(?=\s*=\s*(?:function\b|(?:\([^()]*\)|[_$a-z\xA0-\uFFFF][$\w\xA0-\uFFFF]*)\s*=>))/i,
alias:"function"},constant:/\b[A-Z][A-Z\d_]*\b/});p.languages.insertBefore("javascript","string",{"template-string":{pattern:/`(?:\\[\s\S]|\${[^}]+}|[^\\`])*`/,greedy:!0,inside:{interpolation:{pattern:/\${[^}]+}/,inside:{"interpolation-punctuation":{pattern:/^\${|}$/,alias:"punctuation"},rest:null}},string:/[\s\S]+/}}});p.languages.javascript["template-string"].inside.interpolation.inside.rest=p.languages.javascript;p.languages.markup&&p.languages.insertBefore("markup","tag",{script:{pattern:/(<script[\s\S]*?>)[\s\S]*?(?=<\/script>)/i,
lookbehind:!0,inside:p.languages.javascript,alias:"language-javascript",greedy:!0}});p.languages.js=p.languages.javascript;(function(){"undefined"!==typeof self&&self.Prism&&self.document&&document.querySelector&&(self.Prism.fileHighlight=function(){var h={js:"javascript",py:"python",rb:"ruby",ps1:"powershell",psm1:"powershell",sh:"bash",bat:"batch",h:"c",tex:"latex"};Array.prototype.slice.call(document.querySelectorAll("pre[data-src]")).forEach(function(n){for(var k=n.getAttribute("data-src"),q,
r=n,f=/\blang(?:uage)?-([\w-]+)\b/i;r&&!f.test(r.className);)r=r.parentNode;r&&(q=(n.className.match(f)||[,""])[1]);q||(q=(k.match(/\.(\w+)$/)||[,""])[1],q=h[q]||q);var c=document.createElement("code");c.className="language-"+q;n.textContent="";c.textContent="Loading\u2026";n.appendChild(c);var a=new XMLHttpRequest;a.open("GET",k,!0);a.onreadystatechange=function(){4==a.readyState&&(400>a.status&&a.responseText?(c.textContent=a.responseText,p.highlightElement(c)):c.textContent=400<=a.status?"\u2716 Error "+
a.status+" while fetching file: "+a.statusText:"\u2716 Error: File does not exist or is empty")};a.send(null)});p.plugins.toolbar&&p.plugins.toolbar.registerButton("download-file",function(h){if((h=h.element.parentNode)&&/pre/i.test(h.nodeName)&&h.hasAttribute("data-src")&&h.hasAttribute("data-download-link")){var k=h.getAttribute("data-src"),n=document.createElement("a");n.textContent=h.getAttribute("data-download-link-label")||"Download";n.setAttribute("download","");n.href=k;return n}})},document.addEventListener("DOMContentLoaded",
self.Prism.fileHighlight))})()})()});require.register("components/main.component.svelte",function(h,q,x){function z(g,l){var e,d,b,m,f,h,k,n,p=new a({root:g.root});p.on("mobilemenu",function(b){g.handleMobileMenu(b)});p.on("fontsize",function(b){g.handleFontSize(b)});g.refs.topbar=p;var q=new c({root:g.root});q.on("mobilemenu",function(b){g.handleMobileMenu(b)});g.refs.menu=q;return{c:function(){e=document.createElement("div");p._fragment.c();d=document.createTextNode("\n  ");q._fragment.c();b=document.createTextNode("\n  ");
m=document.createElement("div");f=document.createElement("div");h=document.createTextNode("\n    ");k=document.createElement("div");this.h()},h:function(){f.className="menu-swipper";k.className=n="doc-container font-"+l.fontSize;m.className="body";e.className="MainComp"},m:function(a,c){a.insertBefore(e,c);p._mount(e,null);e.appendChild(d);q._mount(e,null);e.appendChild(b);e.appendChild(m);m.appendChild(f);m.appendChild(h);m.appendChild(k);k.innerHTML=l.documentationHTML;g.refs.docContainer=k},p:function(b,
a){b.documentationHTML&&(k.innerHTML=a.documentationHTML);b.fontSize&&n!==(n="doc-container font-"+a.fontSize)&&(k.className=n)},u:function(){k.innerHTML="";e.parentNode.removeChild(e)},d:function(){p.destroy(!1);g.refs.topbar===p&&(g.refs.topbar=null);q.destroy(!1);g.refs.menu===q&&(g.refs.menu=null);g.refs.docContainer===k&&(g.refs.docContainer=null)}}}function p(a){B(this,a);this.refs={};this._state=n({fontSize:2,documentation:"",documentationHTML:""},a.data);var c=this;a.root||(this._oncreate=
[],this._beforecreate=[],this._aftercreate=[]);this._fragment=z(this,this._state);this.root._oncreate.push(function(){c.registerDocumentation();c.fire("update",{changed:{fontSize:1,documentationHTML:1},current:c._state})});a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),this._lock=!0,k(this._beforecreate),k(this._oncreate),k(this._aftercreate),this._lock=!1)}function B(a,c){a._handlers=Object.create(null);a._bind=c._bind;a.options=c;a.root=c.root||a;a.store=a.root.store||c.store}function n(a,
c){for(var g in c)a[g]=c[g];return a}function k(a){for(;a&&a.length;)a.shift()()}function v(a){this.destroy=r;this.fire("destroy");this.set=this.get=r;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function r(){}var f=q("../herodotus-settings.js"),c=q("./menu.component"),a=q("./topbar.component"),u=q("marked"),e=q("@fdaciuk/ajax");q("hammerjs");var y=q("prismjs");f=f&&f.__esModule?f["default"]:f;c=c&&c.__esModule?c["default"]:c;a=a&&a.__esModule?a["default"]:a;u=u&&
u.__esModule?u["default"]:u;e=e&&e.__esModule?e["default"]:e;y=y&&y.__esModule?y["default"]:y;n(p.prototype,{destroy:v,get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var g=0;g<a.length;g+=1){var d=a[g];d.__calling||(d.__calling=!0,d.call(this,c),d.__calling=!1)}},observe:function(a,c,e){var d=c.bind(this);e&&!1===e.init||d(this.get()[a],void 0);return this.on(e&&e.defer?"update":"state",function(b){b.changed[a]&&d(b.current[a],
b.previous&&b.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var g=this._handlers[a]||(this._handlers[a]=[]);g.push(c);return{cancel:function(){var a=g.indexOf(c);~a&&g.splice(a,1)}}},set:function(a){this._set(n({},a));this.root._lock||(this.root._lock=!0,k(this.root._beforecreate),k(this.root._oncreate),k(this.root._aftercreate),this.root._lock=!1)},teardown:v,_set:function(a){var c=this._state,g={},d=!1,b;for(b in a)this._differs(a[b],c[b])&&(g[b]=d=!0);d&&(this._state=
n(n({},c),a),this._recompute(g,this._state),this._bind&&this._bind(g,this._state),this._fragment&&(this.fire("state",{changed:g,current:this._state,previous:c}),this._fragment.p(g,this._state),this.fire("update",{changed:g,current:this._state,previous:c})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});n(p.prototype,{getParentId:function(a){return"end"===
a?null:a.id&&-1<["H1","H2"].indexOf(a.tagName)?{id:a.id,title:a.textContent}:this.getParentId(a.previousElementSibling||"end")},generateSearchList:function(){var a=this,c=[];[].concat($jscomp.arrayFromIterable(document.querySelector(".doc-container").children)).forEach(function(e){var d=a.getParentId(e);d&&c.push({id:d.id,title:d.title,content:e.textContent})});return c},handleFontSize:function(a){switch(a.action){case "INCREASE":this.increaseFont();break;case "DECREASE":this.decreaseFont()}},handleMobileMenu:function(a){switch(a.action){case "TOGGLE":this.refs.topbar.set({isMenuOpen:this.refs.menu.toggle()});
break;case "CLOSE":this.refs.menu.close();this.refs.topbar.set({isMenuOpen:!1});break;case "OPEN":this.refs.menu.open(),this.refs.topbar.set({isMenuOpen:!0})}},increaseFont:function(){var a=this.get("fontSize");4<=a||this.set({fontSize:a+1})},decreaseFont:function(){var a=this.get("fontSize");1>=a||this.set({fontSize:a-1})},registerDocumentation:function(){var a=this;var c=f.allow_remote_documentation?f.remote_documentation_url:"documentation.md";e().get(c).then(function(c,d){a.set({documentation:c,
documentationHTML:u(c)});a.refs.menu.startMenu(a.generateMenu());a.refs.topbar.refs.searchlist.set({searchList:a.generateSearchList()});a.responsiveTables();y.highlightAll()})},responsiveTables:function(){Array.from(document.querySelectorAll(".doc-container table")).forEach(function(a){var c=document.createElement("div");c.classList.add("responsive-table");a.parentElement.insertBefore(c,a);c.appendChild(a)})},generateMenu:function(){var a=[],c=[],e;this.refs.docContainer.querySelectorAll("h1, h2").forEach(function(d){c.push({type:d.nodeName.toLowerCase(),
label:d.textContent,id:d.id});"h1"===d.nodeName.toLowerCase()?(a.push({type:d.nodeName.toLowerCase(),label:d.textContent,id:d.id}),e=a[a.length-1],e.children=[]):"h2"===d.nodeName.toLowerCase()&&e.children.push({type:d.nodeName.toLowerCase(),label:d.textContent,id:d.id})});return{menuItems:a,menuItemsFlat:c}}});p.prototype._recompute=r;x.exports=p});require.register("components/menu.component.svelte",function(h,q,x){function z(a,b){(new w(a)).on("swipeleft",b)}function p(){var a=this;window.onhashchange=
function(){a.scrollToURLMenu()}}function B(c,b){function d(b){c.onAppScroll(this.scrollY)}function e(b){c.fire("mobilemenu",{action:"CLOSE"})}var f,g,l,h,k,p,w,q,r,y;window.addEventListener("scroll",d);for(var v=b.menuItems,x=[],B=0;B<v.length;B+=1)x[B]=n(c,a(a({},b),{each_value:v,item:v[B],item_index:B}));return{c:function(){f=document.createElement("div");g=document.createElement("div");h=document.createTextNode("\n  ");k=document.createElement("div");p=document.createElement("img");w=document.createTextNode("\n    ");
q=document.createElement("ul");for(var b=0;b<x.length;b+=1)x[b].c();this.h()},h:function(){g.addEventListener("click",e,!1);g.className=l="MenuComp--overlay "+(b.isOpen?"active":"");p.src="img/logo-green.svg";p.alt="Peercoin Docs";p.className="logo";q.className="menu";r=z.call(c,k,function(b){c.fire("mobilemenu",{action:"CLOSE"})});k.className=y="MenuComp "+(b.isOpen?"open":"")},m:function(b,a){b.insertBefore(f,a);f.appendChild(g);c.refs.overlay=g;f.appendChild(h);f.appendChild(k);k.appendChild(p);
k.appendChild(w);k.appendChild(q);for(b=0;b<x.length;b+=1)x[b].m(q,null);c.refs.menu=k},p:function(b,d){b.isOpen&&l!==(l="MenuComp--overlay "+(d.isOpen?"active":""))&&(g.className=l);var e=d.menuItems;if(b.menuItems){for(var m=0;m<e.length;m+=1){var f=a(a({},d),{each_value:e,item:e[m],item_index:m});x[m]?x[m].p(b,f):(x[m]=n(c,f),x[m].c(),x[m].m(q,null))}for(;m<x.length;m+=1)x[m].u(),x[m].d();x.length=e.length}b.isOpen&&y!==(y="MenuComp "+(d.isOpen?"open":""))&&(k.className=y)},u:function(){f.parentNode.removeChild(f);
for(var b=0;b<x.length;b+=1)x[b].u()},d:function(){window.removeEventListener("scroll",d);g.removeEventListener("click",e,!1);c.refs.overlay===g&&(c.refs.overlay=null);u(x);r[r.destroy?"destroy":"teardown"]();c.refs.menu===k&&(c.refs.menu=null)}}}function n(a,b){var c=b.item,d,e,f=c.label,g,l,h,k,p,n=0<c.children.length&&v(a,b);return{c:function(){d=document.createElement("li");e=document.createElement("a");g=document.createTextNode(f);h=document.createTextNode("\n            ");n&&n.c();this.h()},
h:function(){e.addEventListener("click",r,!1);e.href=l="#"+c.id;e._svelte={component:a,each_value:b.each_value,item_index:b.item_index};d.id=k="menu-"+c.id;d.className=p=c.type},m:function(b,a){b.insertBefore(d,a);d.appendChild(e);e.appendChild(g);d.appendChild(h);n&&n.m(d,null)},p:function(b,m){c=m.item;b.menuItems&&f!==(f=c.label)&&(g.data=f);b.menuItems&&l!==(l="#"+c.id)&&(e.href=l);e._svelte.each_value=m.each_value;e._svelte.item_index=m.item_index;0<c.children.length?n?n.p(b,m):(n=v(a,m),n.c(),
n.m(d,null)):n&&(n.u(),n.d(),n=null);b.menuItems&&k!==(k="menu-"+c.id)&&(d.id=k);b.menuItems&&p!==(p=c.type)&&(d.className=p)},u:function(){d.parentNode.removeChild(d);n&&n.u()},d:function(){e.removeEventListener("click",r,!1);n&&n.d()}}}function k(a,b){var c=b.subitem,d,e,g=c.label,l,h,k,n;return{c:function(){d=document.createElement("li");e=document.createElement("a");l=document.createTextNode(g);this.h()},h:function(){e.addEventListener("click",f,!1);e.href=h="#"+c.id;e._svelte={component:a,each_value_1:b.each_value_1,
subitem_index:b.subitem_index};d.id=k="menu-"+c.id;d.className=n=c.type},m:function(b,a){b.insertBefore(d,a);d.appendChild(e);e.appendChild(l)},p:function(b,a){c=a.subitem;b.menuItems&&g!==(g=c.label)&&(l.data=g);b.menuItems&&h!==(h="#"+c.id)&&(e.href=h);e._svelte.each_value_1=a.each_value_1;e._svelte.subitem_index=a.subitem_index;b.menuItems&&k!==(k="menu-"+c.id)&&(d.id=k);b.menuItems&&n!==(n=c.type)&&(d.className=n)},u:function(){d.parentNode.removeChild(d)},d:function(){e.removeEventListener("click",
f,!1)}}}function v(c,b){for(var d=b.item,e,f=d.children,g=[],l=0;l<f.length;l+=1)g[l]=k(c,a(a({},b),{each_value_1:f,subitem:f[l],subitem_index:l}));return{c:function(){e=document.createElement("ul");for(var b=0;b<g.length;b+=1)g[b].c();this.h()},h:function(){e.className="subsection"},m:function(b,a){b.insertBefore(e,a);for(b=0;b<g.length;b+=1)g[b].m(e,null)},p:function(b,f){d=f.item;var m=d.children;if(b.menuItems){for(var l=0;l<m.length;l+=1){var h=a(a({},f),{each_value_1:m,subitem:m[l],subitem_index:l});
g[l]?g[l].p(b,h):(g[l]=k(c,h),g[l].c(),g[l].m(e,null))}for(;l<g.length;l+=1)g[l].u(),g[l].d();g.length=m.length}},u:function(){e.parentNode.removeChild(e);for(var b=0;b<g.length;b+=1)g[b].u()},d:function(){u(g)}}}function r(a){this._svelte.component.scrollToItem(this._svelte.each_value[this._svelte.item_index],a)}function f(a){this._svelte.component.scrollToItem(this._svelte.each_value_1[this._svelte.subitem_index],a)}function c(c){e(this,c);this.refs={};this._state=a({menuItems:[],menuItemsFlat:[],
isOpen:!1,prevY:0},c.data);var b=this;c.root||(this._oncreate=[]);this._fragment=B(this,this._state);this.root._oncreate.push(function(){p.call(b);b.fire("update",{changed:{isOpen:1,menuItems:1},current:b._state})});c.target&&(this._fragment.c(),this._mount(c.target,c.anchor),y(this._oncreate))}function a(a,b){for(var c in b)a[c]=b[c];return a}function u(a){for(var b=0;b<a.length;b+=1)a[b]&&a[b].d()}function e(a,b){a._handlers=Object.create(null);a._bind=b._bind;a.options=b;a.root=b.root||a;a.store=
a.root.store||b.store}function y(a){for(;a&&a.length;)a.shift()()}function g(a){this.destroy=l;this.fire("destroy");this.set=this.get=l;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function l(){}var w=q("hammerjs");w=w&&w.__esModule?w["default"]:w;a(c.prototype,{destroy:g,get:function(a){return a?this._state[a]:this._state},fire:function(a,b){if(a=a in this._handlers&&this._handlers[a].slice())for(var c=0;c<a.length;c+=1){var d=a[c];d.__calling||(d.__calling=!0,d.call(this,
b),d.__calling=!1)}},observe:function(a,b,c){var d=b.bind(this);c&&!1===c.init||d(this.get()[a],void 0);return this.on(c&&c.defer?"update":"state",function(b){b.changed[a]&&d(b.current[a],b.previous&&b.previous[a])})},on:function(a,b){if("teardown"===a)return this.on("destroy",b);var c=this._handlers[a]||(this._handlers[a]=[]);c.push(b);return{cancel:function(){var a=c.indexOf(b);~a&&c.splice(a,1)}}},set:function(c){this._set(a({},c));this.root._lock||(this.root._lock=!0,y(this.root._beforecreate),
y(this.root._oncreate),y(this.root._aftercreate),this.root._lock=!1)},teardown:g,_set:function(c){var b=this._state,d={},e=!1,g;for(g in c)this._differs(c[g],b[g])&&(d[g]=e=!0);e&&(this._state=a(a({},b),c),this._recompute(d,this._state),this._bind&&this._bind(d,this._state),this._fragment&&(this.fire("state",{changed:d,current:this._state,previous:b}),this._fragment.p(d,this._state),this.fire("update",{changed:d,current:this._state,previous:b})))},_mount:function(a,b){this._fragment[this._fragment.i?
"i":"m"](a,b||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,b){return a!=a?b==b:a!==b||a&&"object"===typeof a||"function"===typeof a}});a(c.prototype,{onAppScroll:function(a){a=this.get("menuItemsFlat");a=$jscomp.makeIterator(a.entries());for(var b=a.next();!b.done;b=a.next()){b=$jscomp.makeIterator(b.value);b.next();b=b.next().value;var c=document.getElementById(b.id),d=c.getBoundingClientRect().top;c=c.getBoundingClientRect().bottom;if(0<=d&&c<=window.innerHeight){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu li.active"))).map(function(a){return a.classList.remove("active")});
a=document.getElementById("menu-"+b.id);a.classList.add("active");b=a.parentNode;b.classList.contains("subsection")&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),b.classList.add("show"));0<a.querySelectorAll(".subsection").length&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),a.querySelector(".subsection").classList.add("show"));
break}}},startMenu:function(a){var b=this;this.set(a);setTimeout(function(){b.scrollToURLMenu()},10)},scrollTop:function(){window.scrollTo(0,0);this.close()},scrollToURLMenu:function(){var a=window.location.hash.substr(2),b=this.get("menuItemsFlat").filter(function(b){return b.id===a});0<b.length?(b=document.getElementById(b[0].id),b=window.scrollY+b.getBoundingClientRect().top-70,window.scrollTo(0,b)):window.scrollTo(0,1)},toggle:function(){this.set({isOpen:!this.refs.menu.isOpen});return this.refs.menu.isOpen},
close:function(){this.set({isOpen:!1})},open:function(){this.set({isOpen:!0})},scrollToItem:function(a,b){b&&b.preventDefault();window.location.hash="/"+a.id;this.get("menuItemsFlat");a=window.scrollY+document.getElementById(a.id).getBoundingClientRect().top-70;window.scrollTo(0,a);this.fire("mobilemenu",{action:"CLOSE"})}});c.prototype._recompute=l;x.exports=c});require.register("components/searchlist.component.svelte",function(h,q,x){function z(){var a=this;this.observe("searchList",function(c){a.fuse=
a.setFuse(c)})}function p(a,c){function d(b){a.toggleSearch()}function b(b){a.closeSearch()}function e(b){a.handleSearch(b)}function g(b){a.isClosable(b)}var l,h,p,w,q,r,u,y,v,x,z,B,A,C=1<c.filteredList.length&&n(a,c),K=1>c.filteredList.length&&k(a,c);return{c:function(){l=document.createElement("div");h=document.createElement("div");p=f("svg");w=f("use");q=document.createTextNode("\n  \n  ");r=document.createElement("div");y=document.createTextNode("\n\n  ");v=document.createElement("div");x=document.createElement("input");
z=document.createTextNode("\n    ");C&&C.c();B=document.createTextNode("\n\n    ");K&&K.c();this.h()},h:function(){w.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-search.svg#icon");w.setAttribute("preserveAspectRatio","xMidYMid");p.addEventListener("click",d,!1);p.setAttribute("class","svg-icon");p.setAttribute("xmlns","http://www.w3.org/2000/svg");p.setAttribute("role","img");p.setAttribute("viewBox","0 0 15 15");h.className="btn btn-svg";r.addEventListener("click",b,!1);r.className=
u="SearchListComp--overlay "+(c.isOpen?"active":"");x.addEventListener("input",e,!1);x.addEventListener("keydown",g,!1);x.setAttribute("type","text");x.className="filter-input";x.placeholder="Search here...";v.className=A="search-popup "+(c.isOpen?"open":"");l.className="SearchListComp"},m:function(b,c){b.insertBefore(l,c);l.appendChild(h);h.appendChild(p);p.appendChild(w);l.appendChild(q);l.appendChild(r);l.appendChild(y);l.appendChild(v);v.appendChild(x);a.refs.input=x;v.appendChild(z);C&&C.m(v,
null);v.appendChild(B);K&&K.m(v,null)},p:function(b,c){b.isOpen&&u!==(u="SearchListComp--overlay "+(c.isOpen?"active":""))&&(r.className=u);1<c.filteredList.length?C?C.p(b,c):(C=n(a,c),C.c(),C.m(v,B)):C&&(C.u(),C.d(),C=null);1>c.filteredList.length?K||(K=k(a,c),K.c(),K.m(v,null)):K&&(K.u(),K.d(),K=null);b.isOpen&&A!==(A="search-popup "+(c.isOpen?"open":""))&&(v.className=A)},u:function(){l.parentNode.removeChild(l);C&&C.u();K&&K.u()},d:function(){p.removeEventListener("click",d,!1);r.removeEventListener("click",
b,!1);x.removeEventListener("input",e,!1);x.removeEventListener("keydown",g,!1);a.refs.input===x&&(a.refs.input=null);C&&C.d();K&&K.d()}}}function B(a,c){var d=c.item,b,e,g,f=d.item.title,l,h,k,n=d.item.content.substr(0,100),p,w,q;return{c:function(){b=document.createElement("li");e=document.createElement("a");g=document.createElement("div");l=document.createTextNode(f);h=document.createTextNode("\n          ");k=document.createElement("div");p=document.createTextNode(n);w=document.createTextNode("...");
this.h()},h:function(){g.className="section-title";k.className="section-text";e.addEventListener("click",v,!1);e.href=q="#/"+d.item.id;e._svelte={component:a};b.className="item"},m:function(a,c){a.insertBefore(b,c);b.appendChild(e);e.appendChild(g);g.appendChild(l);e.appendChild(h);e.appendChild(k);k.appendChild(p);k.appendChild(w)},p:function(a,b){d=b.item;a.filteredList&&f!==(f=d.item.title)&&(l.data=f);a.filteredList&&n!==(n=d.item.content.substr(0,100))&&(p.data=n);a.filteredList&&q!==(q="#/"+
d.item.id)&&(e.href=q)},u:function(){b.parentNode.removeChild(b)},d:function(){e.removeEventListener("click",v,!1)}}}function n(a,e){for(var d,b=e.filteredList,g=[],f=0;f<b.length;f+=1)g[f]=B(a,c(c({},e),{each_value:b,item:b[f],item_index:f}));return{c:function(){d=document.createElement("ul");for(var a=0;a<g.length;a+=1)g[a].c();this.h()},h:function(){d.className="filtered-list"},m:function(a,b){a.insertBefore(d,b);for(a=0;a<g.length;a+=1)g[a].m(d,null)},p:function(b,e){var f=e.filteredList;if(b.filteredList){for(var l=
0;l<f.length;l+=1){var h=c(c({},e),{each_value:f,item:f[l],item_index:l});g[l]?g[l].p(b,h):(g[l]=B(a,h),g[l].c(),g[l].m(d,null))}for(;l<g.length;l+=1)g[l].u(),g[l].d();g.length=f.length}},u:function(){d.parentNode.removeChild(d);for(var a=0;a<g.length;a+=1)g[a].u()},d:function(){for(var a=0;a<g.length;a+=1)g[a]&&g[a].d()}}}function k(c,e){var d;return{c:function(){d=document.createElement("h2");d.textContent="No matches found.";this.h()},h:function(){d.className="empty-message"},m:function(a,c){a.insertBefore(d,
c)},u:function(){d.parentNode.removeChild(d)},d:a}}function v(a){this._svelte.component.closeSearch()}function r(a){u(this,a);this.refs={};this._state=c({searchList:[],filteredList:[],fuse:null,isOpen:!1},a.data);var g=this;a.root||(this._oncreate=[]);this._fragment=p(this,this._state);this.root._oncreate.push(function(){z.call(g);g.fire("update",{changed:{isOpen:1,filteredList:1},current:g._state})});a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),e(this._oncreate))}function f(a){return document.createElementNS("http://www.w3.org/2000/svg",
a)}function c(a,c){for(var d in c)a[d]=c[d];return a}function a(){}function u(a,c){a._handlers=Object.create(null);a._bind=c._bind;a.options=c;a.root=c.root||a;a.store=a.root.store||c.store}function e(a){for(;a&&a.length;)a.shift()()}function y(c){this.destroy=a;this.fire("destroy");this.set=this.get=a;!1!==c&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}var g=q("fuse.js");g=g&&g.__esModule?g["default"]:g;c(r.prototype,{destroy:y,get:function(a){return a?this._state[a]:this._state},
fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var d=0;d<a.length;d+=1){var b=a[d];b.__calling||(b.__calling=!0,b.call(this,c),b.__calling=!1)}},observe:function(a,c,d){var b=c.bind(this);d&&!1===d.init||b(this.get()[a],void 0);return this.on(d&&d.defer?"update":"state",function(c){c.changed[a]&&b(c.current[a],c.previous&&c.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var d=this._handlers[a]||(this._handlers[a]=[]);d.push(c);return{cancel:function(){var a=
d.indexOf(c);~a&&d.splice(a,1)}}},set:function(a){this._set(c({},a));this.root._lock||(this.root._lock=!0,e(this.root._beforecreate),e(this.root._oncreate),e(this.root._aftercreate),this.root._lock=!1)},teardown:y,_set:function(a){var e=this._state,d={},b=!1,g;for(g in a)this._differs(a[g],e[g])&&(d[g]=b=!0);b&&(this._state=c(c({},e),a),this._recompute(d,this._state),this._bind&&this._bind(d,this._state),this._fragment&&(this.fire("state",{changed:d,current:this._state,previous:e}),this._fragment.p(d,
this._state),this.fire("update",{changed:d,current:this._state,previous:e})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});c(r.prototype,{openSearch:function(){this.set({isOpen:!0});this.refs.input.focus()},closeSearch:function(){this.set({isOpen:!1})},toggleSearch:function(){this.get("isOpen")?this.closeSearch():this.openSearch()},
isClosable:function(a){27===a.keyCode&&this.closeSearch()},setFuse:function(a){1>a.length||this.set({fuse:new g(a,{shouldSort:!0,findAllMatches:!0,includeMatches:!0,threshold:.3,location:0,distance:1E4,maxPatternLength:32,minMatchCharLength:3,keys:["content"]})})},handleSearch:function(a){3<a.target.value.length?this.set({filteredList:this.get("fuse").search(a.target.value)}):this.set({filteredList:[]});console.log(this.get("filteredList"))}});r.prototype._recompute=a;x.exports=r});require.register("components/topbar.component.svelte",
function(h,q,x){function z(c,f){function e(a){c.fire("mobilemenu",{action:"TOGGLE"})}function l(a){c.scrollTop()}var h,d,b,m,n,q,r,u,y,v,x,z,D=f.settings.allow_font_size_control&&p(c,f),C=new a({root:c.root});c.refs.searchlist=C;var A=f.settings.allow_topbar_link&&B(c,f);return{c:function(){h=document.createElement("div");d=document.createElement("div");b=k("svg");m=k("use");q=document.createTextNode("\n\n    ");r=document.createElement("div");r.innerHTML='\x3cimg src\x3d"img/logo.svg" alt\x3d"Peercoin Docs"\x3e';
u=document.createTextNode("\n\n    ");D&&D.c();y=document.createTextNode("\n\n    ");v=document.createElement("hr");x=document.createTextNode("\n\n    ");C._fragment.c();z=document.createTextNode("\n\n    ");A&&A.c();this.h()},h:function(){m.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-menu-open.svg#icon");m.setAttribute("preserveAspectRatio","xMidYMid");var a=n="svg-icon "+(f.isMenuOpen?"off":"");b.setAttribute("class",a);b.setAttribute("xmlns","http://www.w3.org/2000/svg");
b.setAttribute("role","img");b.setAttribute("viewBox","0 0 40 28");d.addEventListener("click",e,!1);d.className="menu-button";r.addEventListener("click",l,!1);r.className="logo";h.className="TopbarComp"},m:function(a,c){a.insertBefore(h,c);h.appendChild(d);d.appendChild(b);b.appendChild(m);h.appendChild(q);h.appendChild(r);h.appendChild(u);D&&D.m(h,null);h.appendChild(y);h.appendChild(v);h.appendChild(x);C._mount(h,null);h.appendChild(z);A&&A.m(h,null)},p:function(a,d){a.isMenuOpen&&n!==(n="svg-icon "+
(d.isMenuOpen?"off":""))&&b.setAttribute("class",n);d.settings.allow_font_size_control?D||(D=p(c,d),D.c(),D.m(h,y)):D&&(D.u(),D.d(),D=null);d.settings.allow_topbar_link?A?A.p(a,d):(A=B(c,d),A.c(),A.m(h,null)):A&&(A.u(),A.d(),A=null)},u:function(){h.parentNode.removeChild(h);D&&D.u();A&&A.u()},d:function(){d.removeEventListener("click",e,!1);r.removeEventListener("click",l,!1);D&&D.d();C.destroy(!1);c.refs.searchlist===C&&(c.refs.searchlist=null);A&&A.d()}}}function p(a,c){function e(b){a.fire("fontsize",
{action:"DECREASE"})}function f(b){a.fire("fontsize",{action:"INCREASE"})}var h,d,b,k;return{c:function(){h=document.createElement("div");d=document.createElement("div");d.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-minus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';b=document.createTextNode("\n      ");k=document.createElement("div");k.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-plus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';
this.h()},h:function(){d.addEventListener("click",e,!1);d.className="btn btn-svg v-center";k.addEventListener("click",f,!1);k.className="btn btn-svg v-center";h.className="btn-group"},m:function(a,c){a.insertBefore(h,c);h.appendChild(d);h.appendChild(b);h.appendChild(k)},u:function(){h.parentNode.removeChild(h)},d:function(){d.removeEventListener("click",e,!1);k.removeEventListener("click",f,!1)}}}function B(a,c){var e,f,h,d=c.settings.topbar_link_label,b,k;return{c:function(){e=document.createElement("a");
f=document.createElement("span");f.textContent="Contribute to";h=document.createElement("b");b=document.createTextNode(d);this.h()},h:function(){e.href=k=c.settings.topbar_link_url;e.className="btn btn-last-link"},m:function(a,c){a.insertBefore(e,c);e.appendChild(f);e.appendChild(h);h.appendChild(b)},p:function(a,c){a.settings&&d!==(d=c.settings.topbar_link_label)&&(b.data=d);a.settings&&k!==(k=c.settings.topbar_link_url)&&(e.href=k)},u:function(){e.parentNode.removeChild(e)},d:v}}function n(a){this._handlers=
Object.create(null);this._bind=a._bind;this.options=a;this.root=a.root||this;this.store=this.root.store||a.store;this.refs={};this._state=r({settings:u},a.data);a.root||(this._oncreate=[],this._beforecreate=[],this._aftercreate=[]);this._fragment=z(this,this._state);a.target&&(this._fragment.c(),this._mount(a.target,a.anchor),this._lock=!0,f(this._beforecreate),f(this._oncreate),f(this._aftercreate),this._lock=!1)}function k(a){return document.createElementNS("http://www.w3.org/2000/svg",a)}function v(){}
function r(a,c){for(var e in c)a[e]=c[e];return a}function f(a){for(;a&&a.length;)a.shift()()}function c(a){this.destroy=v;this.fire("destroy");this.set=this.get=v;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}var a=q("./searchlist.component"),u=q("../herodotus-settings.js");a=a&&a.__esModule?a["default"]:a;u=u&&u.__esModule?u["default"]:u;r(n.prototype,{destroy:c,get:function(a){return a?this._state[a]:this._state},fire:function(a,c){if(a=a in this._handlers&&this._handlers[a].slice())for(var e=
0;e<a.length;e+=1){var f=a[e];f.__calling||(f.__calling=!0,f.call(this,c),f.__calling=!1)}},observe:function(a,c,f){var e=c.bind(this);f&&!1===f.init||e(this.get()[a],void 0);return this.on(f&&f.defer?"update":"state",function(c){c.changed[a]&&e(c.current[a],c.previous&&c.previous[a])})},on:function(a,c){if("teardown"===a)return this.on("destroy",c);var e=this._handlers[a]||(this._handlers[a]=[]);e.push(c);return{cancel:function(){var a=e.indexOf(c);~a&&e.splice(a,1)}}},set:function(a){this._set(r({},
a));this.root._lock||(this.root._lock=!0,f(this.root._beforecreate),f(this.root._oncreate),f(this.root._aftercreate),this.root._lock=!1)},teardown:c,_set:function(a){var c=this._state,e={},f=!1,h;for(h in a)this._differs(a[h],c[h])&&(e[h]=f=!0);f&&(this._state=r(r({},c),a),this._recompute(e,this._state),this._bind&&this._bind(e,this._state),this._fragment&&(this.fire("state",{changed:e,current:this._state,previous:c}),this._fragment.p(e,this._state),this.fire("update",{changed:e,current:this._state,
previous:c})))},_mount:function(a,c){this._fragment[this._fragment.i?"i":"m"](a,c||null)},_unmount:function(){this._fragment&&this._fragment.u()},_differs:function(a,c){return a!=a?c==c:a!==c||a&&"object"===typeof a||"function"===typeof a}});n.prototype._recompute=v;x.exports=n});require.register("herodotus-settings.js",function(h,q,x){Object.defineProperty(h,"__esModule",{value:!0});h.default={documentation_name:"My awesome documentation",allow_topbar_link:!0,topbar_link_label:"Peercoin Docs Repo",
topbar_link_url:"https://github.com/peercoin/docs#peercoin-official-documentation-repository",allow_font_size_control:!0,allow_remote_documentation:!1,remote_documentation_url:""}});require.register("initialize.js",function(h,q,x){var z=(h=q("./components/main.component"))&&h.__esModule?h:{default:h};document.addEventListener("DOMContentLoaded",function(){window.mainComponent=new z.default({target:document.querySelector("main")})})});require.alias("@fdaciuk/ajax/dist/ajax.min.js","@fdaciuk/ajax");
require.alias("fuse.js/dist/fuse.js","fuse.js");require.alias("hammerjs/hammer.js","hammerjs");require.alias("marked/lib/marked.js","marked");require.alias("prismjs/prism.js","prismjs");require.register("___globals___",function(h,q,x){})})();require("___globals___");require("initialize");