/*
 Fuse.js v3.2.0 - Lightweight fuzzy-search (http://fusejs.io)

 Copyright (c) 2012-2017 Kirollos Risk (http://kiro.me)
 All Rights Reserved. Apache Software License 2.0

 http://www.apache.org/licenses/LICENSE-2.0
 Hammer.JS - v2.0.7 - 2016-04-22
 http://hammerjs.github.io/

 Copyright (c) 2016 Jorik Tangelder;
 Licensed under the MIT license */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,y,A){f!=Array.prototype&&f!=Object.prototype&&(f[y]=A.value)};$jscomp.getGlobal=function(f){return"undefined"!=typeof window&&window===f?f:"undefined"!=typeof global&&null!=global?global:f};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(f){return $jscomp.SYMBOL_PREFIX+(f||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var f=$jscomp.global.Symbol.iterator;f||(f=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[f]&&$jscomp.defineProperty(Array.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(f){var y=0;return $jscomp.iteratorPrototype(function(){return y<f.length?{done:!1,value:f[y++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(f){$jscomp.initSymbolIterator();f={next:f};f[$jscomp.global.Symbol.iterator]=function(){return this};return f};$jscomp.makeIterator=function(f){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var y=f[Symbol.iterator];return y?y.call(f):$jscomp.arrayIterator(f)};$jscomp.arrayFromIterator=function(f){for(var y,A=[];!(y=f.next()).done;)A.push(y.value);return A};$jscomp.arrayFromIterable=function(f){return f instanceof Array?f:$jscomp.arrayFromIterator($jscomp.makeIterator(f))};
$jscomp.iteratorFromArray=function(f,y){$jscomp.initSymbolIterator();f instanceof String&&(f+="");var A=0,v={next:function(){if(A<f.length){var z=A++;return{value:y(z,f[z]),done:!1}}v.next=function(){return{done:!0,value:void 0}};return v.next()}};v[Symbol.iterator]=function(){return v};return v};
$jscomp.polyfill=function(f,y,A,v){if(y){A=$jscomp.global;f=f.split(".");for(v=0;v<f.length-1;v++){var z=f[v];z in A||(A[z]={});A=A[z]}f=f[f.length-1];v=A[f];y=y(v);y!=v&&null!=y&&$jscomp.defineProperty(A,f,{configurable:!0,writable:!0,value:y})}};$jscomp.polyfill("Array.prototype.keys",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(f){return f})}},"es6","es3");
$jscomp.polyfill("Array.prototype.entries",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(f,A){return[f,A]})}},"es6","es3");
(function(){var f="undefined"===typeof global?self:global;if("function"!==typeof f.require){var y={},A={},v={},z={}.hasOwnProperty,M=/^\.\.?(\/|$)/,u=function(b,g){var n=[];g=(M.test(g)?b+"/"+g:g).split("/");for(var l=0,p=g.length;l<p;l++)b=g[l],".."===b?n.pop():"."!==b&&""!==b&&n.push(b);return n.join("/")},q=function(b){return function(g){g=u(b.split("/").slice(0,-1).join("/"),g);return f.require(g,b)}},m=function(b){return v[b]?m(v[b]):b},x=function(b,g){return m(u(b.split("/").slice(0,-1).join("/"),
g))},B=function(b,n){null==n&&(n="/");var h=m(b);if(z.call(A,h))return A[h].exports;if(z.call(y,h))return b=y[h],n=g&&g.createHot(h),n={id:h,exports:{},hot:n},A[h]=n,b(n.exports,q(h),n),n.exports;throw Error("Cannot find module '"+b+"' from '"+n+"'");};B.alias=function(b,g){v[g]=b};var t=/\.[^.\/]+$/,D=/\/index(\.[^\/]+)?$/;B.register=B.define=function(b,g){if(b&&"object"===typeof b)for(var n in b)z.call(b,n)&&B.register(n,b[n]);else y[b]=g,delete A[b],t.test(b)&&(g=b.replace(t,""),z.call(v,g)&&v[g].replace(t,
"")!==g+"/index"||(v[g]=b)),D.test(b)&&(g=b.replace(D,""),z.call(v,g)||(v[g]=b))};B.list=function(){var b=[],g;for(g in y)z.call(y,g)&&b.push(g);return b};var g=f._hmr&&new f._hmr(x,B,y,A);B._cache=A;B.hmr=g&&g.wrap;B.brunch=!0;f.require=B}})();
(function(){var f="undefined"===typeof window?this:window,y=function(f,v,z){var M={},u=function(q,m){var x;try{return x=f(m+"/node_modules/"+q)}catch(B){if(-1===B.toString().indexOf("Cannot find module"))throw B;if(-1!==m.indexOf("node_modules"))return m=m.split("/"),x=m.lastIndexOf("node_modules"),m=m.slice(0,x).join("/"),u(q,m)}return M};return function(q){q in v&&(q=v[q]);if(q){if("."!==q[0]&&z){var m=u(q,z);if(m!==M)return m}return f(q)}}};require.register("@fdaciuk/ajax/dist/ajax.min.js",function(f,
v,z){v=y(v,{},"@fdaciuk/ajax");(function(){!function(M,u){"function"==typeof define&&define.amd?define("ajax",u):"object"==typeof f?f=z.exports=u():M.ajax=u()}(this,function(){function f(g,b,n,h){var l=["then","catch","always"].reduce(function(e,a){return e[a]=function(c){return e[a]=c,e},e},{}),p=new XMLHttpRequest;b=u(b,n,g);return p.open(g,b,!0),p.withCredentials=h.hasOwnProperty("withCredentials"),q(p,h.headers),p.addEventListener("readystatechange",x(l,p),!1),p.send(t(n)),l.abort=function(){return p.abort()},
l}function u(g,b,n){if("get"!==n.toLowerCase()||!b)return g;b=t(b);n=-1<g.indexOf("?")?"\x26":"?";return g+n+b}function q(g,b){b=b||{};m(b)||(b["Content-Type"]="application/x-www-form-urlencoded");Object.keys(b).forEach(function(n){b[n]&&g.setRequestHeader(n,b[n])})}function m(g){return Object.keys(g).some(function(b){return"content-type"===b.toLowerCase()})}function x(g,b){return function h(){b.readyState===b.DONE&&(b.removeEventListener("readystatechange",h,!1),g.always.apply(g,B(b)),200<=b.status&&
300>b.status?g.then.apply(g,B(b)):g["catch"].apply(g,B(b)))}}function B(g){try{var b=JSON.parse(g.responseText)}catch(n){b=g.responseText}return[b,g]}function t(g){return"[object Object]"===Object.prototype.toString.call(g)?D(g):g}function D(g){return Object.keys(g).reduce(function(b,n){return(b?b+"\x26":"")+encodeURIComponent(n)+"\x3d"+encodeURIComponent(g[n])},"")}return function(g){var b=["get","post","put","delete"];return g=g||{},g.baseUrl=g.baseUrl||"",g.method&&g.url?f(g.method,g.baseUrl+g.url,
g.data||null,g):b.reduce(function(b,h){return b[h]=function(b,p){return f(h,g.baseUrl+b,p||null,g)},b},{})}})})()});require.register("fuse.js/dist/fuse.js",function(f,v,z){v=y(v,{},"fuse.js");(function(){(function(M,u){"object"===typeof f&&"object"===typeof z?z.exports=u():"function"===typeof define&&define.amd?define("Fuse",[],u):"object"===typeof f?f.Fuse=u():M.Fuse=u()})(this,function(){return function(f){function u(m){if(q[m])return q[m].exports;var x=q[m]={i:m,l:!1,exports:{}};f[m].call(x.exports,
x,x.exports,u);x.l=!0;return x.exports}var q={};u.m=f;u.c=q;u.i=function(m){return m};u.d=function(m,x,f){u.o(m,x)||Object.defineProperty(m,x,{configurable:!1,enumerable:!0,get:f})};u.n=function(m){var x=m&&m.__esModule?function(){return m["default"]}:function(){return m};u.d(x,"a",x);return x};u.o=function(m,x){return Object.prototype.hasOwnProperty.call(m,x)};u.p="";return u(u.s=8)}([function(f,u,q){f.exports=function(m){return"[object Array]"===Object.prototype.toString.call(m)}},function(f,u,
q){var m=function(){function m(g,b){for(var n=0;n<b.length;n++){var h=b[n];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(g,h.key,h)}}return function(g,b,n){b&&m(g.prototype,b);n&&m(g,n);return g}}(),x=q(5),B=q(7),t=q(4);u=function(){function f(g,b){var n=b.location;n=void 0===n?0:n;var h=b.distance;h=void 0===h?100:h;var l=b.threshold;l=void 0===l?.6:l;var p=b.maxPatternLength;p=void 0===p?32:p;var e=b.isCaseSensitive;e=void 0===e?!1:e;var a=b.tokenSeparator;
a=void 0===a?/ +/g:a;var c=b.findAllMatches;c=void 0===c?!1:c;b=b.minMatchCharLength;b=void 0===b?1:b;if(!(this instanceof f))throw new TypeError("Cannot call a class as a function");this.options={location:n,distance:h,threshold:l,maxPatternLength:p,isCaseSensitive:e,tokenSeparator:a,findAllMatches:c,minMatchCharLength:b};this.pattern=this.options.isCaseSensitive?g:g.toLowerCase();this.pattern.length<=p&&(this.patternAlphabet=t(this.pattern))}m(f,[{key:"search",value:function(g){this.options.isCaseSensitive||
(g=g.toLowerCase());if(this.pattern===g)return{isMatch:!0,score:0,matchedIndices:[[0,g.length-1]]};var b=this.options,n=b.tokenSeparator;if(this.pattern.length>b.maxPatternLength)return x(g,this.pattern,n);b=this.options;return B(g,this.pattern,this.patternAlphabet,{location:b.location,distance:b.distance,threshold:b.threshold,findAllMatches:b.findAllMatches,minMatchCharLength:b.minMatchCharLength})}}]);return f}();f.exports=u},function(f,u,q){var m=q(0),x=function t(f,g,b){if(g){var n=g.indexOf("."),
h=g,l=null;-1!==n&&(h=g.slice(0,n),l=g.slice(n+1));f=f[h];if(null!==f&&void 0!==f)if(l||"string"!==typeof f&&"number"!==typeof f)if(m(f))for(g=0,n=f.length;g<n;g+=1)t(f[g],l,b);else l&&t(f,l,b);else b.push(f.toString())}else b.push(f);return b};f.exports=function(m,f){return x(m,f,[])}},function(f,u,q){f.exports=function(){for(var m=0<arguments.length&&void 0!==arguments[0]?arguments[0]:[],f=1<arguments.length&&void 0!==arguments[1]?arguments[1]:1,q=[],t=-1,u,g=0,b=m.length;g<b;g+=1)(u=m[g])&&-1===
t?t=g:u||-1===t||(u=g-1,u-t+1>=f&&q.push([t,u]),t=-1);m[g-1]&&g-t>=f&&q.push([t,g-1]);return q}},function(f,u,q){f.exports=function(f){for(var m={},q=f.length,t=0;t<q;t+=1)m[f.charAt(t)]=0;for(t=0;t<q;t+=1)m[f.charAt(t)]|=1<<q-t-1;return m}},function(f,u,q){var m=/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g;f.exports=function(f,q){var t=2<arguments.length&&void 0!==arguments[2]?arguments[2]:/ +/g;t=new RegExp(q.replace(m,"\\$\x26").replace(t,"|"));t=f.match(t);var x=!!t,g=[];if(x)for(var b=0,n=t.length;b<
n;b+=1){var h=t[b];g.push([f.indexOf(h),h.length-1])}return{score:x?.5:1,isMatch:x,matchedIndices:g}}},function(f,u,q){f.exports=function(f,q){var m=q.errors,t=q.currentLocation,u=q.expectedLocation;q=q.distance;q=void 0===q?100:q;f=(void 0===m?0:m)/f.length;t=Math.abs((void 0===u?0:u)-(void 0===t?0:t));return q?f+t/q:t?1:f}},function(f,u,q){var m=q(6),x=q(3);f.exports=function(f,q,u,g){var b=g.location,n=g.distance;n=void 0===n?100:n;var h=g.threshold,l=g.findAllMatches;l=void 0===l?!1:l;g=g.minMatchCharLength;
g=void 0===g?1:g;b=void 0===b?0:b;var p=f.length;h=void 0===h?.6:h;for(var e=f.indexOf(q,b),a=q.length,c=[],d=0;d<p;d+=1)c[d]=0;-1!==e&&(e=m(q,{errors:0,currentLocation:e,expectedLocation:b,distance:n}),h=Math.min(e,h),e=f.lastIndexOf(q,b+a),-1!==e&&(e=m(q,{errors:0,currentLocation:e,expectedLocation:b,distance:n}),h=Math.min(e,h)));e=-1;d=[];for(var k=1,K=a+p,w=1<<a-1,F=0;F<a;F+=1){for(var G=0,C=K;G<C;)m(q,{errors:F,currentLocation:b+C,expectedLocation:b,distance:n})<=h?G=C:K=C,C=Math.floor((K-G)/
2+G);K=C;G=Math.max(1,b-C+1);var L=l?p:Math.min(b+C,p)+a;C=Array(L+2);for(C[L+1]=(1<<F)-1;L>=G;--L){var O=L-1,t=u[f.charAt(O)];t&&(c[O]=1);C[L]=(C[L+1]<<1|1)&t;0!==F&&(C[L]=C[L]|(d[L+1]|d[L])<<1|1|d[L+1]);if(C[L]&w&&(k=m(q,{errors:F,currentLocation:O,expectedLocation:b,distance:n}),k<=h)){h=k;e=O;if(e<=b)break;G=Math.max(1,2*b-e)}}if(m(q,{errors:F+1,currentLocation:b,expectedLocation:b,distance:n})>h)break;d=C}return{isMatch:0<=e,score:0===k?.001:k,matchedIndices:x(c,g)}}},function(f,u,q){var m=function(){function f(g,
b){for(var n=0;n<b.length;n++){var h=b[n];h.enumerable=h.enumerable||!1;h.configurable=!0;"value"in h&&(h.writable=!0);Object.defineProperty(g,h.key,h)}}return function(g,b,n){b&&f(g.prototype,b);n&&f(g,n);return g}}(),x=q(1),v=q(2),t=q(0);u=function(){function f(g,b){var n=b.location;n=void 0===n?0:n;var h=b.distance;h=void 0===h?100:h;var l=b.threshold;l=void 0===l?.6:l;var p=b.maxPatternLength;p=void 0===p?32:p;var e=b.caseSensitive;e=void 0===e?!1:e;var a=b.tokenSeparator;a=void 0===a?/ +/g:a;
var c=b.findAllMatches;c=void 0===c?!1:c;var d=b.minMatchCharLength;d=void 0===d?1:d;var k=b.id;k=void 0===k?null:k;var K=b.keys;K=void 0===K?[]:K;var w=b.shouldSort;w=void 0===w?!0:w;var F=b.getFn;F=void 0===F?v:F;var G=b.sortFn;G=void 0===G?function(a,c){return a.score-c.score}:G;var C=b.tokenize;C=void 0===C?!1:C;var m=b.matchAllTokens;m=void 0===m?!1:m;var q=b.includeMatches;q=void 0===q?!1:q;var t=b.includeScore;t=void 0===t?!1:t;b=b.verbose;b=void 0===b?!1:b;if(!(this instanceof f))throw new TypeError("Cannot call a class as a function");
this.options={location:n,distance:h,threshold:l,maxPatternLength:p,isCaseSensitive:e,tokenSeparator:a,findAllMatches:c,minMatchCharLength:d,id:k,keys:K,includeMatches:q,includeScore:t,shouldSort:w,getFn:F,sortFn:G,verbose:b,tokenize:C,matchAllTokens:m};this.setCollection(g)}m(f,[{key:"setCollection",value:function(g){return this.list=g}},{key:"search",value:function(g){this._log('---------\nSearch pattern: "'+g+'"');g=this._prepareSearchers(g);g=this._search(g.tokenSearchers,g.fullSearcher);var b=
g.results;this._computeScore(g.weights,b);this.options.shouldSort&&this._sort(b);return this._format(b)}},{key:"_prepareSearchers",value:function(){var g=0<arguments.length&&void 0!==arguments[0]?arguments[0]:"",b=[];if(this.options.tokenize)for(var n=g.split(this.options.tokenSeparator),h=0,l=n.length;h<l;h+=1)b.push(new x(n[h],this.options));g=new x(g,this.options);return{tokenSearchers:b,fullSearcher:g}}},{key:"_search",value:function(){var g=0<arguments.length&&void 0!==arguments[0]?arguments[0]:
[],b=arguments[1],n=this.list,h={},l=[];if("string"===typeof n[0]){for(var p=0,e=n.length;p<e;p+=1)this._analyze({key:"",value:n[p],record:p,index:p},{resultMap:h,results:l,tokenSearchers:g,fullSearcher:b});return{weights:null,results:l}}p={};e=0;for(var a=n.length;e<a;e+=1)for(var c=n[e],d=0,k=this.options.keys.length;d<k;d+=1){var f=this.options.keys[d];if("string"!==typeof f){p[f.name]={weight:1-f.weight||1};if(0>=f.weight||1<f.weight)throw Error("Key weight has to be \x3e 0 and \x3c\x3d 1");f=
f.name}else p[f]={weight:1};this._analyze({key:f,value:this.options.getFn(c,f),record:c,index:e},{resultMap:h,results:l,tokenSearchers:g,fullSearcher:b})}return{weights:p,results:l}}},{key:"_analyze",value:function(g,b){var f=g.key,h=g.arrayIndex,l=void 0===h?-1:h;h=g.value;var p=g.record;g=g.index;var e=b.tokenSearchers;e=void 0===e?[]:e;var a=b.fullSearcher,c=void 0===a?[]:a;a=b.resultMap;a=void 0===a?{}:a;b=b.results;b=void 0===b?[]:b;if(void 0!==h&&null!==h){var d=!1,k=-1,K=0;if("string"===typeof h){this._log("\nKey: "+
(""===f?"-":f));c=c.search(h);this._log('Full text: "'+h+'", score: '+c.score);if(this.options.tokenize){k=h.split(this.options.tokenSeparator);for(var w=[],F=0;F<e.length;F+=1){var G=e[F];this._log('\nPattern: "'+G.pattern+'"');for(var C=!1,m=0;m<k.length;m+=1){var q=k[m],u=G.search(q),x={};u.isMatch?(x[q]=u.score,C=d=!0,w.push(u.score)):(x[q]=1,this.options.matchAllTokens||w.push(1));this._log('Token: "'+q+'", score: '+x[q])}C&&(K+=1)}k=w[0];F=w.length;for(G=1;G<F;G+=1)k+=w[G];k/=F;this._log("Token score average:",
k)}w=c.score;-1<k&&(w=(w+k)/2);this._log("Score average:",w);e=this.options.tokenize&&this.options.matchAllTokens?K>=e.length:!0;this._log("\nCheck Matches: "+e);(d||c.isMatch)&&e&&((e=a[g])?e.output.push({key:f,arrayIndex:l,value:h,score:w,matchedIndices:c.matchedIndices}):(a[g]={item:p,output:[{key:f,arrayIndex:l,value:h,score:w,matchedIndices:c.matchedIndices}]},b.push(a[g])))}else if(t(h))for(l=0,d=h.length;l<d;l+=1)this._analyze({key:f,arrayIndex:l,value:h[l],record:p,index:g},{resultMap:a,results:b,
tokenSearchers:e,fullSearcher:c})}}},{key:"_computeScore",value:function(g,b){this._log("\n\nComputing score:\n");for(var f=0,h=b.length;f<h;f+=1){for(var l=b[f].output,p=l.length,e=0,a=1,c=0;c<p;c+=1){var d=g?g[l[c].key].weight:1,k=(1===d?l[c].score:l[c].score||.001)*d;1!==d?a=Math.min(a,k):(l[c].nScore=k,e+=k)}b[f].score=1===a?e/p:a;this._log(b[f])}}},{key:"_sort",value:function(g){this._log("\n\nSorting....");g.sort(this.options.sortFn)}},{key:"_format",value:function(g){var b=[];this._log("\n\nOutput:\n\n",
JSON.stringify(g));var f=[];this.options.includeMatches&&f.push(function(a,c){a=a.output;c.matches=[];for(var d=0,k=a.length;d<k;d+=1){var e=a[d];if(0!==e.matchedIndices.length){var b={indices:e.matchedIndices,value:e.value};e.key&&(b.key=e.key);e.hasOwnProperty("arrayIndex")&&-1<e.arrayIndex&&(b.arrayIndex=e.arrayIndex);c.matches.push(b)}}});this.options.includeScore&&f.push(function(a,c){c.score=a.score});for(var h=0,l=g.length;h<l;h+=1){var p=g[h];this.options.id&&(p.item=this.options.getFn(p.item,
this.options.id)[0]);if(f.length){for(var e={item:p.item},a=0,c=f.length;a<c;a+=1)f[a](p,e);b.push(e)}else b.push(p.item)}return b}},{key:"_log",value:function(){if(this.options.verbose){var g;(g=console).log.apply(g,arguments)}}}]);return f}();f.exports=u}])})})()});require.register("hammerjs/hammer.js",function(f,v,z){v=y(v,{},"hammerjs");(function(){(function(f,u,q,m){function x(a,c,d){return setTimeout(b(a,d),c)}function v(a,c,d){return Array.isArray(a)?(t(a,d[c],d),!0):!1}function t(a,c,d){var r;
if(a)if(a.forEach)a.forEach(c,d);else if(a.length!==m)for(r=0;r<a.length;)c.call(d,a[r],r,a),r++;else for(r in a)a.hasOwnProperty(r)&&c.call(d,a[r],r,a)}function A(a,c,d){var r="DEPRECATED METHOD: "+c+"\n"+d+" AT \n";return function(){var c=Error("get-stack-trace");c=c&&c.stack?c.stack.replace(/^[^\(]+?[\n$]/gm,"").replace(/^\s+at\s+/gm,"").replace(/^Object.<anonymous>\s*\(/gm,"{anonymous}()@"):"Unknown Stack Trace";var d=f.console&&(f.console.warn||f.console.log);d&&d.call(f.console,r,c);return a.apply(this,
arguments)}}function g(a,c,d){c=c.prototype;var r=a.prototype=Object.create(c);r.constructor=a;r._super=c;d&&R(r,d)}function b(a,c){return function(){return a.apply(c,arguments)}}function n(a,c){return"function"==typeof a?a.apply(c?c[0]||m:m,c):a}function h(a,c,d){t(e(c),function(c){a.addEventListener(c,d,!1)})}function l(a,c,d){t(e(c),function(c){a.removeEventListener(c,d,!1)})}function p(a,c){for(;a;){if(a==c)return!0;a=a.parentNode}return!1}function e(a){return a.trim().split(/\s+/g)}function a(a,
c,d){if(a.indexOf&&!d)return a.indexOf(c);for(var r=0;r<a.length;){if(d&&a[r][d]==c||!d&&a[r]===c)return r;r++}return-1}function c(a){return Array.prototype.slice.call(a,0)}function d(c,d,k){for(var r=[],e=[],b=0;b<c.length;){var w=d?c[b][d]:c[b];0>a(e,w)&&r.push(c[b]);e[b]=w;b++}k&&(r=d?r.sort(function(a,c){return a[d]>c[d]}):r.sort());return r}function k(a,c){for(var r,d=c[0].toUpperCase()+c.slice(1),k=0;k<ka.length;){r=(r=ka[k])?r+d:c;if(r in a)return r;k++}return m}function K(a){a=a.ownerDocument||
a;return a.defaultView||a.parentWindow||f}function w(a,c){var r=this;this.manager=a;this.callback=c;this.element=a.element;this.target=a.options.inputTarget;this.domHandler=function(c){n(a.options.enable,[a])&&r.handler(c)};this.init()}function F(a){var c=a.options.inputClass;return new (c?c:va?ca:wa?E:la?H:V)(a,G)}function G(a,c,d){var r=d.pointers.length,k=d.changedPointers.length;var e=c&1&&0===r-k;d.isFirst=!!e;d.isFinal=!!(c&12&&0===r-k);e&&(a.session={});d.eventType=c;c=a.session;r=d.pointers;
k=r.length;c.firstInput||(c.firstInput=C(d));1<k&&!c.firstMultiple?c.firstMultiple=C(d):1===k&&(c.firstMultiple=!1);e=c.firstInput;var b=(k=c.firstMultiple)?k.center:e.center;var w=d.center=L(r);d.timeStamp=da();d.deltaTime=d.timeStamp-e.timeStamp;d.angle=ba(b,w);d.distance=U(b,w);e=d.center;b=c.offsetDelta||{};w=c.prevDelta||{};var g=c.prevInput||{};if(1===d.eventType||4===g.eventType)w=c.prevDelta={x:g.deltaX||0,y:g.deltaY||0},b=c.offsetDelta={x:e.x,y:e.y};d.deltaX=w.x+(e.x-b.x);d.deltaY=w.y+(e.y-
b.y);d.offsetDirection=O(d.deltaX,d.deltaY);b=d.deltaTime;e=d.deltaX/b||0;b=d.deltaY/b||0;d.overallVelocityX=e;d.overallVelocityY=b;d.overallVelocity=S(e)>S(b)?e:b;k?(e=k.pointers,e=U(r[0],r[1],W)/U(e[0],e[1],W)):e=1;d.scale=e;k?(k=k.pointers,r=ba(r[1],r[0],W)+ba(k[1],k[0],W)):r=0;d.rotation=r;d.maxPointers=c.prevInput?d.pointers.length>c.prevInput.maxPointers?d.pointers.length:c.prevInput.maxPointers:d.pointers.length;b=c.lastInterval||d;r=d.timeStamp-b.timeStamp;8!=d.eventType&&(25<r||b.velocity===
m)?(e=d.deltaX-b.deltaX,b=d.deltaY-b.deltaY,w=e/r||0,g=b/r||0,r=w,k=g,w=S(w)>S(g)?w:g,e=O(e,b),c.lastInterval=d):(w=b.velocity,r=b.velocityX,k=b.velocityY,e=b.direction);d.velocity=w;d.velocityX=r;d.velocityY=k;d.direction=e;c=a.element;p(d.srcEvent.target,c)&&(c=d.srcEvent.target);d.target=c;a.emit("hammer.input",d);a.recognize(d);a.session.prevInput=d}function C(a){for(var c=[],r=0;r<a.pointers.length;)c[r]={clientX:T(a.pointers[r].clientX),clientY:T(a.pointers[r].clientY)},r++;return{timeStamp:da(),
pointers:c,center:L(c),deltaX:a.deltaX,deltaY:a.deltaY}}function L(a){var c=a.length;if(1===c)return{x:T(a[0].clientX),y:T(a[0].clientY)};for(var r=0,d=0,k=0;k<c;)r+=a[k].clientX,d+=a[k].clientY,k++;return{x:T(r/c),y:T(d/c)}}function O(a,c){return a===c?1:S(a)>=S(c)?0>a?2:4:0>c?8:16}function U(a,c,d){d||(d=ma);var r=c[d[0]]-a[d[0]];a=c[d[1]]-a[d[1]];return Math.sqrt(r*r+a*a)}function ba(a,c,d){d||(d=ma);return 180*Math.atan2(c[d[1]]-a[d[1]],c[d[0]]-a[d[0]])/Math.PI}function V(){this.evEl=xa;this.evWin=
ya;this.pressed=!1;w.apply(this,arguments)}function ca(){this.evEl=na;this.evWin=oa;w.apply(this,arguments);this.store=this.manager.session.pointerEvents=[]}function I(){this.evTarget="touchstart";this.evWin="touchstart touchmove touchend touchcancel";this.started=!1;w.apply(this,arguments)}function E(){this.evTarget=za;this.targetIds={};w.apply(this,arguments)}function y(a,k){var r=c(a.touches),e=this.targetIds;if(k&3&&1===r.length)return e[r[0].identifier]=!0,[r,r];a=c(a.changedTouches);var b=[],
w=this.target;var g=r.filter(function(a){return p(a.target,w)});if(1===k)for(r=0;r<g.length;)e[g[r].identifier]=!0,r++;for(r=0;r<a.length;)e[a[r].identifier]&&b.push(a[r]),k&12&&delete e[a[r].identifier],r++;if(b.length)return[d(g.concat(b),"identifier",!0),b]}function H(){w.apply(this,arguments);var a=b(this.handler,this);this.touch=new E(this.manager,a);this.mouse=new V(this.manager,a);this.primaryTouch=null;this.lastTouches=[]}function J(a){a=a.changedPointers[0];if(a.identifier===this.primaryTouch){var c=
{x:a.clientX,y:a.clientY};this.lastTouches.push(c);var d=this.lastTouches;setTimeout(function(){var a=d.indexOf(c);-1<a&&d.splice(a,1)},2500)}}function M(a,c){this.manager=a;this.set(c)}function Aa(a){if(-1<a.indexOf("none"))return"none";var c=-1<a.indexOf("pan-x"),d=-1<a.indexOf("pan-y");return c&&d?"none":c||d?c?"pan-x":"pan-y":-1<a.indexOf("manipulation")?"manipulation":"auto"}function P(a){this.options=R({},this.defaults,a||{});this.id=Ba++;this.manager=null;a=this.options.enable;this.options.enable=
a===m?!0:a;this.state=1;this.simultaneous={};this.requireFail=[]}function pa(a){return a&16?"cancel":a&8?"end":a&4?"move":a&2?"start":""}function qa(a){return 16==a?"down":8==a?"up":2==a?"left":4==a?"right":""}function X(a,c){return(c=c.manager)?c.get(a):a}function N(){P.apply(this,arguments)}function Y(){N.apply(this,arguments);this.pY=this.pX=null}function ea(){N.apply(this,arguments)}function fa(){P.apply(this,arguments);this._input=this._timer=null}function ha(){N.apply(this,arguments)}function ia(){N.apply(this,
arguments)}function Z(){P.apply(this,arguments);this.pCenter=this.pTime=!1;this._input=this._timer=null;this.count=0}function Q(a,c){c=c||{};var d=c.recognizers;c.recognizers=d===m?Q.defaults.preset:d;return new ja(a,c)}function ja(a,c){this.options=R({},Q.defaults,c||{});this.options.inputTarget=this.options.inputTarget||a;this.handlers={};this.session={};this.recognizers=[];this.oldCssProps={};this.element=a;this.input=F(this);this.touchAction=new M(this,this.options.touchAction);ra(this,!0);t(this.options.recognizers,
function(a){var c=this.add(new a[0](a[1]));a[2]&&c.recognizeWith(a[2]);a[3]&&c.requireFailure(a[3])},this)}function ra(a,c){var d=a.element;if(d.style){var r;t(a.options.cssProps,function(e,b){r=k(d.style,b);c?(a.oldCssProps[r]=d.style[r],d.style[r]=e):d.style[r]=a.oldCssProps[r]||""});c||(a.oldCssProps={})}}function Ca(a,c){var d=u.createEvent("Event");d.initEvent(a,!0,!0);d.gesture=c;c.target.dispatchEvent(d)}var ka=" webkit Moz MS ms o".split(" "),Da=u.createElement("div"),T=Math.round,S=Math.abs,
da=Date.now;var R="function"!==typeof Object.assign?function(a){if(a===m||null===a)throw new TypeError("Cannot convert undefined or null to object");for(var c=Object(a),d=1;d<arguments.length;d++){var r=arguments[d];if(r!==m&&null!==r)for(var k in r)r.hasOwnProperty(k)&&(c[k]=r[k])}return c}:Object.assign;var sa=A(function(a,c,d){for(var r=Object.keys(c),k=0;k<r.length;){if(!d||d&&a[r[k]]===m)a[r[k]]=c[r[k]];k++}return a},"extend","Use `assign`."),Ea=A(function(a,c){return sa(a,c,!0)},"merge","Use `assign`."),
Ba=1,Fa=/mobile|tablet|ip(ad|hone|od)|android/i,la="ontouchstart"in f,va=k(f,"PointerEvent")!==m,wa=la&&Fa.test(navigator.userAgent),ma=["x","y"],W=["clientX","clientY"];w.prototype={handler:function(){},init:function(){this.evEl&&h(this.element,this.evEl,this.domHandler);this.evTarget&&h(this.target,this.evTarget,this.domHandler);this.evWin&&h(K(this.element),this.evWin,this.domHandler)},destroy:function(){this.evEl&&l(this.element,this.evEl,this.domHandler);this.evTarget&&l(this.target,this.evTarget,
this.domHandler);this.evWin&&l(K(this.element),this.evWin,this.domHandler)}};var Ga={mousedown:1,mousemove:2,mouseup:4},xa="mousedown",ya="mousemove mouseup";g(V,w,{handler:function(a){var c=Ga[a.type];c&1&&0===a.button&&(this.pressed=!0);c&2&&1!==a.which&&(c=4);this.pressed&&(c&4&&(this.pressed=!1),this.callback(this.manager,c,{pointers:[a],changedPointers:[a],pointerType:"mouse",srcEvent:a}))}});var Ha={pointerdown:1,pointermove:2,pointerup:4,pointercancel:8,pointerout:8},Ia={2:"touch",3:"pen",
4:"mouse",5:"kinect"},na="pointerdown",oa="pointermove pointerup pointercancel";f.MSPointerEvent&&!f.PointerEvent&&(na="MSPointerDown",oa="MSPointerMove MSPointerUp MSPointerCancel");g(ca,w,{handler:function(c){var d=this.store,r=!1,k=c.type.toLowerCase().replace("ms","");k=Ha[k];var e=Ia[c.pointerType]||c.pointerType,b="touch"==e,w=a(d,c.pointerId,"pointerId");k&1&&(0===c.button||b)?0>w&&(d.push(c),w=d.length-1):k&12&&(r=!0);0>w||(d[w]=c,this.callback(this.manager,k,{pointers:d,changedPointers:[c],
pointerType:e,srcEvent:c}),r&&d.splice(w,1))}});var Ja={touchstart:1,touchmove:2,touchend:4,touchcancel:8};g(I,w,{handler:function(a){var k=Ja[a.type];1===k&&(this.started=!0);if(this.started){var r=c(a.touches);var e=c(a.changedTouches);k&12&&(r=d(r.concat(e),"identifier",!0));r=[r,e];k&12&&0===r[0].length-r[1].length&&(this.started=!1);this.callback(this.manager,k,{pointers:r[0],changedPointers:r[1],pointerType:"touch",srcEvent:a})}}});var Ka={touchstart:1,touchmove:2,touchend:4,touchcancel:8},
za="touchstart touchmove touchend touchcancel";g(E,w,{handler:function(a){var c=Ka[a.type],d=y.call(this,a,c);d&&this.callback(this.manager,c,{pointers:d[0],changedPointers:d[1],pointerType:"touch",srcEvent:a})}});g(H,w,{handler:function(a,c,d){var k="mouse"==d.pointerType;if(!(k&&d.sourceCapabilities&&d.sourceCapabilities.firesTouchEvents)){if("touch"==d.pointerType)c&1?(this.primaryTouch=d.changedPointers[0].identifier,J.call(this,d)):c&12&&J.call(this,d);else{if(k)a:{k=d.srcEvent.clientX;for(var r=
d.srcEvent.clientY,e=0;e<this.lastTouches.length;e++){var b=this.lastTouches[e],w=Math.abs(r-b.y);if(25>=Math.abs(k-b.x)&&25>=w){k=!0;break a}}k=!1}if(k)return}this.callback(a,c,d)}},destroy:function(){this.touch.destroy();this.mouse.destroy()}});var ta=k(Da.style,"touchAction"),ua=ta!==m,aa=function(){if(!ua)return!1;var a={},c=f.CSS&&f.CSS.supports;"auto;manipulation;pan-y;pan-x;pan-x pan-y;none".split(";").forEach(function(d){a[d]=c?f.CSS.supports("touch-action",d):!0});return a}();M.prototype=
{set:function(a){"compute"==a&&(a=this.compute());ua&&this.manager.element.style&&aa[a]&&(this.manager.element.style[ta]=a);this.actions=a.toLowerCase().trim()},update:function(){this.set(this.manager.options.touchAction)},compute:function(){var a=[];t(this.manager.recognizers,function(c){n(c.options.enable,[c])&&(a=a.concat(c.getTouchAction()))});return Aa(a.join(" "))},preventDefaults:function(a){var c=a.srcEvent,d=a.offsetDirection;if(this.manager.session.prevented)c.preventDefault();else{var k=
this.actions,e=-1<k.indexOf("none")&&!aa.none,r=-1<k.indexOf("pan-y")&&!aa["pan-y"];k=-1<k.indexOf("pan-x")&&!aa["pan-x"];if(e){var b=2>a.distance,w=250>a.deltaTime;if(1===a.pointers.length&&b&&w)return}if(!k||!r)if(e||r&&d&6||k&&d&24)return this.preventSrc(c)}},preventSrc:function(a){this.manager.session.prevented=!0;a.preventDefault()}};P.prototype={defaults:{},set:function(a){R(this.options,a);this.manager&&this.manager.touchAction.update();return this},recognizeWith:function(a){if(v(a,"recognizeWith",
this))return this;var c=this.simultaneous;a=X(a,this);c[a.id]||(c[a.id]=a,a.recognizeWith(this));return this},dropRecognizeWith:function(a){if(v(a,"dropRecognizeWith",this))return this;a=X(a,this);delete this.simultaneous[a.id];return this},requireFailure:function(c){if(v(c,"requireFailure",this))return this;var d=this.requireFail;c=X(c,this);-1===a(d,c)&&(d.push(c),c.requireFailure(this));return this},dropRequireFailure:function(c){if(v(c,"dropRequireFailure",this))return this;c=X(c,this);c=a(this.requireFail,
c);-1<c&&this.requireFail.splice(c,1);return this},hasRequireFailures:function(){return 0<this.requireFail.length},canRecognizeWith:function(a){return!!this.simultaneous[a.id]},emit:function(a){function c(c){d.manager.emit(c,a)}var d=this,k=this.state;8>k&&c(d.options.event+pa(k));c(d.options.event);a.additionalEvent&&c(a.additionalEvent);8<=k&&c(d.options.event+pa(k))},tryEmit:function(a){if(this.canEmit())return this.emit(a);this.state=32},canEmit:function(){for(var a=0;a<this.requireFail.length;){if(!(this.requireFail[a].state&
33))return!1;a++}return!0},recognize:function(a){a=R({},a);n(this.options.enable,[this,a])?(this.state&56&&(this.state=1),this.state=this.process(a),this.state&30&&this.tryEmit(a)):(this.reset(),this.state=32)},process:function(a){},getTouchAction:function(){},reset:function(){}};g(N,P,{defaults:{pointers:1},attrTest:function(a){var c=this.options.pointers;return 0===c||a.pointers.length===c},process:function(a){var c=this.state,d=a.eventType,k=c&6;a=this.attrTest(a);return k&&(d&8||!a)?c|16:k||a?
d&4?c|8:c&2?c|4:2:32}});g(Y,N,{defaults:{event:"pan",threshold:10,pointers:1,direction:30},getTouchAction:function(){var a=this.options.direction,c=[];a&6&&c.push("pan-y");a&24&&c.push("pan-x");return c},directionTest:function(a){var c=this.options,d=!0,k=a.distance,e=a.direction,b=a.deltaX,w=a.deltaY;e&c.direction||(c.direction&6?(e=0===b?1:0>b?2:4,d=b!=this.pX,k=Math.abs(a.deltaX)):(e=0===w?1:0>w?8:16,d=w!=this.pY,k=Math.abs(a.deltaY)));a.direction=e;return d&&k>c.threshold&&e&c.direction},attrTest:function(a){return N.prototype.attrTest.call(this,
a)&&(this.state&2||!(this.state&2)&&this.directionTest(a))},emit:function(a){this.pX=a.deltaX;this.pY=a.deltaY;var c=qa(a.direction);c&&(a.additionalEvent=this.options.event+c);this._super.emit.call(this,a)}});g(ea,N,{defaults:{event:"pinch",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.scale-1)>this.options.threshold||this.state&2)},emit:function(a){1!==a.scale&&(a.additionalEvent=this.options.event+(1>
a.scale?"in":"out"));this._super.emit.call(this,a)}});g(fa,P,{defaults:{event:"press",pointers:1,time:251,threshold:9},getTouchAction:function(){return["auto"]},process:function(a){var c=this.options,d=a.pointers.length===c.pointers,k=a.distance<c.threshold,e=a.deltaTime>c.time;this._input=a;if(!k||!d||a.eventType&12&&!e)this.reset();else if(a.eventType&1)this.reset(),this._timer=x(function(){this.state=8;this.tryEmit()},c.time,this);else if(a.eventType&4)return 8;return 32},reset:function(){clearTimeout(this._timer)},
emit:function(a){8===this.state&&(a&&a.eventType&4?this.manager.emit(this.options.event+"up",a):(this._input.timeStamp=da(),this.manager.emit(this.options.event,this._input)))}});g(ha,N,{defaults:{event:"rotate",threshold:0,pointers:2},getTouchAction:function(){return["none"]},attrTest:function(a){return this._super.attrTest.call(this,a)&&(Math.abs(a.rotation)>this.options.threshold||this.state&2)}});g(ia,N,{defaults:{event:"swipe",threshold:10,velocity:.3,direction:30,pointers:1},getTouchAction:function(){return Y.prototype.getTouchAction.call(this)},
attrTest:function(a){var c=this.options.direction;if(c&30)var d=a.overallVelocity;else c&6?d=a.overallVelocityX:c&24&&(d=a.overallVelocityY);return this._super.attrTest.call(this,a)&&c&a.offsetDirection&&a.distance>this.options.threshold&&a.maxPointers==this.options.pointers&&S(d)>this.options.velocity&&a.eventType&4},emit:function(a){var c=qa(a.offsetDirection);c&&this.manager.emit(this.options.event+c,a);this.manager.emit(this.options.event,a)}});g(Z,P,{defaults:{event:"tap",pointers:1,taps:1,interval:300,
time:250,threshold:9,posThreshold:10},getTouchAction:function(){return["manipulation"]},process:function(a){var c=this.options,d=a.pointers.length===c.pointers,k=a.distance<c.threshold,e=a.deltaTime<c.time;this.reset();if(a.eventType&1&&0===this.count)return this.failTimeout();if(k&&e&&d){if(4!=a.eventType)return this.failTimeout();d=this.pTime?a.timeStamp-this.pTime<c.interval:!0;k=!this.pCenter||U(this.pCenter,a.center)<c.posThreshold;this.pTime=a.timeStamp;this.pCenter=a.center;this.count=k&&d?
this.count+1:1;this._input=a;if(0===this.count%c.taps)return this.hasRequireFailures()?(this._timer=x(function(){this.state=8;this.tryEmit()},c.interval,this),2):8}return 32},failTimeout:function(){this._timer=x(function(){this.state=32},this.options.interval,this);return 32},reset:function(){clearTimeout(this._timer)},emit:function(){8==this.state&&(this._input.tapCount=this.count,this.manager.emit(this.options.event,this._input))}});Q.VERSION="2.0.7";Q.defaults={domEvents:!1,touchAction:"compute",
enable:!0,inputTarget:null,inputClass:null,preset:[[ha,{enable:!1}],[ea,{enable:!1},["rotate"]],[ia,{direction:6}],[Y,{direction:6},["swipe"]],[Z],[Z,{event:"doubletap",taps:2},["tap"]],[fa]],cssProps:{userSelect:"none",touchSelect:"none",touchCallout:"none",contentZooming:"none",userDrag:"none",tapHighlightColor:"rgba(0,0,0,0)"}};ja.prototype={set:function(a){R(this.options,a);a.touchAction&&this.touchAction.update();a.inputTarget&&(this.input.destroy(),this.input.target=a.inputTarget,this.input.init());
return this},stop:function(a){this.session.stopped=a?2:1},recognize:function(a){var c=this.session;if(!c.stopped){this.touchAction.preventDefaults(a);var d=this.recognizers,k=c.curRecognizer;if(!k||k&&k.state&8)k=c.curRecognizer=null;for(var e=0;e<d.length;){var b=d[e];2===c.stopped||k&&b!=k&&!b.canRecognizeWith(k)?b.reset():b.recognize(a);!k&&b.state&14&&(k=c.curRecognizer=b);e++}}},get:function(a){if(a instanceof P)return a;for(var c=this.recognizers,d=0;d<c.length;d++)if(c[d].options.event==a)return c[d];
return null},add:function(a){if(v(a,"add",this))return this;var c=this.get(a.options.event);c&&this.remove(c);this.recognizers.push(a);a.manager=this;this.touchAction.update();return a},remove:function(c){if(v(c,"remove",this))return this;if(c=this.get(c)){var d=this.recognizers;c=a(d,c);-1!==c&&(d.splice(c,1),this.touchAction.update())}return this},on:function(a,c){if(a!==m&&c!==m){var d=this.handlers;t(e(a),function(a){d[a]=d[a]||[];d[a].push(c)});return this}},off:function(c,d){if(c!==m){var k=
this.handlers;t(e(c),function(c){d?k[c]&&k[c].splice(a(k[c],d),1):delete k[c]});return this}},emit:function(a,c){this.options.domEvents&&Ca(a,c);var d=this.handlers[a]&&this.handlers[a].slice();if(d&&d.length)for(c.type=a,c.preventDefault=function(){c.srcEvent.preventDefault()},a=0;a<d.length;)d[a](c),a++},destroy:function(){this.element&&ra(this,!1);this.handlers={};this.session={};this.input.destroy();this.element=null}};R(Q,{INPUT_START:1,INPUT_MOVE:2,INPUT_END:4,INPUT_CANCEL:8,STATE_POSSIBLE:1,
STATE_BEGAN:2,STATE_CHANGED:4,STATE_ENDED:8,STATE_RECOGNIZED:8,STATE_CANCELLED:16,STATE_FAILED:32,DIRECTION_NONE:1,DIRECTION_LEFT:2,DIRECTION_RIGHT:4,DIRECTION_UP:8,DIRECTION_DOWN:16,DIRECTION_HORIZONTAL:6,DIRECTION_VERTICAL:24,DIRECTION_ALL:30,Manager:ja,Input:w,TouchAction:M,TouchInput:E,MouseInput:V,PointerEventInput:ca,TouchMouseInput:H,SingleTouchInput:I,Recognizer:P,AttrRecognizer:N,Tap:Z,Pan:Y,Swipe:ia,Pinch:ea,Rotate:ha,Press:fa,on:h,off:l,each:t,merge:Ea,extend:sa,assign:R,inherit:g,bindFn:b,
prefixed:k});("undefined"!==typeof f?f:"undefined"!==typeof self?self:{}).Hammer=Q;"function"===typeof define&&define.amd?define(function(){return Q}):"undefined"!=typeof z&&z.exports?z.exports=Q:f[q]=Q})(window,document,"Hammer")})()});require.register("marked/lib/marked.js",function(A,v,z){v=y(v,{},"marked");(function(){(function(){function f(a){this.tokens=[];this.tokens.links={};this.options=a||n.defaults;this.rules=h.normal;this.options.gfm&&(this.rules=this.options.tables?h.tables:h.gfm)}function u(a,
c){this.options=c||n.defaults;this.links=a;this.rules=l.normal;this.renderer=this.options.renderer||new q;this.renderer.options=this.options;if(!this.links)throw Error("Tokens array requires a `links` property.");this.options.gfm?this.rules=this.options.breaks?l.breaks:l.gfm:this.options.pedantic&&(this.rules=l.pedantic)}function q(a){this.options=a||{}}function m(a){this.tokens=[];this.token=null;this.options=a||n.defaults;this.options.renderer=this.options.renderer||new q;this.renderer=this.options.renderer;
this.renderer.options=this.options}function x(a,c){return a.replace(c?/&/g:/&(?!#?\w+;)/g,"\x26amp;").replace(/</g,"\x26lt;").replace(/>/g,"\x26gt;").replace(/"/g,"\x26quot;").replace(/'/g,"\x26#39;")}function v(a){return a.replace(/&(#(?:\d+)|(?:#x[0-9A-Fa-f]+)|(?:\w+));?/ig,function(a,d){d=d.toLowerCase();return"colon"===d?":":"#"===d.charAt(0)?"x"===d.charAt(1)?String.fromCharCode(parseInt(d.substring(2),16)):String.fromCharCode(+d.substring(1)):""})}function t(a,c){a=a.source;c=c||"";return function k(e,
b){if(!e)return new RegExp(a,c);b=b.source||b;b=b.replace(/(^|[^\[])\^/g,"$1");a=a.replace(e,b);return k}}function y(a,c){p[" "+a]||(/^[^:]+:\/*[^/]*$/.test(a)?p[" "+a]=a+"/":p[" "+a]=a.replace(/[^/]*$/,""));a=p[" "+a];return"//"===c.slice(0,2)?a.replace(/:[\s\S]*/,":")+c:"/"===c.charAt(0)?a.replace(/(:\/*[^/]*)[\s\S]*/,"$1")+c:a+c}function g(){}function b(a){for(var c=1,d,k;c<arguments.length;c++)for(k in d=arguments[c],d)Object.prototype.hasOwnProperty.call(d,k)&&(a[k]=d[k]);return a}function n(a,
c,d){if(d||"function"===typeof c){d||(d=c,c=null);c=b({},n.defaults,c||{});var k=c.highlight,e=0;try{var w=f.lex(a,c)}catch(C){return d(C)}var g=w.length;var p=function(a){if(a)return c.highlight=k,d(a);try{var e=m.parse(w,c)}catch(O){a=O}c.highlight=k;return a?d(a):d(null,e)};if(!k||3>k.length)return p();delete c.highlight;if(!g)return p();for(;e<w.length;e++)(function(a){return"code"!==a.type?--g||p():k(a.text,a.lang,function(c,d){if(c)return p(c);if(null==d||d===a.text)return--g||p();a.text=d;
a.escaped=!0;--g||p()})})(w[e])}else try{return c&&(c=b({},n.defaults,c)),m.parse(f.lex(a,c),c)}catch(C){C.message+="\nPlease report this to https://github.com/chjj/marked.";if((c||n.defaults).silent)return"\x3cp\x3eAn error occurred:\x3c/p\x3e\x3cpre\x3e"+x(C.message+"",!0)+"\x3c/pre\x3e";throw C;}}var h={newline:/^\n+/,code:/^( {4}[^\n]+\n*)+/,fences:g,hr:/^( *[-*_]){3,} *(?:\n+|$)/,heading:/^ *(#{1,6}) *([^\n]+?) *#* *(?:\n+|$)/,nptable:g,lheading:/^([^\n]+)\n *(=|-){2,} *(?:\n+|$)/,blockquote:/^( *>[^\n]+(\n(?!def)[^\n]+)*\n*)+/,
list:/^( *)(bull) [\s\S]+?(?:hr|def|\n{2,}(?! )(?!\1bull )\n*|\s*$)/,html:/^ *(?:comment *(?:\n|\s*$)|closed *(?:\n{2,}|\s*$)|closing *(?:\n{2,}|\s*$))/,def:/^ *\[([^\]]+)\]: *<?([^\s>]+)>?(?: +["(]([^\n]+)[")])? *(?:\n+|$)/,table:g,paragraph:/^((?:[^\n]+\n?(?!hr|heading|lheading|blockquote|tag|def))+)\n*/,text:/^[^\n]+/,bullet:/(?:[*+-]|\d+\.)/,item:/^( *)(bull) [^\n]*(?:\n(?!\1bull )[^\n]*)*/};h.item=t(h.item,"gm")(/bull/g,h.bullet)();h.list=t(h.list)(/bull/g,h.bullet)("hr","\\n+(?\x3d\\1?(?:[-*_] *){3,}(?:\\n+|$))")("def",
"\\n+(?\x3d"+h.def.source+")")();h.blockquote=t(h.blockquote)("def",h.def)();h._tag="(?!(?:a|em|strong|small|s|cite|q|dfn|abbr|data|time|code|var|samp|kbd|sub|sup|i|b|u|mark|ruby|rt|rp|bdi|bdo|span|br|wbr|ins|del|img)\\b)\\w+(?!:/|[^\\w\\s@]*@)\\b";h.html=t(h.html)("comment",/\x3c!--[\s\S]*?--\x3e/)("closed",/<(tag)[\s\S]+?<\/\1>/)("closing",/<tag(?:"[^"]*"|'[^']*'|[^'">])*?>/)(/tag/g,h._tag)();h.paragraph=t(h.paragraph)("hr",h.hr)("heading",h.heading)("lheading",h.lheading)("blockquote",h.blockquote)("tag",
"\x3c"+h._tag)("def",h.def)();h.normal=b({},h);h.gfm=b({},h.normal,{fences:/^ *(`{3,}|~{3,})[ \.]*(\S+)? *\n([\s\S]*?)\s*\1 *(?:\n+|$)/,paragraph:/^/,heading:/^ *(#{1,6}) +([^\n]+?) *#* *(?:\n+|$)/});h.gfm.paragraph=t(h.paragraph)("(?!","(?!"+h.gfm.fences.source.replace("\\1","\\2")+"|"+h.list.source.replace("\\1","\\3")+"|")();h.tables=b({},h.gfm,{nptable:/^ *(\S.*\|.*)\n *([-:]+ *\|[-| :]*)\n((?:.*\|.*(?:\n|$))*)\n*/,table:/^ *\|(.+)\n *\|( *[-:]+[-| :]*)\n((?: *\|.*(?:\n|$))*)\n*/});f.rules=h;
f.lex=function(a,c){return(new f(c)).lex(a)};f.prototype.lex=function(a){a=a.replace(/\r\n|\r/g,"\n").replace(/\t/g,"    ").replace(/\u00a0/g," ").replace(/\u2424/g,"\n");return this.token(a,!0)};f.prototype.token=function(a,c,d){a=a.replace(/^ +$/gm,"");for(var k,e,b,g,f,p,l;a;){if(b=this.rules.newline.exec(a))a=a.substring(b[0].length),1<b[0].length&&this.tokens.push({type:"space"});if(b=this.rules.code.exec(a))a=a.substring(b[0].length),b=b[0].replace(/^ {4}/gm,""),this.tokens.push({type:"code",
text:this.options.pedantic?b:b.replace(/\n+$/,"")});else if(b=this.rules.fences.exec(a))a=a.substring(b[0].length),this.tokens.push({type:"code",lang:b[2],text:b[3]||""});else if(b=this.rules.heading.exec(a))a=a.substring(b[0].length),this.tokens.push({type:"heading",depth:b[1].length,text:b[2]});else if(c&&(b=this.rules.nptable.exec(a))){a=a.substring(b[0].length);f={type:"table",header:b[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:b[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:b[3].replace(/\n$/,
"").split("\n")};for(p=0;p<f.align.length;p++)/^ *-+: *$/.test(f.align[p])?f.align[p]="right":/^ *:-+: *$/.test(f.align[p])?f.align[p]="center":/^ *:-+ *$/.test(f.align[p])?f.align[p]="left":f.align[p]=null;for(p=0;p<f.cells.length;p++)f.cells[p]=f.cells[p].split(/ *\| */);this.tokens.push(f)}else if(b=this.rules.lheading.exec(a))a=a.substring(b[0].length),this.tokens.push({type:"heading",depth:"\x3d"===b[2]?1:2,text:b[1]});else if(b=this.rules.hr.exec(a))a=a.substring(b[0].length),this.tokens.push({type:"hr"});
else if(b=this.rules.blockquote.exec(a))a=a.substring(b[0].length),this.tokens.push({type:"blockquote_start"}),b=b[0].replace(/^ *> ?/gm,""),this.token(b,c,!0),this.tokens.push({type:"blockquote_end"});else if(b=this.rules.list.exec(a)){a=a.substring(b[0].length);g=b[2];this.tokens.push({type:"list_start",ordered:1<g.length});b=b[0].match(this.rules.item);k=!1;l=b.length;for(p=0;p<l;p++)f=b[p],e=f.length,f=f.replace(/^ *([*+-]|\d+\.) +/,""),~f.indexOf("\n ")&&(e-=f.length,f=this.options.pedantic?
f.replace(/^ {1,4}/gm,""):f.replace(new RegExp("^ {1,"+e+"}","gm"),"")),this.options.smartLists&&p!==l-1&&(e=h.bullet.exec(b[p+1])[0],g===e||1<g.length&&1<e.length||(a=b.slice(p+1).join("\n")+a,p=l-1)),e=k||/\n\n(?!\s*$)/.test(f),p!==l-1&&(k="\n"===f.charAt(f.length-1),e||(e=k)),this.tokens.push({type:e?"loose_item_start":"list_item_start"}),this.token(f,!1,d),this.tokens.push({type:"list_item_end"});this.tokens.push({type:"list_end"})}else if(b=this.rules.html.exec(a))a=a.substring(b[0].length),
this.tokens.push({type:this.options.sanitize?"paragraph":"html",pre:!this.options.sanitizer&&("pre"===b[1]||"script"===b[1]||"style"===b[1]),text:b[0]});else if(!d&&c&&(b=this.rules.def.exec(a)))a=a.substring(b[0].length),this.tokens.links[b[1].toLowerCase()]={href:b[2],title:b[3]};else if(c&&(b=this.rules.table.exec(a))){a=a.substring(b[0].length);f={type:"table",header:b[1].replace(/^ *| *\| *$/g,"").split(/ *\| */),align:b[2].replace(/^ *|\| *$/g,"").split(/ *\| */),cells:b[3].replace(/(?: *\| *)?\n$/,
"").split("\n")};for(p=0;p<f.align.length;p++)/^ *-+: *$/.test(f.align[p])?f.align[p]="right":/^ *:-+: *$/.test(f.align[p])?f.align[p]="center":/^ *:-+ *$/.test(f.align[p])?f.align[p]="left":f.align[p]=null;for(p=0;p<f.cells.length;p++)f.cells[p]=f.cells[p].replace(/^ *\| *| *\| *$/g,"").split(/ *\| */);this.tokens.push(f)}else if(c&&(b=this.rules.paragraph.exec(a)))a=a.substring(b[0].length),this.tokens.push({type:"paragraph",text:"\n"===b[1].charAt(b[1].length-1)?b[1].slice(0,-1):b[1]});else if(b=
this.rules.text.exec(a))a=a.substring(b[0].length),this.tokens.push({type:"text",text:b[0]});else if(a)throw Error("Infinite loop on byte: "+a.charCodeAt(0));}return this.tokens};var l={escape:/^\\([\\`*{}\[\]()#+\-.!_>])/,autolink:/^<([^ <>]+(@|:\/)[^ <>]+)>/,url:g,tag:/^\x3c!--[\s\S]*?--\x3e|^<\/?\w+(?:"[^"]*"|'[^']*'|[^<'">])*?>/,link:/^!?\[(inside)\]\(href\)/,reflink:/^!?\[(inside)\]\s*\[([^\]]*)\]/,nolink:/^!?\[((?:\[[^\]]*\]|[^\[\]])*)\]/,strong:/^__([\s\S]+?)__(?!_)|^\*\*([\s\S]+?)\*\*(?!\*)/,
em:/^\b_((?:[^_]|__)+?)_\b|^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,code:/^(`+)([\s\S]*?[^`])\1(?!`)/,br:/^ {2,}\n(?!\s*$)/,del:g,text:/^[\s\S]+?(?=[\\<!\[_*`]| {2,}\n|$)/,_inside:/(?:\[[^\]]*\]|\\[\[\]]|[^\[\]]|\](?=[^\[]*\]))*/,_href:/\s*<?([\s\S]*?)>?(?:\s+['"]([\s\S]*?)['"])?\s*/};l.link=t(l.link)("inside",l._inside)("href",l._href)();l.reflink=t(l.reflink)("inside",l._inside)();l.normal=b({},l);l.pedantic=b({},l.normal,{strong:/^__(?=\S)([\s\S]*?\S)__(?!_)|^\*\*(?=\S)([\s\S]*?\S)\*\*(?!\*)/,em:/^_(?=\S)([\s\S]*?\S)_(?!_)|^\*(?=\S)([\s\S]*?\S)\*(?!\*)/});
l.gfm=b({},l.normal,{escape:t(l.escape)("])","~|])")(),url:/^(https?:\/\/[^\s<]+[^<.,:;"')\]\s])/,del:/^~~(?=\S)([\s\S]*?\S)~~/,text:t(l.text)("]|","~]|")("|","|https?://|")()});l.breaks=b({},l.gfm,{br:t(l.br)("{2,}","*")(),text:t(l.gfm.text)("{2,}","*")()});u.rules=l;u.output=function(a,c,d){return(new u(c,d)).output(a)};u.prototype.output=function(a){for(var c="",d,b;a;)if(b=this.rules.escape.exec(a))a=a.substring(b[0].length),c+=b[1];else if(b=this.rules.autolink.exec(a))a=a.substring(b[0].length),
"@"===b[2]?(d=x(":"===b[1].charAt(6)?this.mangle(b[1].substring(7)):this.mangle(b[1])),b=this.mangle("mailto:")+d):b=d=x(b[1]),c+=this.renderer.link(b,null,d);else if(!this.inLink&&(b=this.rules.url.exec(a)))a=a.substring(b[0].length),b=d=x(b[1]),c+=this.renderer.link(b,null,d);else if(b=this.rules.tag.exec(a))!this.inLink&&/^<a /i.test(b[0])?this.inLink=!0:this.inLink&&/^<\/a>/i.test(b[0])&&(this.inLink=!1),a=a.substring(b[0].length),c+=this.options.sanitize?this.options.sanitizer?this.options.sanitizer(b[0]):
x(b[0]):b[0];else if(b=this.rules.link.exec(a))a=a.substring(b[0].length),this.inLink=!0,c+=this.outputLink(b,{href:b[2],title:b[3]}),this.inLink=!1;else if((b=this.rules.reflink.exec(a))||(b=this.rules.nolink.exec(a)))a=a.substring(b[0].length),d=(b[2]||b[1]).replace(/\s+/g," "),(d=this.links[d.toLowerCase()])&&d.href?(this.inLink=!0,c+=this.outputLink(b,d),this.inLink=!1):(c+=b[0].charAt(0),a=b[0].substring(1)+a);else if(b=this.rules.strong.exec(a))a=a.substring(b[0].length),c+=this.renderer.strong(this.output(b[2]||
b[1]));else if(b=this.rules.em.exec(a))a=a.substring(b[0].length),c+=this.renderer.em(this.output(b[2]||b[1]));else if(b=this.rules.code.exec(a))a=a.substring(b[0].length),c+=this.renderer.codespan(x(b[2].trim(),!0));else if(b=this.rules.br.exec(a))a=a.substring(b[0].length),c+=this.renderer.br();else if(b=this.rules.del.exec(a))a=a.substring(b[0].length),c+=this.renderer.del(this.output(b[1]));else if(b=this.rules.text.exec(a))a=a.substring(b[0].length),c+=this.renderer.text(x(this.smartypants(b[0])));
else if(a)throw Error("Infinite loop on byte: "+a.charCodeAt(0));return c};u.prototype.outputLink=function(a,c){var d=x(c.href);c=c.title?x(c.title):null;return"!"!==a[0].charAt(0)?this.renderer.link(d,c,this.output(a[1])):this.renderer.image(d,c,x(a[1]))};u.prototype.smartypants=function(a){return this.options.smartypants?a.replace(/---/g,"\u2014").replace(/--/g,"\u2013").replace(/(^|[-\u2014/(\[{"\s])'/g,"$1\u2018").replace(/'/g,"\u2019").replace(/(^|[-\u2014/(\[{\u2018\s])"/g,"$1\u201c").replace(/"/g,
"\u201d").replace(/\.{3}/g,"\u2026"):a};u.prototype.mangle=function(a){if(!this.options.mangle)return a;for(var c="",d=a.length,b=0,e;b<d;b++)e=a.charCodeAt(b),.5<Math.random()&&(e="x"+e.toString(16)),c+="\x26#"+e+";";return c};q.prototype.code=function(a,c,d){if(this.options.highlight){var b=this.options.highlight(a,c);null!=b&&b!==a&&(d=!0,a=b)}return c?'\x3cpre\x3e\x3ccode class\x3d"'+this.options.langPrefix+x(c,!0)+'"\x3e'+(d?a:x(a,!0))+"\n\x3c/code\x3e\x3c/pre\x3e\n":"\x3cpre\x3e\x3ccode\x3e"+
(d?a:x(a,!0))+"\n\x3c/code\x3e\x3c/pre\x3e"};q.prototype.blockquote=function(a){return"\x3cblockquote\x3e\n"+a+"\x3c/blockquote\x3e\n"};q.prototype.html=function(a){return a};q.prototype.heading=function(a,c,d){return"\x3ch"+c+' id\x3d"'+this.options.headerPrefix+d.toLowerCase().replace(/[^\w]+/g,"-")+'"\x3e'+a+"\x3c/h"+c+"\x3e\n"};q.prototype.hr=function(){return this.options.xhtml?"\x3chr/\x3e\n":"\x3chr\x3e\n"};q.prototype.list=function(a,c){c=c?"ol":"ul";return"\x3c"+c+"\x3e\n"+a+"\x3c/"+c+"\x3e\n"};
q.prototype.listitem=function(a){return"\x3cli\x3e"+a+"\x3c/li\x3e\n"};q.prototype.paragraph=function(a){return"\x3cp\x3e"+a+"\x3c/p\x3e\n"};q.prototype.table=function(a,c){return"\x3ctable\x3e\n\x3cthead\x3e\n"+a+"\x3c/thead\x3e\n\x3ctbody\x3e\n"+c+"\x3c/tbody\x3e\n\x3c/table\x3e\n"};q.prototype.tablerow=function(a){return"\x3ctr\x3e\n"+a+"\x3c/tr\x3e\n"};q.prototype.tablecell=function(a,c){var d=c.header?"th":"td";return(c.align?"\x3c"+d+' style\x3d"text-align:'+c.align+'"\x3e':"\x3c"+d+"\x3e")+
a+"\x3c/"+d+"\x3e\n"};q.prototype.strong=function(a){return"\x3cstrong\x3e"+a+"\x3c/strong\x3e"};q.prototype.em=function(a){return"\x3cem\x3e"+a+"\x3c/em\x3e"};q.prototype.codespan=function(a){return"\x3ccode\x3e"+a+"\x3c/code\x3e"};q.prototype.br=function(){return this.options.xhtml?"\x3cbr/\x3e":"\x3cbr\x3e"};q.prototype.del=function(a){return"\x3cdel\x3e"+a+"\x3c/del\x3e"};q.prototype.link=function(a,c,d){if(this.options.sanitize){try{var b=decodeURIComponent(v(a)).replace(/[^\w:]/g,"").toLowerCase()}catch(K){return d}if(0===
b.indexOf("javascript:")||0===b.indexOf("vbscript:")||0===b.indexOf("data:"))return d}this.options.baseUrl&&!e.test(a)&&(a=y(this.options.baseUrl,a));a='\x3ca href\x3d"'+a+'"';c&&(a+=' title\x3d"'+c+'"');return a+("\x3e"+d+"\x3c/a\x3e")};q.prototype.image=function(a,c,d){this.options.baseUrl&&!e.test(a)&&(a=y(this.options.baseUrl,a));a='\x3cimg src\x3d"'+a+'" alt\x3d"'+d+'"';c&&(a+=' title\x3d"'+c+'"');return a+=this.options.xhtml?"/\x3e":"\x3e"};q.prototype.text=function(a){return a};m.parse=function(a,
c,d){return(new m(c,d)).parse(a)};m.prototype.parse=function(a){this.inline=new u(a.links,this.options,this.renderer);this.tokens=a.reverse();for(a="";this.next();)a+=this.tok();return a};m.prototype.next=function(){return this.token=this.tokens.pop()};m.prototype.peek=function(){return this.tokens[this.tokens.length-1]||0};m.prototype.parseText=function(){for(var a=this.token.text;"text"===this.peek().type;)a+="\n"+this.next().text;return this.inline.output(a)};m.prototype.tok=function(){switch(this.token.type){case "space":return"";
case "hr":return this.renderer.hr();case "heading":return this.renderer.heading(this.inline.output(this.token.text),this.token.depth,this.token.text);case "code":return this.renderer.code(this.token.text,this.token.lang,this.token.escaped);case "table":var a="";var c="";var d,b;var e="";for(d=0;d<this.token.header.length;d++)e+=this.renderer.tablecell(this.inline.output(this.token.header[d]),{header:!0,align:this.token.align[d]});a+=this.renderer.tablerow(e);for(d=0;d<this.token.cells.length;d++){var f=
this.token.cells[d];e="";for(b=0;b<f.length;b++)e+=this.renderer.tablecell(this.inline.output(f[b]),{header:!1,align:this.token.align[b]});c+=this.renderer.tablerow(e)}return this.renderer.table(a,c);case "blockquote_start":for(c="";"blockquote_end"!==this.next().type;)c+=this.tok();return this.renderer.blockquote(c);case "list_start":c="";for(a=this.token.ordered;"list_end"!==this.next().type;)c+=this.tok();return this.renderer.list(c,a);case "list_item_start":for(c="";"list_item_end"!==this.next().type;)c+=
"text"===this.token.type?this.parseText():this.tok();return this.renderer.listitem(c);case "loose_item_start":for(c="";"list_item_end"!==this.next().type;)c+=this.tok();return this.renderer.listitem(c);case "html":return c=this.token.pre||this.options.pedantic?this.token.text:this.inline.output(this.token.text),this.renderer.html(c);case "paragraph":return this.renderer.paragraph(this.inline.output(this.token.text));case "text":return this.renderer.paragraph(this.parseText())}};var p={},e=/^$|^[a-z][a-z0-9+.-]*:|^[?#]/i;
g.exec=g;n.options=n.setOptions=function(a){b(n.defaults,a);return n};n.defaults={gfm:!0,tables:!0,breaks:!1,pedantic:!1,sanitize:!1,sanitizer:null,mangle:!0,smartLists:!1,silent:!1,highlight:null,langPrefix:"lang-",smartypants:!1,headerPrefix:"",renderer:new q,xhtml:!1,baseUrl:null};n.Parser=m;n.parser=m.parse;n.Renderer=q;n.Lexer=f;n.lexer=f.lex;n.InlineLexer=u;n.inlineLexer=u.output;n.parse=n;"undefined"!==typeof z&&"object"===typeof A?z.exports=n:"function"===typeof define&&define.amd?define(function(){return n}):
this.marked=n}).call(function(){return this||("undefined"!==typeof window?window:f)}())})()});require.register("components/main.component.svelte",function(f,v,z){function A(){this.registerDocumentation()}function u(f,e){var a,c,d,k,g,p,l,h,m,q,t=new n({root:e.root});t.on("mobilemenu",function(a){e.handleMobileMenu(a)});t.on("fontsize",function(a){e.handleFontSize(a)});e.refs.topbar=t;var u=new b({root:e.root});u.on("mobilemenu",function(a){e.handleMobileMenu(a)});e.refs.menu=u;return{c:function(){a=
document.createElement("div");t._fragment.c();c=document.createTextNode("\n  ");u._fragment.c();d=document.createTextNode("\n  ");k=document.createElement("div");g=document.createElement("div");g.innerHTML="Disclaimer:\x3cbr\x3eThis documentation is a work in progress. It isn't ready and shouldn't be shared with outsiders until the removal of this message. If you want to help build it, please \x3ca href\x3d\"https://github.com/peercoin/docs#peercoin-official-documentation-repository\"\x3eclick here\x3c/a\x3e.";
p=document.createTextNode("\n    ");l=document.createElement("div");h=document.createTextNode("\n    ");m=document.createElement("div");this.h()},h:function(){g.className="warn";l.className="menu-swipper";m.className=q="doc-container font-"+f.fontSize;k.className="body";a.className="MainComp"},m:function(b,w){b.insertBefore(a,w);t._mount(a,null);a.appendChild(c);u._mount(a,null);a.appendChild(d);a.appendChild(k);k.appendChild(g);k.appendChild(p);k.appendChild(l);k.appendChild(h);k.appendChild(m);
m.innerHTML=f.documentationHTML;e.refs.docContainer=m},p:function(a,c){a.documentationHTML&&(m.innerHTML=c.documentationHTML);a.fontSize&&q!==(q="doc-container font-"+c.fontSize)&&(m.className=q)},u:function(){m.innerHTML="";a.parentNode.removeChild(a)},d:function(){t.destroy(!1);e.refs.topbar===t&&(e.refs.topbar=null);u.destroy(!1);e.refs.menu===u&&(e.refs.menu=null);e.refs.docContainer===m&&(e.refs.docContainer=null)}}}function q(b){this._observers={pre:Object.create(null),post:Object.create(null)};
this._handlers=Object.create(null);this._bind=b._bind;this.options=b;this.root=b.root||this;this.store=this.root.store||b.store;this.refs={};this._state=m({fontSize:2,documentation:"",documentationHTML:""},b.data);var e=A.bind(this);b.root?this.root._oncreate.push(e):(this._oncreate=[e],this._beforecreate=[],this._aftercreate=[]);this._fragment=u(this._state,this);b.target&&(this._fragment.c(),this._fragment.m(b.target,b.anchor||null),this._lock=!0,x(this._beforecreate),x(this._oncreate),x(this._aftercreate),
this._lock=!1)}function m(b){for(var e,a,c=1,d=arguments.length;c<d;c++)for(e in a=arguments[c],a)b[e]=a[e];return b}function x(b){for(;b&&b.length;)b.pop()()}function y(b){this.destroy=t;this.fire("destroy");this.set=this.get=t;!1!==b&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function t(){}function D(b,e,a,c,d){for(var k in e)if(a[k]){var f=c[k],g=d[k],p=e[k];if(p)for(var l=0;l<p.length;l+=1){var h=p[l];h.__calling||(h.__calling=!0,h.call(b,f,g),h.__calling=!1)}}}var g=
v("../herodotus-settings.js"),b=v("./menu.component"),n=v("./topbar.component"),h=v("marked"),l=v("@fdaciuk/ajax");v("hammerjs");g=g&&g.__esModule?g["default"]:g;b=b&&b.__esModule?b["default"]:b;n=n&&n.__esModule?n["default"]:n;h=h&&h.__esModule?h["default"]:h;l=l&&l.__esModule?l["default"]:l;m(q.prototype,{getParentId:function(b){return"end"===b?null:b.id&&-1<["H1","H2"].indexOf(b.tagName)?{id:b.id,title:b.textContent}:this.getParentId(b.previousElementSibling||"end")},generateSearchList:function(){var b=
this,e=[];[].concat($jscomp.arrayFromIterable(document.querySelector(".doc-container").children)).forEach(function(a){var c=b.getParentId(a);c&&e.push({id:c.id,title:c.title,content:a.textContent})});return e},handleFontSize:function(b){switch(b.action){case "INCREASE":this.increaseFont();break;case "DECREASE":this.decreaseFont()}},handleMobileMenu:function(b){switch(b.action){case "TOGGLE":this.refs.topbar.set({isMenuOpen:this.refs.menu.toggle()});break;case "CLOSE":this.refs.menu.close();this.refs.topbar.set({isMenuOpen:!1});
break;case "OPEN":this.refs.menu.open(),this.refs.topbar.set({isMenuOpen:!0})}},increaseFont:function(){var b=this.get("fontSize");4<=b||this.set({fontSize:b+1})},decreaseFont:function(){var b=this.get("fontSize");1>=b||this.set({fontSize:b-1})},registerDocumentation:function(){var b=this;var e=g.allow_remote_documentation?g.remote_documentation_url:"documentation.md";l().get(e).then(function(a,c){b.set({documentation:a,documentationHTML:h(a)});b.refs.menu.startMenu(b.generateMenu());b.refs.topbar.refs.searchlist.set({searchList:b.generateSearchList()})})},
generateMenu:function(){var b=[],e=[],a;this.refs.docContainer.querySelectorAll("h1, h2").forEach(function(c){e.push({type:c.nodeName.toLowerCase(),label:c.textContent,id:c.id});"h1"===c.nodeName.toLowerCase()?(b.push({type:c.nodeName.toLowerCase(),label:c.textContent,id:c.id}),a=b[b.length-1],a.children=[]):"h2"===c.nodeName.toLowerCase()&&a.children.push({type:c.nodeName.toLowerCase(),label:c.textContent,id:c.id})});return{menuItems:b,menuItemsFlat:e}}},{destroy:y,get:function(b){return b?this._state[b]:
this._state},fire:function(b,e){if(b=b in this._handlers&&this._handlers[b].slice())for(var a=0;a<b.length;a+=1)b[a].call(this,e)},observe:function(b,e,a){var c=a&&a.defer?this._observers.post:this._observers.pre;(c[b]||(c[b]=[])).push(e);a&&!1===a.init||(e.__calling=!0,e.call(this,this._state[b]),e.__calling=!1);return{cancel:function(){var a=c[b].indexOf(e);~a&&c[b].splice(a,1)}}},on:function(b,e){if("teardown"===b)return this.on("destroy",e);var a=this._handlers[b]||(this._handlers[b]=[]);a.push(e);
return{cancel:function(){var c=a.indexOf(e);~c&&a.splice(c,1)}}},set:function(b){this._set(m({},b));this.root._lock||(this.root._lock=!0,x(this.root._beforecreate),x(this.root._oncreate),x(this.root._aftercreate),this.root._lock=!1)},teardown:y,_set:function(b){var e=this._state,a={},c=!1,d;for(d in b){var k=b[d];if(k!==e[d]||k&&"object"===typeof k||"function"===typeof k)a[d]=c=!0}c&&(this._state=m({},e,b),this._recompute(a,this._state),this._bind&&this._bind(a,this._state),this._fragment&&(D(this,
this._observers.pre,a,this._state,e),this._fragment.p(a,this._state),D(this,this._observers.post,a,this._state,e)))},_mount:function(b,e){this._fragment.m(b,e)},_unmount:function(){this._fragment&&this._fragment.u()}});q.prototype._recompute=t;z.exports=q});require.register("components/menu.component.svelte",function(f,v,y){function A(c,b){(new a(c)).on("swipeleft",b)}function u(){var a=this;window.onhashchange=function(){a.scrollToURLMenu()}}function q(a,d){function c(a){d.onAppScroll(this.scrollY)}
function e(a){d.fire("mobilemenu",{action:"CLOSE"})}var f,g,l,p,h,n,q,t,u,x;window.addEventListener("scroll",c);for(var v=a.menuItems,E=[],y=0;y<v.length;y+=1)E[y]=m(a,v,v[y],y,d);return{c:function(){f=document.createElement("div");g=document.createElement("div");p=document.createTextNode("\n  ");h=document.createElement("div");n=document.createElement("img");q=document.createTextNode("\n    ");t=document.createElement("ul");for(var a=0;a<E.length;a+=1)E[a].c();this.h()},h:function(){g.className=
l="MenuComp--overlay "+(a.isOpen?"active":"");g.addEventListener("click",e,!1);n.src="img/logo-green.svg";n.alt="Peercoin Docs";n.className="logo";t.className="menu";h.className=u="MenuComp "+(a.isOpen?"open":"");x=A.call(d,h,function(a){d.fire("mobilemenu",{action:"CLOSE"})})},m:function(a,c){a.insertBefore(f,c);f.appendChild(g);d.refs.overlay=g;f.appendChild(p);f.appendChild(h);h.appendChild(n);h.appendChild(q);h.appendChild(t);for(a=0;a<E.length;a+=1)E[a].m(t,null);d.refs.menu=h},p:function(a,
c){a.isOpen&&l!==(l="MenuComp--overlay "+(c.isOpen?"active":""))&&(g.className=l);var b=c.menuItems;if(a.menuItems){for(var e=0;e<b.length;e+=1)E[e]?E[e].p(a,c,b,b[e],e):(E[e]=m(c,b,b[e],e,d),E[e].c(),E[e].m(t,null));for(;e<E.length;e+=1)E[e].u(),E[e].d();E.length=b.length}a.isOpen&&u!==(u="MenuComp "+(c.isOpen?"open":""))&&(h.className=u)},u:function(){f.parentNode.removeChild(f);for(var a=0;a<E.length;a+=1)E[a].u()},d:function(){window.removeEventListener("scroll",c);g.removeEventListener("click",
e,!1);d.refs.overlay===g&&(d.refs.overlay=null);b(E);x.teardown();d.refs.menu===h&&(d.refs.menu=null)}}}function m(a,b,e,f,g){var c,d,k=e.label,l,h,p,w,n,m=0<e.children.length&&z(a,b,e,f,g);return{c:function(){c=document.createElement("li");d=document.createElement("a");l=document.createTextNode(k);p=document.createTextNode("\n            ");m&&m.c();this.h()},h:function(){d.href=h="#"+e.id;d.addEventListener("click",t,!1);d._svelte={component:g,menuItems:b,item_index:f};c.id=w="menu-"+e.id;c.className=
n=e.type},m:function(a,b){a.insertBefore(c,b);c.appendChild(d);d.appendChild(l);c.appendChild(p);m&&m.m(c,null)},p:function(a,b,e,f,p){a.menuItems&&k!==(k=f.label)&&(l.data=k);a.menuItems&&h!==(h="#"+f.id)&&(d.href=h);d._svelte.menuItems=e;d._svelte.item_index=p;0<f.children.length?m?m.p(a,b,e,f,p):(m=z(b,e,f,p,g),m.c(),m.m(c,null)):m&&(m.u(),m.d(),m=null);a.menuItems&&w!==(w="menu-"+f.id)&&(c.id=w);a.menuItems&&n!==(n=f.type)&&(c.className=n)},u:function(){c.parentNode.removeChild(c);m&&m.u()},d:function(){d.removeEventListener("click",
t,!1);m&&m.d()}}}function x(a,b,e,f,g,h,l,p){var c,d,k=h.label,w,n,m,q;return{c:function(){c=document.createElement("li");d=document.createElement("a");w=document.createTextNode(k);this.h()},h:function(){d.href=n="#"+h.id;d.addEventListener("click",D,!1);d._svelte={component:p,children_1:g,subitem_index:l};c.id=m="menu-"+h.id;c.className=q=h.type},m:function(a,b){a.insertBefore(c,b);c.appendChild(d);d.appendChild(w)},p:function(a,b,e,f,g,h,l,p){a.menuItems&&k!==(k=l.label)&&(w.data=k);a.menuItems&&
n!==(n="#"+l.id)&&(d.href=n);d._svelte.children_1=h;d._svelte.subitem_index=p;a.menuItems&&m!==(m="menu-"+l.id)&&(c.id=m);a.menuItems&&q!==(q=l.type)&&(c.className=q)},u:function(){c.parentNode.removeChild(c)},d:function(){d.removeEventListener("click",D,!1)}}}function z(a,d,e,f,g){for(var c,k=e.children,h=[],l=0;l<k.length;l+=1)h[l]=x(a,d,e,f,k,k[l],l,g);return{c:function(){c=document.createElement("ul");for(var a=0;a<h.length;a+=1)h[a].c();this.h()},h:function(){c.className="subsection"},m:function(a,
b){a.insertBefore(c,b);for(a=0;a<h.length;a+=1)h[a].m(c,null)},p:function(a,b,d,e,f){var k=e.children;if(a.menuItems){for(var l=0;l<k.length;l+=1)h[l]?h[l].p(a,b,d,e,f,k,k[l],l):(h[l]=x(b,d,e,f,k,k[l],l,g),h[l].c(),h[l].m(c,null));for(;l<h.length;l+=1)h[l].u(),h[l].d();h.length=k.length}},u:function(){c.parentNode.removeChild(c);for(var a=0;a<h.length;a+=1)h[a].u()},d:function(){b(h)}}}function t(a){this._svelte.component.scrollToItem(this._svelte.menuItems[this._svelte.item_index],a)}function D(a){this._svelte.component.scrollToItem(this._svelte.children_1[this._svelte.subitem_index],
a)}function g(a){this._observers={pre:Object.create(null),post:Object.create(null)};this._handlers=Object.create(null);this._bind=a._bind;this.options=a;this.root=a.root||this;this.store=this.root.store||a.store;this.refs={};this._state=n({menuItems:[],menuItemsFlat:[],isOpen:!1,prevY:0},a.data);var c=u.bind(this);a.root?this.root._oncreate.push(c):this._oncreate=[c];this._fragment=q(this._state,this);a.target&&(this._fragment.c(),this._fragment.m(a.target,a.anchor||null),h(this._oncreate))}function b(a){for(var c=
0;c<a.length;c+=1)a[c]&&a[c].d()}function n(a){for(var c,b,e=1,f=arguments.length;e<f;e++)for(c in b=arguments[e],b)a[c]=b[c];return a}function h(a){for(;a&&a.length;)a.pop()()}function l(a){this.destroy=p;this.fire("destroy");this.set=this.get=p;!1!==a&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function p(){}function e(a,b,e,f,g){for(var c in b)if(e[c]){var d=f[c],k=g[c],l=b[c];if(l)for(var h=0;h<l.length;h+=1){var p=l[h];p.__calling||(p.__calling=!0,p.call(a,d,k),p.__calling=
!1)}}}var a=v("hammerjs");a=a&&a.__esModule?a["default"]:a;n(g.prototype,{onAppScroll:function(a){a=this.get("menuItemsFlat");a=$jscomp.makeIterator(a.entries());for(var c=a.next();!c.done;c=a.next()){c=$jscomp.makeIterator(c.value);c.next();c=c.next().value;var b=document.getElementById(c.id),e=b.getBoundingClientRect().top;b=b.getBoundingClientRect().bottom;if(0<=e&&b<=window.innerHeight){[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu li.active"))).map(function(a){return a.classList.remove("active")});
a=document.getElementById("menu-"+c.id);a.classList.add("active");c=a.parentNode;c.classList.contains("subsection")&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),c.classList.add("show"));0<a.querySelectorAll(".subsection").length&&([].concat($jscomp.arrayFromIterable(document.querySelectorAll(".menu .subsection"))).map(function(a){return a.classList.remove("show")}),a.querySelector(".subsection").classList.add("show"));
break}}},startMenu:function(a){var c=this;this.set(a);setTimeout(function(){c.scrollToURLMenu()},10)},scrollTop:function(){window.scrollTo(0,0);this.close()},scrollToURLMenu:function(){var a=window.location.hash.substr(2),b=this.get("menuItemsFlat").filter(function(c){return c.id===a});0<b.length?(b=document.getElementById(b[0].id),b=window.scrollY+b.getBoundingClientRect().top-70,window.scrollTo(0,b)):window.scrollTo(0,1)},toggle:function(){this.set({isOpen:!this.refs.menu.isOpen});return this.refs.menu.isOpen},
close:function(){this.set({isOpen:!1})},open:function(){this.set({isOpen:!0})},scrollToItem:function(a,b){b&&b.preventDefault();window.location.hash="/"+a.id;this.get("menuItemsFlat");a=window.scrollY+document.getElementById(a.id).getBoundingClientRect().top-70;window.scrollTo(0,a);this.fire("mobilemenu",{action:"CLOSE"})}},{destroy:l,get:function(a){return a?this._state[a]:this._state},fire:function(a,b){if(a=a in this._handlers&&this._handlers[a].slice())for(var c=0;c<a.length;c+=1)a[c].call(this,
b)},observe:function(a,b,e){var c=e&&e.defer?this._observers.post:this._observers.pre;(c[a]||(c[a]=[])).push(b);e&&!1===e.init||(b.__calling=!0,b.call(this,this._state[a]),b.__calling=!1);return{cancel:function(){var d=c[a].indexOf(b);~d&&c[a].splice(d,1)}}},on:function(a,b){if("teardown"===a)return this.on("destroy",b);var c=this._handlers[a]||(this._handlers[a]=[]);c.push(b);return{cancel:function(){var a=c.indexOf(b);~a&&c.splice(a,1)}}},set:function(a){this._set(n({},a));this.root._lock||(this.root._lock=
!0,h(this.root._beforecreate),h(this.root._oncreate),h(this.root._aftercreate),this.root._lock=!1)},teardown:l,_set:function(a){var c=this._state,b={},f=!1,g;for(g in a){var l=a[g];if(l!==c[g]||l&&"object"===typeof l||"function"===typeof l)b[g]=f=!0}f&&(this._state=n({},c,a),this._recompute(b,this._state),this._bind&&this._bind(b,this._state),this._fragment&&(e(this,this._observers.pre,b,this._state,c),this._fragment.p(b,this._state),e(this,this._observers.post,b,this._state,c)))},_mount:function(a,
b){this._fragment.m(a,b)},_unmount:function(){this._fragment&&this._fragment.u()}});g.prototype._recompute=p;y.exports=g});require.register("components/searchlist.component.svelte",function(f,v,y){function A(){var b=this;this.observe("searchList",function(a){b.fuse=b.setFuse(a)})}function u(b,a){function c(c){a.toggleSearch()}function d(c){a.closeSearch()}function e(c){a.handleSearch(c)}function f(c){a.isClosable(c)}var g,l,h,p,n,q,t,u,v,y,A,z,B,H=1<b.filteredList.length&&m(b,a),J=1>b.filteredList.length&&
x(b,a);return{c:function(){g=document.createElement("div");l=document.createElement("div");h=D("svg");p=D("use");n=document.createTextNode("\n  \n  ");q=document.createElement("div");u=document.createTextNode("\n\n  ");v=document.createElement("div");y=document.createElement("input");A=document.createTextNode("\n    ");H&&H.c();z=document.createTextNode("\n\n    ");J&&J.c();this.h()},h:function(){p.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-search.svg#icon");p.setAttribute("preserveAspectRatio",
"xMidYMid");h.setAttribute("class","svg-icon");h.setAttribute("xmlns","http://www.w3.org/2000/svg");h.setAttribute("role","img");h.setAttribute("viewBox","0 0 15 15");h.addEventListener("click",c,!1);l.className="btn btn-svg";q.className=t="SearchListComp--overlay "+(b.isOpen?"active":"");q.addEventListener("click",d,!1);y.type="text";y.className="filter-input";y.placeholder="Search here...";y.addEventListener("input",e,!1);y.addEventListener("keydown",f,!1);v.className=B="search-popup "+(b.isOpen?
"open":"");g.className="SearchListComp"},m:function(c,b){c.insertBefore(g,b);g.appendChild(l);l.appendChild(h);h.appendChild(p);g.appendChild(n);g.appendChild(q);g.appendChild(u);g.appendChild(v);v.appendChild(y);a.refs.input=y;v.appendChild(A);H&&H.m(v,null);v.appendChild(z);J&&J.m(v,null)},p:function(c,b){c.isOpen&&t!==(t="SearchListComp--overlay "+(b.isOpen?"active":""))&&(q.className=t);1<b.filteredList.length?H?H.p(c,b):(H=m(b,a),H.c(),H.m(v,z)):H&&(H.u(),H.d(),H=null);1>b.filteredList.length?
J||(J=x(b,a),J.c(),J.m(v,null)):J&&(J.u(),J.d(),J=null);c.isOpen&&B!==(B="search-popup "+(b.isOpen?"open":""))&&(v.className=B)},u:function(){g.parentNode.removeChild(g);H&&H.u();J&&J.u()},d:function(){h.removeEventListener("click",c,!1);q.removeEventListener("click",d,!1);y.removeEventListener("input",e,!1);y.removeEventListener("keydown",f,!1);a.refs.input===y&&(a.refs.input=null);H&&H.d();J&&J.d()}}}function q(b,a,c,d,f){var e,g,k,l=c.item.title,h,p,n,m=c.item.content.substr(0,100),q,t,u;return{c:function(){e=
document.createElement("li");g=document.createElement("a");k=document.createElement("div");h=document.createTextNode(l);p=document.createTextNode("\n          ");n=document.createElement("div");q=document.createTextNode(m);t=document.createTextNode("...");this.h()},h:function(){k.className="section-title";n.className="section-text";g.href=u="#/"+c.item.id;g.addEventListener("click",z,!1);g._svelte={component:f};e.className="item"},m:function(a,c){a.insertBefore(e,c);e.appendChild(g);g.appendChild(k);
k.appendChild(h);g.appendChild(p);g.appendChild(n);n.appendChild(q);n.appendChild(t)},p:function(a,c,b,d,e){a.filteredList&&l!==(l=d.item.title)&&(h.data=l);a.filteredList&&m!==(m=d.item.content.substr(0,100))&&(q.data=m);a.filteredList&&u!==(u="#/"+d.item.id)&&(g.href=u)},u:function(){e.parentNode.removeChild(e)},d:function(){g.removeEventListener("click",z,!1)}}}function m(b,a){for(var c,d=b.filteredList,e=[],g=0;g<d.length;g+=1)e[g]=q(b,d,d[g],g,a);return{c:function(){c=document.createElement("ul");
for(var a=0;a<e.length;a+=1)e[a].c();this.h()},h:function(){c.className="filtered-list"},m:function(a,b){a.insertBefore(c,b);for(a=0;a<e.length;a+=1)e[a].m(c,null)},p:function(b,d){var g=d.filteredList;if(b.filteredList){for(var f=0;f<g.length;f+=1)e[f]?e[f].p(b,d,g,g[f],f):(e[f]=q(d,g,g[f],f,a),e[f].c(),e[f].m(c,null));for(;f<e.length;f+=1)e[f].u(),e[f].d();e.length=g.length}},u:function(){c.parentNode.removeChild(c);for(var a=0;a<e.length;a+=1)e[a].u()},d:function(){for(var a=0;a<e.length;a+=1)e[a]&&
e[a].d()}}}function x(b,a){var c;return{c:function(){c=document.createElement("h2");c.textContent="No matches found.";this.h()},h:function(){c.className="empty-message"},m:function(a,b){a.insertBefore(c,b)},u:function(){c.parentNode.removeChild(c)},d:g}}function z(b){this._svelte.component.closeSearch()}function t(e){this._observers={pre:Object.create(null),post:Object.create(null)};this._handlers=Object.create(null);this._bind=e._bind;this.options=e;this.root=e.root||this;this.store=this.root.store||
e.store;this.refs={};this._state=b({searchList:[],filteredList:[],fuse:null,isOpen:!1},e.data);var a=A.bind(this);e.root?this.root._oncreate.push(a):this._oncreate=[a];this._fragment=u(this._state,this);e.target&&(this._fragment.c(),this._fragment.m(e.target,e.anchor||null),n(this._oncreate))}function D(b){return document.createElementNS("http://www.w3.org/2000/svg",b)}function g(){}function b(b){for(var a,c,d=1,e=arguments.length;d<e;d++)for(a in c=arguments[d],c)b[a]=c[a];return b}function n(b){for(;b&&
b.length;)b.pop()()}function h(b){this.destroy=g;this.fire("destroy");this.set=this.get=g;!1!==b&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function l(b,a,c,d,f){for(var e in a)if(c[e]){var g=d[e],k=f[e],l=a[e];if(l)for(var h=0;h<l.length;h+=1){var p=l[h];p.__calling||(p.__calling=!0,p.call(b,g,k),p.__calling=!1)}}}var p=v("fuse.js");p=p&&p.__esModule?p["default"]:p;b(t.prototype,{openSearch:function(){this.set({isOpen:!0});this.refs.input.focus()},closeSearch:function(){this.set({isOpen:!1})},
toggleSearch:function(){this.get("isOpen")?this.closeSearch():this.openSearch()},isClosable:function(b){27===b.keyCode&&this.closeSearch()},setFuse:function(b){1>b.length||this.set({fuse:new p(b,{shouldSort:!0,findAllMatches:!0,includeMatches:!0,threshold:.3,location:0,distance:1E4,maxPatternLength:32,minMatchCharLength:3,keys:["content"]})})},handleSearch:function(b){3<b.target.value.length?this.set({filteredList:this.get("fuse").search(b.target.value)}):this.set({filteredList:[]});console.log(this.get("filteredList"))}},
{destroy:h,get:function(b){return b?this._state[b]:this._state},fire:function(b,a){if(b=b in this._handlers&&this._handlers[b].slice())for(var c=0;c<b.length;c+=1)b[c].call(this,a)},observe:function(b,a,c){var d=c&&c.defer?this._observers.post:this._observers.pre;(d[b]||(d[b]=[])).push(a);c&&!1===c.init||(a.__calling=!0,a.call(this,this._state[b]),a.__calling=!1);return{cancel:function(){var c=d[b].indexOf(a);~c&&d[b].splice(c,1)}}},on:function(b,a){if("teardown"===b)return this.on("destroy",a);var c=
this._handlers[b]||(this._handlers[b]=[]);c.push(a);return{cancel:function(){var b=c.indexOf(a);~b&&c.splice(b,1)}}},set:function(e){this._set(b({},e));this.root._lock||(this.root._lock=!0,n(this.root._beforecreate),n(this.root._oncreate),n(this.root._aftercreate),this.root._lock=!1)},teardown:h,_set:function(e){var a=this._state,c={},d=!1,f;for(f in e){var g=e[f];if(g!==a[f]||g&&"object"===typeof g||"function"===typeof g)c[f]=d=!0}d&&(this._state=b({},a,e),this._recompute(c,this._state),this._bind&&
this._bind(c,this._state),this._fragment&&(l(this,this._observers.pre,c,this._state,a),this._fragment.p(c,this._state),l(this,this._observers.post,c,this._state,a)))},_mount:function(b,a){this._fragment.m(b,a)},_unmount:function(){this._fragment&&this._fragment.u()}});t.prototype._recompute=g;y.exports=t});require.register("components/topbar.component.svelte",function(f,v,y){function A(b,f){function e(a){f.fire("mobilemenu",{action:"TOGGLE"})}function a(a){f.scrollTop()}var c,d,g,h,l,p,m,t,v,y,A,
z,B=b.settings.allow_font_size_control&&u(b,f),D=new n({root:f.root});f.refs.searchlist=D;var I=b.settings.allow_topbar_link&&q(b,f);return{c:function(){c=document.createElement("div");d=document.createElement("div");g=x("svg");h=x("use");p=document.createTextNode("\n\n    ");m=document.createElement("div");m.innerHTML='\x3cimg src\x3d"img/logo.svg" alt\x3d"Peercoin Docs"\x3e';t=document.createTextNode("\n\n    ");B&&B.c();v=document.createTextNode("\n\n    ");y=document.createElement("hr");A=document.createTextNode("\n\n    ");
D._fragment.c();z=document.createTextNode("\n\n    ");I&&I.c();this.h()},h:function(){h.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","img/icon-menu-open.svg#icon");h.setAttribute("preserveAspectRatio","xMidYMid");var f=l="svg-icon "+(b.isMenuOpen?"off":"");g.setAttribute("class",f);g.setAttribute("xmlns","http://www.w3.org/2000/svg");g.setAttribute("role","img");g.setAttribute("viewBox","0 0 40 28");d.className="menu-button";d.addEventListener("click",e,!1);m.className="logo";m.addEventListener("click",
a,!1);c.className="TopbarComp"},m:function(a,b){a.insertBefore(c,b);c.appendChild(d);d.appendChild(g);g.appendChild(h);c.appendChild(p);c.appendChild(m);c.appendChild(t);B&&B.m(c,null);c.appendChild(v);c.appendChild(y);c.appendChild(A);D._mount(c,null);c.appendChild(z);I&&I.m(c,null)},p:function(a,b){a.isMenuOpen&&l!==(l="svg-icon "+(b.isMenuOpen?"off":""))&&g.setAttribute("class",l);b.settings.allow_font_size_control?B||(B=u(b,f),B.c(),B.m(c,v)):B&&(B.u(),B.d(),B=null);b.settings.allow_topbar_link?
I?I.p(a,b):(I=q(b,f),I.c(),I.m(c,null)):I&&(I.u(),I.d(),I=null)},u:function(){c.parentNode.removeChild(c);B&&B.u();I&&I.u()},d:function(){d.removeEventListener("click",e,!1);m.removeEventListener("click",a,!1);B&&B.d();D.destroy(!1);f.refs.searchlist===D&&(f.refs.searchlist=null);I&&I.d()}}}function u(b,f){function e(a){f.fire("fontsize",{action:"DECREASE"})}function a(a){f.fire("fontsize",{action:"INCREASE"})}var c,d,g,h;return{c:function(){c=document.createElement("div");d=document.createElement("div");
d.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-minus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';g=document.createTextNode("\n      ");h=document.createElement("div");h.innerHTML='\x3csvg class\x3d"svg-icon" xmlns\x3d"http://www.w3.org/2000/svg" role\x3d"img" viewBox\x3d"0 0 26 20"\x3e\x3cuse xlink:href\x3d"img/icon-font-plus.svg#icon" preserveAspectRatio\x3d"xMidYMid"\x3e\x3c/use\x3e\n        \x3c/svg\x3e';
this.h()},h:function(){d.className="btn btn-svg v-center";d.addEventListener("click",e,!1);h.className="btn btn-svg v-center";h.addEventListener("click",a,!1);c.className="btn-group"},m:function(a,b){a.insertBefore(c,b);c.appendChild(d);c.appendChild(g);c.appendChild(h)},u:function(){c.parentNode.removeChild(c)},d:function(){d.removeEventListener("click",e,!1);h.removeEventListener("click",a,!1)}}}function q(b,f){var e,a,c,d=b.settings.topbar_link_label,g,h;return{c:function(){e=document.createElement("a");
a=document.createElement("span");a.textContent="Contribute to";c=document.createElement("b");g=document.createTextNode(d);this.h()},h:function(){e.href=h=b.settings.topbar_link_url;e.className="btn btn-last-link"},m:function(b,d){b.insertBefore(e,d);e.appendChild(a);e.appendChild(c);c.appendChild(g)},p:function(a,b){a.settings&&d!==(d=b.settings.topbar_link_label)&&(g.data=d);a.settings&&h!==(h=b.settings.topbar_link_url)&&(e.href=h)},u:function(){e.parentNode.removeChild(e)},d:z}}function m(b){this._observers=
{pre:Object.create(null),post:Object.create(null)};this._handlers=Object.create(null);this._bind=b._bind;this.options=b;this.root=b.root||this;this.store=this.root.store||b.store;this.refs={};this._state=t({settings:h},b.data);b.root||(this._oncreate=[],this._beforecreate=[],this._aftercreate=[]);this._fragment=A(this._state,this);b.target&&(this._fragment.c(),this._fragment.m(b.target,b.anchor||null),this._lock=!0,D(this._beforecreate),D(this._oncreate),D(this._aftercreate),this._lock=!1)}function x(b){return document.createElementNS("http://www.w3.org/2000/svg",
b)}function z(){}function t(b){for(var f,e,a=1,c=arguments.length;a<c;a++)for(f in e=arguments[a],e)b[f]=e[f];return b}function D(b){for(;b&&b.length;)b.pop()()}function g(b){this.destroy=z;this.fire("destroy");this.set=this.get=z;!1!==b&&this._fragment.u();this._fragment.d();this._fragment=this._state=null}function b(b,f,e,a,c){for(var d in f)if(e[d]){var g=a[d],h=c[d],l=f[d];if(l)for(var p=0;p<l.length;p+=1){var m=l[p];m.__calling||(m.__calling=!0,m.call(b,g,h),m.__calling=!1)}}}var n=v("./searchlist.component"),
h=v("../herodotus-settings.js");n=n&&n.__esModule?n["default"]:n;h=h&&h.__esModule?h["default"]:h;t(m.prototype,{destroy:g,get:function(b){return b?this._state[b]:this._state},fire:function(b,f){if(b=b in this._handlers&&this._handlers[b].slice())for(var e=0;e<b.length;e+=1)b[e].call(this,f)},observe:function(b,f,e){var a=e&&e.defer?this._observers.post:this._observers.pre;(a[b]||(a[b]=[])).push(f);e&&!1===e.init||(f.__calling=!0,f.call(this,this._state[b]),f.__calling=!1);return{cancel:function(){var c=
a[b].indexOf(f);~c&&a[b].splice(c,1)}}},on:function(b,f){if("teardown"===b)return this.on("destroy",f);var e=this._handlers[b]||(this._handlers[b]=[]);e.push(f);return{cancel:function(){var a=e.indexOf(f);~a&&e.splice(a,1)}}},set:function(b){this._set(t({},b));this.root._lock||(this.root._lock=!0,D(this.root._beforecreate),D(this.root._oncreate),D(this.root._aftercreate),this.root._lock=!1)},teardown:g,_set:function(f){var g=this._state,e={},a=!1,c;for(c in f){var d=f[c];if(d!==g[c]||d&&"object"===
typeof d||"function"===typeof d)e[c]=a=!0}a&&(this._state=t({},g,f),this._recompute(e,this._state),this._bind&&this._bind(e,this._state),this._fragment&&(b(this,this._observers.pre,e,this._state,g),this._fragment.p(e,this._state),b(this,this._observers.post,e,this._state,g)))},_mount:function(b,f){this._fragment.m(b,f)},_unmount:function(){this._fragment&&this._fragment.u()}});m.prototype._recompute=z;y.exports=m});require.register("herodotus-settings.js",function(f,v,y){Object.defineProperty(f,"__esModule",
{value:!0});f.default={documentation_name:"My awesome documentation",allow_topbar_link:!0,topbar_link_label:"Peercoin Docs Repo",topbar_link_url:"https://github.com/peercoin/docs#peercoin-official-documentation-repository",allow_font_size_control:!0,allow_remote_documentation:!1,remote_documentation_url:""}});require.register("initialize.js",function(f,v,y){var z=(f=v("./components/main.component"))&&f.__esModule?f:{default:f};document.addEventListener("DOMContentLoaded",function(){window.mainComponent=
new z.default({target:document.querySelector("main")})})});require.alias("@fdaciuk/ajax/dist/ajax.min.js","@fdaciuk/ajax");require.alias("fuse.js/dist/fuse.js","fuse.js");require.alias("hammerjs/hammer.js","hammerjs");require.alias("marked/lib/marked.js","marked");require.register("___globals___",function(f,v,y){})})();require("___globals___");require("initialize");